<?php
declare(strict_types=1);

$manufacturingEscape = $manufacturingEscape ?? static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
$state = is_array($manufacturingData['state'] ?? null) ? $manufacturingData['state'] : [];
?>
<?php if ($manufacturingSection === 'boms'): ?>
    <?php $boms = is_array($manufacturingData['boms'] ?? null) ? $manufacturingData['boms'] : []; ?>
    <div class="grid gap-5" data-manufacturing-bom-workspace>
        <div class="flex items-end justify-between gap-3"><div><h3 class="text-sm font-semibold">Bills of Materials</h3><p class="mt-1 text-xs text-muted-foreground"><?= count($boms) ?> revisions in this company</p></div><span class="text-xs text-muted-foreground">Nested explosion and owner-verified costing</span></div>
        <div class="overflow-x-auto"><table class="w-full min-w-[46rem] text-sm"><thead class="border-b text-left text-xs text-muted-foreground"><tr><th class="px-3 py-2">BOM</th><th class="px-3 py-2">Item</th><th class="px-3 py-2">Revision</th><th class="px-3 py-2">Effective</th><th class="px-3 py-2">Cost</th><th class="px-3 py-2">Status</th><th class="px-3 py-2">Actions</th></tr></thead><tbody class="divide-y"><?php foreach ($boms as $bom): ?><tr><td class="px-3 py-3 font-medium"><?= $manufacturingEscape((string) $bom['bom_code']) ?><?= !empty($bom['is_alternative']) ? ' <span class="text-xs text-muted-foreground">Alternative</span>' : '' ?></td><td class="px-3 py-3 font-mono text-xs"><?= $manufacturingEscape((string) $bom['item_key']) ?></td><td class="px-3 py-3"><?= (int) $bom['revision'] ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $bom['effective_from']) ?><?= (string) ($bom['effective_to'] ?? '') !== '' ? ' to ' . $manufacturingEscape((string) $bom['effective_to']) : '' ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $bom['currency']) ?> <?= $manufacturingEscape((string) $bom['total_cost']) ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $bom['lifecycle_status']) ?></td><td class="px-3 py-3"><a class="inline-flex size-8 items-center justify-center rounded-md border" aria-label="Open <?= $manufacturingEscape((string) $bom['bom_code']) ?>" href="?view=manufacturing&amp;section=boms&amp;bom=<?= $manufacturingEscape((string) $bom['bom_key']) ?>"><span class="material-symbols-rounded text-base" aria-hidden="true">edit</span></a></td></tr><?php endforeach; ?><?php if ($boms === []): ?><tr><td colspan="7" class="px-3 py-10 text-center text-muted-foreground">No BOM revisions yet.</td></tr><?php endif; ?></tbody></table></div>
    </div>
<?php elseif ($manufacturingSection === 'operations'): ?>
    <?php $operations = is_array($manufacturingData['operations'] ?? null) ? $manufacturingData['operations'] : []; $routings = is_array($manufacturingData['routings'] ?? null) ? $manufacturingData['routings'] : []; ?>
    <div class="grid gap-7">
        <section aria-labelledby="manufacturing-operations-list">
            <div class="flex items-center justify-between gap-3"><div><h3 id="manufacturing-operations-list" class="text-sm font-semibold">Operations</h3><p class="mt-1 text-xs text-muted-foreground"><?= count($operations) ?> company records</p></div></div>
            <div class="mt-3 overflow-x-auto"><table class="w-full min-w-[40rem] text-sm"><thead class="border-b text-left text-xs text-muted-foreground"><tr><th class="px-3 py-2">Code</th><th class="px-3 py-2">Operation</th><th class="px-3 py-2">Rate</th><th class="px-3 py-2">Sub-operations</th><th class="px-3 py-2">Status</th><th class="px-3 py-2">Actions</th></tr></thead><tbody class="divide-y"><?php foreach ($operations as $operation): ?><tr><td class="px-3 py-3 font-medium"><?= $manufacturingEscape((string) $operation['operation_code']) ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $operation['operation_name']) ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $operation['hourly_rate']) ?></td><td class="px-3 py-3"><?= count($operation['sub_operations'] ?? []) ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $operation['record_status']) ?></td><td class="px-3 py-3"><a class="inline-flex size-8 items-center justify-center rounded-md border" aria-label="Edit <?= $manufacturingEscape((string) $operation['operation_code']) ?>" href="?view=manufacturing&amp;section=operations&amp;operation=<?= $manufacturingEscape((string) $operation['operation_key']) ?>"><span class="material-symbols-rounded text-base" aria-hidden="true">edit</span></a></td></tr><?php endforeach; ?><?php if ($operations === []): ?><tr><td colspan="6" class="px-3 py-10 text-center text-muted-foreground">No operations yet.</td></tr><?php endif; ?></tbody></table></div>
        </section>
        <section aria-labelledby="manufacturing-routings-list">
            <div><h3 id="manufacturing-routings-list" class="text-sm font-semibold">Routings</h3><p class="mt-1 text-xs text-muted-foreground"><?= count($routings) ?> reusable paths</p></div>
            <div class="mt-3 overflow-x-auto"><table class="w-full min-w-[34rem] text-sm"><thead class="border-b text-left text-xs text-muted-foreground"><tr><th class="px-3 py-2">Code</th><th class="px-3 py-2">Routing</th><th class="px-3 py-2">Operations</th><th class="px-3 py-2">Status</th><th class="px-3 py-2">Actions</th></tr></thead><tbody class="divide-y"><?php foreach ($routings as $routing): ?><tr><td class="px-3 py-3 font-medium"><?= $manufacturingEscape((string) $routing['routing_code']) ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $routing['routing_name']) ?></td><td class="px-3 py-3"><?= count($routing['operations'] ?? []) ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $routing['record_status']) ?></td><td class="px-3 py-3"><a class="inline-flex size-8 items-center justify-center rounded-md border" aria-label="Edit <?= $manufacturingEscape((string) $routing['routing_code']) ?>" href="?view=manufacturing&amp;section=operations&amp;routing=<?= $manufacturingEscape((string) $routing['routing_key']) ?>"><span class="material-symbols-rounded text-base" aria-hidden="true">edit</span></a></td></tr><?php endforeach; ?><?php if ($routings === []): ?><tr><td colspan="5" class="px-3 py-10 text-center text-muted-foreground">No routings yet.</td></tr><?php endif; ?></tbody></table></div>
        </section>
    </div>
<?php elseif ($manufacturingSection === 'workstations'): ?>
    <?php $types = is_array($manufacturingData['workstation_types'] ?? null) ? $manufacturingData['workstation_types'] : []; $stations = is_array($manufacturingData['workstations'] ?? null) ? $manufacturingData['workstations'] : []; $downtimes = is_array($manufacturingData['downtimes'] ?? null) ? $manufacturingData['downtimes'] : []; $floor = is_array($manufacturingData['plant_floor'] ?? null) ? $manufacturingData['plant_floor'] : []; ?>
    <div class="grid gap-7">
        <section data-manufacturing-plant-floor aria-labelledby="manufacturing-floor-state"><div><h3 id="manufacturing-floor-state" class="text-sm font-semibold">Plant Floor</h3><p class="mt-1 text-xs text-muted-foreground">Live state from persisted workstations and downtime</p></div><div class="mt-3 grid gap-2 sm:grid-cols-2"><?php foreach ($floor as $station): ?><div class="flex items-center justify-between gap-3 bg-muted/40 p-3"><div class="min-w-0"><p class="truncate text-sm font-medium"><?= $manufacturingEscape((string) $station['workstation_code']) ?></p><p class="truncate text-xs text-muted-foreground"><?= $manufacturingEscape((string) $station['plant_floor_name']) ?></p></div><span class="text-xs font-semibold <?= (string) $station['state'] === 'DOWN' ? 'text-destructive' : 'text-emerald-700' ?>"><?= $manufacturingEscape((string) $station['state']) ?></span></div><?php endforeach; ?><?php if ($floor === []): ?><p class="text-sm text-muted-foreground">No active stations on the Plant Floor.</p><?php endif; ?></div></section>
        <section aria-labelledby="manufacturing-types-list"><div><h3 id="manufacturing-types-list" class="text-sm font-semibold">Workstation Types</h3><p class="mt-1 text-xs text-muted-foreground"><?= count($types) ?> calendars</p></div><div class="mt-3 divide-y"><?php foreach ($types as $type): ?><div class="flex items-center justify-between gap-3 py-3"><div><p class="text-sm font-medium"><?= $manufacturingEscape((string) $type['workstation_type_code']) ?> · <?= $manufacturingEscape((string) $type['workstation_type_name']) ?></p><p class="mt-1 text-xs text-muted-foreground"><?= count($type['working_hours'] ?? []) ?> working intervals · <?= count($type['operation_keys'] ?? []) ?> operations</p></div><a class="inline-flex size-8 shrink-0 items-center justify-center rounded-md border" aria-label="Edit Workstation Type" href="?view=manufacturing&amp;section=workstations&amp;workstation_type=<?= $manufacturingEscape((string) $type['workstation_type_key']) ?>"><span class="material-symbols-rounded text-base" aria-hidden="true">edit</span></a></div><?php endforeach; ?><?php if ($types === []): ?><p class="py-8 text-center text-sm text-muted-foreground">No Workstation Types yet.</p><?php endif; ?></div></section>
        <section aria-labelledby="manufacturing-stations-list"><div><h3 id="manufacturing-stations-list" class="text-sm font-semibold">Workstations</h3><p class="mt-1 text-xs text-muted-foreground"><?= count($stations) ?> capacity resources</p></div><div class="mt-3 overflow-x-auto"><table class="w-full min-w-[42rem] text-sm"><thead class="border-b text-left text-xs text-muted-foreground"><tr><th class="px-3 py-2">Code</th><th class="px-3 py-2">Type</th><th class="px-3 py-2">Plant Floor</th><th class="px-3 py-2">Capacity</th><th class="px-3 py-2">Rate</th><th class="px-3 py-2">Actions</th></tr></thead><tbody class="divide-y"><?php foreach ($stations as $station): ?><tr><td class="px-3 py-3 font-medium"><?= $manufacturingEscape((string) $station['workstation_code']) ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $station['workstation_type_name']) ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $station['plant_floor_name']) ?></td><td class="px-3 py-3"><?= (int) $station['capacity_units'] ?></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $station['hourly_rate']) ?></td><td class="px-3 py-3"><a class="inline-flex size-8 items-center justify-center rounded-md border" aria-label="Edit workstation" href="?view=manufacturing&amp;section=workstations&amp;workstation=<?= $manufacturingEscape((string) $station['workstation_key']) ?>"><span class="material-symbols-rounded text-base" aria-hidden="true">edit</span></a></td></tr><?php endforeach; ?><?php if ($stations === []): ?><tr><td colspan="6" class="px-3 py-10 text-center text-muted-foreground">No workstations yet.</td></tr><?php endif; ?></tbody></table></div></section>
        <section aria-labelledby="manufacturing-downtime-list"><div><h3 id="manufacturing-downtime-list" class="text-sm font-semibold">Downtime</h3><p class="mt-1 text-xs text-muted-foreground"><?= count($downtimes) ?> persisted entries</p></div><div class="mt-3 divide-y"><?php foreach ($downtimes as $entry): ?><div class="py-3"><div class="flex justify-between gap-3"><p class="text-sm font-medium"><?= $manufacturingEscape((string) $entry['workstation_code']) ?></p><span class="text-xs text-muted-foreground"><?= (int) $entry['duration_minutes'] ?> min</span></div><p class="mt-1 text-xs text-muted-foreground"><?= $manufacturingEscape((string) $entry['starts_at']) ?> · <?= $manufacturingEscape((string) $entry['reason']) ?></p></div><?php endforeach; ?><?php if ($downtimes === []): ?><p class="py-8 text-center text-sm text-muted-foreground">No downtime entries.</p><?php endif; ?></div></section>
    </div>
<?php else: ?>
<div class="grid min-h-[24rem] place-items-center text-center" data-manufacturing-state="<?= $manufacturingEscape((string) ($state['kind'] ?? 'empty')) ?>">
    <div class="max-w-md">
        <span class="material-symbols-rounded text-3xl text-muted-foreground" aria-hidden="true"><?= ($state['kind'] ?? '') === 'dependency' ? 'hourglass_top' : 'precision_manufacturing' ?></span>
        <h2 class="mt-3 text-base font-semibold"><?= $manufacturingEscape((string) ($state['title'] ?? 'Manufacturing')) ?></h2>
        <p class="mt-1 text-sm leading-6 text-muted-foreground"><?= $manufacturingEscape((string) ($state['message'] ?? '')) ?></p>
        <?php if (($state['dependencies'] ?? []) !== []): ?><div class="mt-4 flex justify-center gap-2"><?php foreach ($state['dependencies'] as $dependency): ?><span class="rounded-sm bg-secondary px-2 py-1 text-xs font-medium text-secondary-foreground"><?= $manufacturingEscape((string) $dependency) ?></span><?php endforeach; ?></div><?php endif; ?>
    </div>
</div>
<?php endif; ?>
