<?php
declare(strict_types=1);

$manufacturingEscape = $manufacturingEscape ?? static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
$analysis = is_array($manufacturingData['downtime_analysis'] ?? null) ? $manufacturingData['downtime_analysis'] : ['rows' => [], 'total_downtime_minutes' => 0, 'utilization_percent' => '0.0000'];
?>
<div class="grid gap-6">
    <div><h2 class="text-base font-semibold">Downtime Analysis</h2><p class="mt-1 text-sm text-muted-foreground">Working-calendar utilization from persisted workstation downtime.</p></div>
    <form method="get" data-confirm-submit data-confirm-message="Run Downtime Analysis for this date range?" class="grid gap-3 bg-muted/30 p-3 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="view" value="manufacturing"><input type="hidden" name="section" value="reports"><label class="grid gap-1.5 text-sm"><span>From</span><input class="h-9 rounded-md border bg-background px-3" type="date" name="date_from" required value="<?= $manufacturingEscape((string) ($analysis['date_from'] ?? date('Y-m-01'))) ?>"></label><label class="grid gap-1.5 text-sm"><span>To</span><input class="h-9 rounded-md border bg-background px-3" type="date" name="date_to" required value="<?= $manufacturingEscape((string) ($analysis['date_to'] ?? date('Y-m-d'))) ?>"></label><button type="submit" class="mt-auto inline-flex h-9 items-center justify-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"><span class="material-symbols-rounded text-base" aria-hidden="true">analytics</span>Run</button></form>
    <dl class="grid grid-cols-2 gap-3 bg-muted/30 p-3 text-sm"><div><dt class="text-xs text-muted-foreground">Downtime</dt><dd class="mt-1 text-lg font-semibold"><?= (int) ($analysis['total_downtime_minutes'] ?? 0) ?> min</dd></div><div><dt class="text-xs text-muted-foreground">Utilization</dt><dd class="mt-1 text-lg font-semibold"><?= $manufacturingEscape((string) ($analysis['utilization_percent'] ?? '0.0000')) ?>%</dd></div></dl>
    <div class="overflow-x-auto"><table class="w-full min-w-[38rem] text-sm"><thead class="border-b text-left text-xs text-muted-foreground"><tr><th class="px-3 py-2">Workstation</th><th class="px-3 py-2">Plant Floor</th><th class="px-3 py-2 text-right">Working</th><th class="px-3 py-2 text-right">Downtime</th><th class="px-3 py-2 text-right">Utilization</th></tr></thead><tbody class="divide-y"><?php foreach ($analysis['rows'] ?? [] as $row): ?><tr><td class="px-3 py-3"><span class="font-medium"><?= $manufacturingEscape((string) $row['workstation_code']) ?></span><span class="block text-xs text-muted-foreground"><?= $manufacturingEscape((string) $row['workstation_name']) ?></span></td><td class="px-3 py-3"><?= $manufacturingEscape((string) $row['plant_floor_name']) ?></td><td class="px-3 py-3 text-right"><?= (int) $row['working_minutes'] ?> min</td><td class="px-3 py-3 text-right"><?= (int) $row['downtime_minutes'] ?> min</td><td class="px-3 py-3 text-right"><?= $manufacturingEscape((string) $row['utilization_percent']) ?>%</td></tr><?php endforeach; ?><?php if (($analysis['rows'] ?? []) === []): ?><tr><td colspan="5" class="px-3 py-10 text-center text-muted-foreground">No active workstation calendars in this range.</td></tr><?php endif; ?></tbody></table></div>
</div>
