<?php
$rows = $accountingFinanceData['bankStatementRows'] ?? [];
$banks = $accountingFinanceData['bankAccounts'] ?? [];
$candidateMap = $accountingFinanceData['bankMatchCandidates'] ?? [];
$reconciliations = $accountingFinanceData['bankReconciliations'] ?? [];
?>
<div class="yovel-hr-two-panel grid min-h-0 gap-4 xl:grid-cols-[minmax(0,12fr)_minmax(16rem,8fr)]">
    <section class="yovel-hr-panel flex flex-col rounded-lg border bg-card">
        <header class="yovel-finance-sticky-panel-header flex items-start justify-between gap-3 border-b bg-card px-5 py-4"><div><h3 class="text-base font-semibold">Bank Reconciliation</h3><p class="mt-1 text-sm text-muted-foreground">Match imported bank movement to submitted payments or journals.</p></div><button type="button" data-record-modal-open="finance-bank-import-modal" class="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"><span class="material-symbols-rounded text-base">upload_file</span>Import CSV</button></header>
        <div class="yovel-hr-panel-body overflow-auto"><table class="w-full min-w-[54rem] text-sm"><thead class="yovel-finance-sticky-table-header border-b bg-card text-left text-xs text-muted-foreground"><tr><th class="px-5 py-3">Date</th><th class="px-5 py-3">Reference</th><th class="px-5 py-3">Description</th><th class="px-5 py-3 text-right">Deposit</th><th class="px-5 py-3 text-right">Withdrawal</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Action</th></tr></thead><tbody class="divide-y">
            <?php foreach ($rows as $row): $rowKey = (string) $row['bank_statement_row_key']; ?><tr><td class="px-5 py-3"><?= bx_h($row['transaction_date']) ?></td><td class="px-5 py-3 font-medium"><?= bx_h((string) $row['reference_no']) ?></td><td class="px-5 py-3"><?= bx_h((string) $row['description']) ?></td><td class="px-5 py-3 text-right"><?= number_format((float) $row['deposit'], 2) ?></td><td class="px-5 py-3 text-right"><?= number_format((float) $row['withdrawal'], 2) ?></td><td class="px-5 py-3"><?= bx_h($row['reconciliation_status']) ?></td><td class="px-5 py-3 text-right"><?php if ($row['reconciliation_status'] === 'UNRECONCILED'): ?><button type="button" data-record-modal-open="finance-bank-match-modal" data-finance-bank-match-open="finance-bank-match-modal" data-bank-row-key="<?= bx_h($rowKey) ?>" data-bank-reference="<?= bx_h((string) ($row['reference_no'] ?: $row['description'])) ?>" data-bank-amount="<?= bx_h(bccomp((string) $row['deposit'], '0', 6) === 1 ? $row['deposit'] : $row['withdrawal']) ?>" data-bank-candidates="<?= bx_h(json_encode($candidateMap[$rowKey] ?? [], JSON_UNESCAPED_SLASHES) ?: '[]') ?>" class="inline-flex h-8 items-center gap-1 rounded-md border px-2 text-xs"><span class="material-symbols-rounded text-base">link</span>Match</button><?php endif; ?></td></tr><?php endforeach; ?>
            <?php if (!$rows): ?><tr><td colspan="7" class="px-5 py-10 text-center text-muted-foreground">No bank statement rows imported.</td></tr><?php endif; ?></tbody></table>
            <?php if ($reconciliations): ?><section class="border-t p-5"><h4 class="mb-3 text-sm font-semibold">Reconciliation History</h4><div class="grid divide-y rounded-md border"><?php foreach ($reconciliations as $item): ?><div class="flex items-center justify-between gap-3 p-3 text-sm"><div><span class="font-medium"><?= bx_h($item['reconciliation_date']) ?></span><span class="ml-2 text-muted-foreground">Difference PHP <?= number_format((float) $item['difference_amount'], 2) ?></span></div><div class="flex items-center gap-2"><span class="text-xs"><?= bx_h($item['status']) ?></span><?php if ($item['status'] === 'RECONCILED'): ?><button type="button" data-record-modal-open="finance-unreconcile-modal" data-finance-unreconcile-open="finance-unreconcile-modal" data-reconciliation-key="<?= bx_h($item['reconciliation_key']) ?>" class="inline-flex size-8 items-center justify-center rounded-md border" title="Undo reconciliation" aria-label="Undo reconciliation"><span class="material-symbols-rounded text-base">undo</span></button><?php endif; ?></div></div><?php endforeach; ?></div></section><?php endif; ?>
        </div>
    </section>
    <?php require __DIR__ . '/feature-panel.php'; ?>
</div>

<div id="finance-bank-import-modal" data-record-modal<?= $financeModalStateAttributes("finance-bank-import-modal") ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><section class="flex w-full max-w-2xl flex-col overflow-hidden rounded-lg border bg-card shadow-lg"><header class="yovel-finance-sticky-modal-header flex justify-between border-b bg-card px-5 py-4"><div><h3 class="font-semibold">Import Bank Statement</h3><p class="mt-1 text-sm text-muted-foreground">CSV rows are fingerprinted to prevent duplicates.</p></div><button type="button" data-record-modal-close class="size-8 rounded-md border" aria-label="Close"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" enctype="multipart/form-data" data-confirm-submit class="contents"><div class="grid gap-4 p-5"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="import_finance_bank_statement"><input type="hidden" name="section" value="bank-reconciliation"><label class="grid gap-1.5 text-sm">Bank Account<select class="h-9 rounded-md border bg-background px-3" name="bank_account_key" required><option value="">Select</option><?php foreach ($banks as $bank): ?><option value="<?= bx_h($bank['bank_account_key']) ?>"><?= bx_h($bank['bank_name'] . ' / ' . $bank['account_name']) ?></option><?php endforeach; ?></select></label><label class="grid gap-1.5 text-sm">CSV file<input class="rounded-md border bg-background p-2" type="file" name="statement_file" accept=".csv,text/csv" required></label><p class="text-xs text-muted-foreground">Expected headers: Date, Reference, Description, Deposit, Withdrawal, Balance.</p></div><footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Import</button></footer></form></section></div>

<div id="finance-bank-match-modal" data-record-modal<?= $financeModalStateAttributes("finance-bank-match-modal") ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><section class="flex w-full max-w-xl flex-col overflow-hidden rounded-lg border bg-card shadow-lg"><header class="yovel-finance-sticky-modal-header flex justify-between border-b bg-card px-5 py-4"><div><h3 class="font-semibold">Match Bank Transaction</h3><p class="mt-1 text-sm text-muted-foreground" data-bank-match-reference></p></div><button type="button" data-record-modal-close class="size-8 rounded-md border" aria-label="Close"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" data-confirm-submit data-finance-bank-match-form class="contents"><div class="grid gap-4 p-5"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="reconcile_finance_bank"><input type="hidden" name="section" value="bank-reconciliation"><input type="hidden" name="row_keys_json" data-bank-row-json><input type="hidden" name="matches_json" data-bank-matches-json><label class="grid gap-1.5 text-sm">Submitted source<select class="h-9 rounded-md border bg-background px-3" data-bank-match-source required></select></label><label class="grid gap-1.5 text-sm">Matched amount<input class="h-9 rounded-md border bg-background px-3" type="number" min="0.01" step="0.01" data-bank-match-amount required></label><p class="text-xs text-muted-foreground" data-bank-match-empty hidden>No equal-amount payment or journal candidate was found. Record and submit the accounting document first.</p></div><footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Reconcile</button></footer></form></section></div>

<div id="finance-unreconcile-modal" data-record-modal<?= $financeModalStateAttributes("finance-unreconcile-modal") ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><section class="flex w-full max-w-lg flex-col overflow-hidden rounded-lg border bg-card shadow-lg"><header class="yovel-finance-sticky-modal-header flex justify-between border-b bg-card px-5 py-4"><h3 class="font-semibold">Undo Reconciliation</h3><button type="button" data-record-modal-close class="size-8 rounded-md border" aria-label="Close"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" data-confirm-submit class="contents"><div class="grid gap-4 p-5"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="unreconcile_finance_bank"><input type="hidden" name="section" value="bank-reconciliation"><input type="hidden" name="reconciliation_key" data-unreconciliation-key><label class="grid gap-1.5 text-sm">Reason<textarea class="min-h-24 rounded-md border bg-background p-3" name="reason" required maxlength="500"></textarea></label></div><footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Undo Match</button></footer></form></section></div>
