<?php
/** General Ledger variables are prepared by bootstrap/controller.php. */
$generalLedgerRunningBalance = (float) ($generalLedgerSummary['opening_balance'] ?? 0);
$generalLedgerVisibleAccounts = array_values(array_filter($accountingAccounts, static fn (array $account): bool => (int) ($account['is_group'] ?? 0) !== 1));
$generalLedgerTransactions = $accountingFinanceData['ledgerTransactions'] ?? [];
$ledgerHealthMonitors = $accountingFinanceData['ledgerHealthMonitors'] ?? [];
$ledgerRepairs = $accountingFinanceData['ledgerRepairs'] ?? ['merges'=>[],'reposts'=>[],'health_runs'=>[]];
$latestLedgerHealth = $ledgerRepairs['health_runs'][0] ?? null;
?>
<div class="yovel-general-ledger yovel-hr-two-panel grid min-h-0 gap-4 xl:grid-cols-[minmax(0,12fr)_minmax(16rem,8fr)]">
    <section class="yovel-hr-panel flex flex-col rounded-lg border bg-card">
        <header class="yovel-finance-sticky-panel-header border-b bg-card px-5 py-4">
            <div class="flex flex-wrap items-start justify-between gap-3">
                <div><h2 class="text-base font-semibold">General Ledger</h2><p class="mt-1 text-sm leading-6 text-muted-foreground">Committed debit and credit postings with source voucher traceability.</p></div>
                <div class="flex gap-2"><button type="button" data-record-modal-open="finance-ledger-health-modal" class="inline-flex size-9 items-center justify-center rounded-md border bg-background hover:bg-muted" aria-label="Run ledger health" title="Ledger health"><span class="material-symbols-rounded text-base" aria-hidden="true">health_and_safety</span></button><button type="button" class="inline-flex size-9 items-center justify-center rounded-md border bg-background hover:bg-muted" aria-label="Export General Ledger" title="Export CSV" data-general-ledger-export><span class="material-symbols-rounded text-base" aria-hidden="true">download</span></button></div>
            </div>
        </header>
        <div class="yovel-hr-panel-body grid content-start gap-4 p-5">
            <div class="yovel-finance-dashboard-metrics grid gap-2">
                <?php foreach ([
                    ['label' => 'Opening balance', 'value' => $generalLedgerSummary['opening_balance'] ?? '0'],
                    ['label' => 'Period debit', 'value' => $generalLedgerSummary['period_debit'] ?? '0'],
                    ['label' => 'Period credit', 'value' => $generalLedgerSummary['period_credit'] ?? '0'],
                    ['label' => 'Closing balance', 'value' => $generalLedgerSummary['closing_balance'] ?? '0'],
                    ['label' => 'Entries', 'value' => (string) ($generalLedgerSummary['entry_count'] ?? 0), 'count' => true],
                ] as $metric): ?>
                    <div class="rounded-md border bg-background px-3 py-3"><p class="text-xs text-muted-foreground"><?= bx_h((string) $metric['label']) ?></p><p class="mt-1 truncate text-base font-semibold"><?= !empty($metric['count']) ? (int) $metric['value'] : bx_h(number_format((float) $metric['value'], 2, '.', ',')) ?></p></div>
                <?php endforeach; ?>
            </div>
            <div class="yovel-general-ledger-table overflow-auto rounded-md border" data-general-ledger-table>
                <table class="w-full table-fixed text-left text-sm" style="min-width: 2020px">
                    <thead class="yovel-finance-sticky-table-header border-b bg-card text-xs text-muted-foreground">
                        <tr>
                            <?php foreach ([['Posting date',110],['Account',220],['Debit',130],['Credit',130],['Foreign amount',150],['Currency / rate',150],['Running balance',150],['Voucher type',150],['Voucher no.',170],['Party',180],['Cost center',150],['Project',150],['Finance book',150],['Remarks',240]] as $column): ?><th scope="col" class="px-3 py-3 font-medium" style="width: <?= (int) $column[1] ?>px"><?= bx_h((string) $column[0]) ?></th><?php endforeach; ?>
                        </tr>
                    </thead>
                    <tbody class="divide-y" data-general-ledger-body>
                        <?php foreach ($generalLedgerEntries as $entry): ?>
                            <?php $generalLedgerRunningBalance += (float) $entry['debit'] - (float) $entry['credit']; ?>
                            <tr data-general-ledger-row>
                                <td class="px-3 py-3 text-xs" data-ledger-value="<?= bx_h((string) $entry['posting_date']) ?>"><?= bx_h((string) $entry['posting_date']) ?></td>
                                <td class="px-3 py-3"><span class="block truncate text-sm font-medium"><?= bx_h((string) $entry['account_name']) ?></span><span class="block truncate text-xs text-muted-foreground"><?= bx_h((string) $entry['account_code']) ?></span></td>
                                <td class="px-3 py-3 text-right font-mono text-xs" data-ledger-value="<?= bx_h((string) $entry['debit']) ?>"><?= number_format((float) $entry['debit'], 2, '.', ',') ?></td>
                                <td class="px-3 py-3 text-right font-mono text-xs" data-ledger-value="<?= bx_h((string) $entry['credit']) ?>"><?= number_format((float) $entry['credit'], 2, '.', ',') ?></td>
                                <td class="px-3 py-3 text-right font-mono text-xs"><?= number_format((float)(((float)($entry['transaction_debit']??0)>0||(float)($entry['transaction_credit']??0)>0)?((float)($entry['transaction_debit']??0)>0?$entry['transaction_debit']:$entry['transaction_credit']):(((float)$entry['debit']>0?$entry['debit']:$entry['credit'])/max(0.00000001,(float)($entry['exchange_rate']??1)))),2,'.',',') ?></td>
                                <td class="px-3 py-3 text-xs"><?= bx_h((string)(($entry['transaction_currency']??'')?:'PHP')) ?> / <?= bx_h(number_format((float)($entry['exchange_rate']??1),4,'.',',')) ?></td>
                                <td class="px-3 py-3 text-right font-mono text-xs" data-ledger-value="<?= bx_h(number_format($generalLedgerRunningBalance, 6, '.', '')) ?>"><?= number_format($generalLedgerRunningBalance, 2, '.', ',') ?></td>
                                <td class="px-3 py-3 text-xs"><?= bx_h(str_replace('_', ' ', (string) $entry['voucher_type'])) ?><?= (int) ($entry['is_reversal'] ?? 0) === 1 ? ' · Reversal' : '' ?></td>
                                <td class="px-3 py-3 text-xs font-medium"><?= bx_h((string) $entry['voucher_no']) ?></td>
                                <td class="px-3 py-3 text-xs"><?= bx_h((string) (($entry['party'] ?? '') ?: '—')) ?></td>
                                <td class="px-3 py-3 text-xs"><?= bx_h((string) (($entry['cost_center'] ?? '') ?: '—')) ?></td>
                                <td class="px-3 py-3 text-xs"><?= bx_h((string) (($entry['project'] ?? '') ?: '—')) ?></td>
                                <td class="px-3 py-3 text-xs"><?= bx_h((string) (($entry['finance_book'] ?? '') ?: '—')) ?></td>
                                <td class="px-3 py-3 text-xs text-muted-foreground"><?= bx_h((string) (($entry['entry_remarks'] ?? '') ?: '—')) ?></td>
                            </tr>
                        <?php endforeach; ?>
                        <?php if (!$generalLedgerEntries): ?><tr><td class="px-5 py-10 text-center text-sm text-muted-foreground" colspan="14">No committed accounting postings exist for the selected filters.</td></tr><?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <aside class="yovel-hr-panel flex flex-col rounded-lg border bg-card">
        <header class="yovel-finance-sticky-panel-header border-b bg-card px-5 py-4"><h2 class="text-base font-semibold">Ledger Controls</h2><p class="mt-1 text-sm leading-6 text-muted-foreground">Diagnose or append controlled repairs, then filter the immutable history.</p></header>
        <div class="yovel-hr-panel-body p-5">
            <div class="mb-5 grid gap-2"><div class="rounded-md border bg-background p-3"><div class="flex items-center justify-between gap-3"><span class="text-xs text-muted-foreground">Latest health</span><span class="text-xs font-medium"><?= bx_h((string)($latestLedgerHealth['health_status']??'NOT RUN')) ?></span></div><p class="mt-1 text-sm"><?= $latestLedgerHealth ? (int)$latestLedgerHealth['finding_count'].' finding(s) across '.(int)$latestLedgerHealth['checked_transactions'].' transactions' : 'No persisted scan yet' ?></p></div><button type="button" data-record-modal-open="finance-ledger-health-modal" class="inline-flex h-9 items-center justify-center gap-2 rounded-md border bg-background px-3 text-sm font-medium"><span class="material-symbols-rounded text-base">health_and_safety</span>Health Scan</button><div class="grid grid-cols-2 gap-2"><button type="button" data-record-modal-open="finance-ledger-merge-modal" class="inline-flex h-9 items-center justify-center gap-2 rounded-md border bg-background px-3 text-sm font-medium"><span class="material-symbols-rounded text-base">merge</span>Merge</button><button type="button" data-record-modal-open="finance-ledger-repost-modal" class="inline-flex h-9 items-center justify-center gap-2 rounded-md border bg-background px-3 text-sm font-medium"><span class="material-symbols-rounded text-base">published_with_changes</span>Repost</button></div></div>
            <form method="get" class="grid gap-3">
                <input type="hidden" name="view" value="accounting-finance"><input type="hidden" name="section" value="general-ledger">
                <div class="grid grid-cols-2 gap-2"><div class="grid gap-1.5"><label class="text-xs font-medium" for="gl_date_from">From</label><input class="h-9 rounded-md border bg-background px-3 text-sm" id="gl_date_from" name="date_from" type="date" value="<?= bx_h((string) $generalLedgerFilters['date_from']) ?>"></div><div class="grid gap-1.5"><label class="text-xs font-medium" for="gl_date_to">To</label><input class="h-9 rounded-md border bg-background px-3 text-sm" id="gl_date_to" name="date_to" type="date" value="<?= bx_h((string) $generalLedgerFilters['date_to']) ?>"></div></div>
                <div class="grid gap-1.5"><label class="text-xs font-medium" for="gl_account">Account</label><select class="h-9 rounded-md border bg-background px-3 text-sm" id="gl_account" name="account_key"><option value="">All ledger accounts</option><?php foreach ($generalLedgerVisibleAccounts as $account): ?><option value="<?= bx_h((string) $account['account_key']) ?>" <?= (string) $generalLedgerFilters['account_key'] === (string) $account['account_key'] ? 'selected' : '' ?>><?= bx_h((string) $account['account_code']) ?> · <?= bx_h((string) $account['account_name']) ?></option><?php endforeach; ?></select></div>
                <div class="grid gap-1.5"><label class="text-xs font-medium" for="gl_voucher_type">Voucher type</label><select class="h-9 rounded-md border bg-background px-3 text-sm" id="gl_voucher_type" name="voucher_type"><option value="">All voucher types</option><?php foreach (['JOURNAL_ENTRY','SALES_INVOICE','PURCHASE_INVOICE','PAYMENT_ENTRY','REVERSAL'] as $type): ?><option value="<?= bx_h($type) ?>" <?= (string) $generalLedgerFilters['voucher_type'] === $type ? 'selected' : '' ?>><?= bx_h(str_replace('_', ' ', $type)) ?></option><?php endforeach; ?></select></div>
                <?php foreach ([['voucher_no','Voucher number'],['party','Party'],['cost_center','Cost center'],['project','Project'],['finance_book','Finance book']] as $filter): ?><div class="grid gap-1.5"><label class="text-xs font-medium" for="gl_<?= bx_h($filter[0]) ?>"><?= bx_h($filter[1]) ?></label><input class="h-9 rounded-md border bg-background px-3 text-sm" id="gl_<?= bx_h($filter[0]) ?>" name="<?= bx_h($filter[0]) ?>" maxlength="180" value="<?= bx_h((string) $generalLedgerFilters[$filter[0]]) ?>"></div><?php endforeach; ?>
                <input type="hidden" name="include_reversals" value="0"><label class="inline-flex items-center gap-2 py-1 text-sm"><input type="checkbox" name="include_reversals" value="1" <?= !empty($generalLedgerFilters['include_reversals']) ? 'checked' : '' ?>>Include reversal entries</label>
                <div class="grid grid-cols-2 gap-2 border-t pt-4"><button type="submit" class="inline-flex h-9 items-center justify-center rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground hover:bg-primary/90">Apply</button><a class="inline-flex h-9 items-center justify-center rounded-md border bg-background px-3 text-sm font-medium hover:bg-muted" href="./?view=accounting-finance&amp;section=general-ledger">Reset</a></div>
            </form>
        </div>
    </aside>
</div>

<div id="finance-ledger-health-modal" data-record-modal<?= $financeModalStateAttributes('finance-ledger-health-modal') ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="finance-ledger-health-title"><section class="w-full max-w-xl overflow-hidden rounded-lg border bg-card shadow-lg"><header class="yovel-finance-sticky-modal-header flex justify-between border-b bg-card px-5 py-4"><div><h3 id="finance-ledger-health-title" class="font-semibold">Ledger Health</h3><p class="mt-1 text-sm text-muted-foreground">Check balances, totals, entry shapes, and orphaned rows.</p></div><button type="button" data-record-modal-close class="size-8 rounded-md border" aria-label="Close"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" data-confirm-submit><div class="grid gap-4 p-5"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="save_finance_journal"><input type="hidden" name="journal_operation" value="ledger_health" data-ledger-health-operation><input type="hidden" name="section" value="general-ledger"><div class="inline-flex rounded-md border p-1" role="group" aria-label="Ledger health mode"><button type="button" class="h-8 flex-1 rounded px-3 text-sm bg-muted" data-ledger-health-mode="scan">Run scan</button><button type="button" class="h-8 flex-1 rounded px-3 text-sm" data-ledger-health-mode="monitor">New monitor</button></div><div data-ledger-health-scan><label class="grid gap-1.5 text-sm">Monitor<select class="h-9 rounded-md border bg-background px-3" name="monitor_key"><option value="">Manual scan</option><?php foreach($ledgerHealthMonitors as $monitor):if(!(int)$monitor['enabled'])continue;?><option value="<?= bx_h($monitor['ledger_health_monitor_key']) ?>"><?= bx_h($monitor['monitor_name']) ?></option><?php endforeach;?></select></label></div><div hidden class="grid gap-4 sm:grid-cols-2" data-ledger-health-monitor><label class="grid gap-1.5 text-sm sm:col-span-2">Monitor name<input class="h-9 rounded-md border bg-background px-3" name="monitor_name"></label><label class="grid gap-1.5 text-sm">Schedule<select class="h-9 rounded-md border bg-background px-3" name="schedule"><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option><option>MANUAL</option></select></label><label class="inline-flex items-center gap-2 self-end py-2 text-sm"><input type="checkbox" name="enabled" value="1" checked>Enabled</label></div></div><footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground" data-ledger-health-submit>Run Scan</button></footer></form></section></div>

<div id="finance-ledger-merge-modal" data-record-modal<?= $financeModalStateAttributes('finance-ledger-merge-modal') ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="finance-ledger-merge-title"><section class="w-full max-w-xl overflow-hidden rounded-lg border bg-card shadow-lg"><header class="yovel-finance-sticky-modal-header flex justify-between border-b bg-card px-5 py-4"><div><h3 id="finance-ledger-merge-title" class="font-semibold">Merge Ledger Balance</h3><p class="mt-1 text-sm text-muted-foreground">Append a balanced transfer while retaining every historical row.</p></div><button type="button" data-record-modal-close class="size-8 rounded-md border" aria-label="Close"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" data-confirm-submit><div class="grid gap-4 p-5"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="save_finance_journal"><input type="hidden" name="journal_operation" value="ledger_merge"><input type="hidden" name="section" value="general-ledger"><div class="grid gap-4 sm:grid-cols-2"><?php foreach([['source_account_key','Source account'],['target_account_key','Target account']] as [$name,$label]):?><label class="grid gap-1.5 text-sm"><?= $label ?><select class="h-9 rounded-md border bg-background px-3" name="<?= $name ?>" required><option value="">Select</option><?php foreach($generalLedgerVisibleAccounts as $account):if($account['account_status']!=='ACTIVE'||(int)($account['freeze_account']??0)===1)continue;?><option value="<?= bx_h($account['account_key']) ?>"><?= bx_h($account['account_code'].' / '.$account['account_name']) ?></option><?php endforeach;?></select></label><?php endforeach;?></div><label class="grid gap-1.5 text-sm">Posting date<input class="h-9 rounded-md border bg-background px-3" type="date" name="posting_date" value="<?= date('Y-m-d') ?>" required></label><label class="grid gap-1.5 text-sm">Reason<textarea class="min-h-24 rounded-md border bg-background p-3" name="reason" required></textarea></label></div><footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Confirm Merge</button></footer></form></section></div>

<div id="finance-ledger-repost-modal" data-record-modal<?= $financeModalStateAttributes('finance-ledger-repost-modal') ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="finance-ledger-repost-title"><section class="w-full max-w-xl overflow-hidden rounded-lg border bg-card shadow-lg"><header class="yovel-finance-sticky-modal-header flex justify-between border-b bg-card px-5 py-4"><div><h3 id="finance-ledger-repost-title" class="font-semibold">Repost Ledger Transaction</h3><p class="mt-1 text-sm text-muted-foreground">Append an opposite reversal and a linked replacement.</p></div><button type="button" data-record-modal-close class="size-8 rounded-md border" aria-label="Close"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" data-confirm-submit><div class="grid gap-4 p-5"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="save_finance_journal"><input type="hidden" name="journal_operation" value="ledger_repost"><input type="hidden" name="section" value="general-ledger"><label class="grid gap-1.5 text-sm">Transaction<select class="h-9 rounded-md border bg-background px-3" name="transaction_key" required><option value="">Select</option><?php foreach($generalLedgerTransactions as $transaction):if(!empty($transaction['reversal_of_transaction_key'])||!empty($transaction['repost_of_transaction_key']))continue;?><option value="<?= bx_h($transaction['transaction_key']) ?>"><?= bx_h($transaction['posting_date'].' / '.$transaction['voucher_type'].' / '.$transaction['voucher_no']) ?></option><?php endforeach;?></select></label><label class="grid gap-1.5 text-sm">Posting date<input class="h-9 rounded-md border bg-background px-3" type="date" name="posting_date" value="<?= date('Y-m-d') ?>" required></label><label class="grid gap-1.5 text-sm">Reason<textarea class="min-h-24 rounded-md border bg-background p-3" name="reason" required></textarea></label></div><footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Confirm Repost</button></footer></form></section></div>
<script>
(()=>{const modal=document.getElementById('finance-ledger-health-modal');if(!modal)return;modal.querySelectorAll('[data-ledger-health-mode]').forEach(button=>button.addEventListener('click',()=>{const monitor=button.dataset.ledgerHealthMode==='monitor';modal.querySelector('[data-ledger-health-operation]').value=monitor?'ledger_health_monitor':'ledger_health';modal.querySelector('[data-ledger-health-scan]').hidden=monitor;modal.querySelector('[data-ledger-health-monitor]').hidden=!monitor;modal.querySelector('[name="monitor_name"]').required=monitor;modal.querySelector('[data-ledger-health-submit]').textContent=monitor?'Save Monitor':'Run Scan';modal.querySelectorAll('[data-ledger-health-mode]').forEach(item=>item.classList.toggle('bg-muted',item===button));}));})();
</script>
