<?php
$isSales = $activeAccountingFinanceSection === 'sales-invoices';
$type = $isSales ? 'SALES' : 'PURCHASE';
$rows = $accountingFinanceData[$isSales ? 'salesInvoices' : 'purchaseInvoices'] ?? [];
$parties = $accountingFinanceData[$isSales ? 'customers' : 'suppliers'] ?? [];
$partyKeyField = $isSales ? 'customer_key' : 'supplier_key';
$partyNameField = $isSales ? 'customer_name' : 'supplier_name';
$submitted = array_filter($rows, static fn (array $row): bool => (string) $row['document_status'] === 'SUBMITTED');
?>
<div class="yovel-hr-two-panel grid min-h-0 gap-4 xl:grid-cols-[minmax(0,12fr)_minmax(16rem,8fr)]">
    <section class="yovel-hr-panel flex flex-col rounded-lg border bg-card">
        <header class="yovel-finance-sticky-panel-header flex items-start justify-between gap-3 border-b bg-card px-5 py-4">
            <div><h3 class="text-base font-semibold"><?= $isSales ? 'Sales Invoices & Receivables' : 'Purchase Invoices & Payables' ?></h3><p class="mt-1 text-sm text-muted-foreground"><?= bx_h($activeAccountingFinanceMeta['description']) ?></p></div>
            <div class="flex gap-2"><?php if (!$isSales): ?><button type="button" data-record-modal-open="finance-supplier-modal" class="inline-flex h-9 items-center gap-2 rounded-md border px-3 text-sm font-medium"><span class="material-symbols-rounded text-base">person_add</span>Supplier</button><?php endif; ?><button type="button" data-record-modal-open="finance-invoice-modal" class="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"><span class="material-symbols-rounded text-base">add</span>New Invoice</button></div>
        </header>
        <div class="grid grid-cols-3 gap-3 border-b p-4">
            <?php foreach ([['Invoices', count($rows)], ['Submitted', count($submitted)], ['Outstanding', 'PHP ' . number_format(array_sum(array_map(static fn (array $row): float => (float) $row['outstanding_amount'], $submitted)), 2)]] as [$label, $value]): ?>
                <div class="bg-muted/40 p-3"><p class="text-xs text-muted-foreground"><?= bx_h((string) $label) ?></p><p class="mt-1 text-xl font-semibold"><?= bx_h((string) $value) ?></p></div>
            <?php endforeach; ?>
        </div>
        <div class="yovel-hr-panel-body overflow-auto">
            <table class="w-full min-w-[64rem] text-left text-sm">
                <thead class="yovel-finance-sticky-table-header border-b bg-card text-xs text-muted-foreground"><tr><th class="px-5 py-3">Invoice</th><th class="px-5 py-3">Party</th><th class="px-5 py-3">Posting</th><th class="px-5 py-3">Due</th><th class="px-5 py-3 text-right">Total</th><th class="px-5 py-3 text-right">Outstanding</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">GL</th><th class="px-5 py-3 text-right">Actions</th></tr></thead>
                <tbody class="divide-y">
                    <?php foreach ($rows as $row): ?>
                        <tr><td class="px-5 py-3 font-medium"><?= bx_h($row['invoice_no']) ?><?= !empty($row['is_return']) ? ' / Return' : '' ?></td><td class="px-5 py-3"><?= bx_h($row['party_name']) ?></td><td class="px-5 py-3"><?= bx_h($row['posting_date']) ?></td><td class="px-5 py-3"><?= bx_h($row['due_date']) ?></td><td class="px-5 py-3 text-right"><?= number_format((float) $row['grand_total'], 2) ?></td><td class="px-5 py-3 text-right"><?= number_format((float) $row['outstanding_amount'], 2) ?></td><td class="px-5 py-3"><?= bx_h($row['document_status']) ?></td><td class="px-5 py-3"><?php if ($row['gl_transaction_key']): ?><a class="text-primary hover:underline" href="./?view=accounting-finance&amp;section=general-ledger&amp;voucher_no=<?= rawurlencode($row['invoice_no']) ?>">Open</a><?php else: ?>-<?php endif; ?></td>
                            <td class="px-5 py-3"><div class="flex justify-end gap-1"><?php if ($row['document_status'] === 'DRAFT'): ?><button type="button" data-record-modal-open="finance-invoice-lifecycle" data-finance-lifecycle-open="finance-invoice-lifecycle" data-lifecycle-mode="submit" data-lifecycle-action="submit_finance_invoice" data-lifecycle-key="<?= bx_h($row['invoice_key']) ?>" data-lifecycle-number="<?= bx_h($row['invoice_no']) ?>" class="inline-flex size-8 items-center justify-center rounded-md border" title="Submit invoice" aria-label="Submit invoice"><span class="material-symbols-rounded text-base">task_alt</span></button><?php elseif ($row['document_status'] === 'SUBMITTED' && bccomp((string) $row['outstanding_amount'], (string) $row['grand_total'], 6) === 0): ?><button type="button" data-record-modal-open="finance-invoice-lifecycle" data-finance-lifecycle-open="finance-invoice-lifecycle" data-lifecycle-mode="cancel" data-lifecycle-action="cancel_finance_invoice" data-lifecycle-key="<?= bx_h($row['invoice_key']) ?>" data-lifecycle-number="<?= bx_h($row['invoice_no']) ?>" class="inline-flex size-8 items-center justify-center rounded-md border" title="Cancel invoice" aria-label="Cancel invoice"><span class="material-symbols-rounded text-base">undo</span></button><?php endif; ?></div></td></tr>
                    <?php endforeach; ?>
                    <?php if (!$rows): ?><tr><td colspan="9" class="px-5 py-10 text-center text-muted-foreground">No invoices yet.</td></tr><?php endif; ?>
                </tbody>
            </table>
        </div>
    </section>
    <?php require __DIR__ . '/feature-panel.php'; ?>
</div>

<div id="finance-invoice-modal" data-record-modal<?= $financeModalStateAttributes("finance-invoice-modal") ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="finance-invoice-title">
    <section class="flex max-h-[calc(100dvh-2rem)] w-full max-w-6xl flex-col overflow-hidden rounded-lg border bg-card shadow-lg">
        <header class="yovel-finance-sticky-modal-header flex items-start justify-between border-b bg-card px-5 py-4"><div><h3 id="finance-invoice-title" class="font-semibold">New <?= $isSales ? 'Sales' : 'Purchase' ?> Invoice</h3><p class="mt-1 text-sm text-muted-foreground">Totals and Philippine VAT are recalculated by the server.</p></div><button type="button" data-record-modal-close class="inline-flex size-8 items-center justify-center rounded-md border" aria-label="Close"><span class="material-symbols-rounded text-base">close</span></button></header>
        <form method="post" data-confirm-submit data-finance-lines-form class="contents">
            <div class="yovel-modal-scroll grid gap-5 overflow-y-auto p-5">
                <input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="save_finance_invoice"><input type="hidden" name="section" value="<?= bx_h($activeAccountingFinanceSection) ?>"><input type="hidden" name="document_type" value="<?= $type ?>"><input type="hidden" name="lines_json" data-finance-lines-json>
                <div class="grid gap-4 md:grid-cols-4"><label class="grid gap-1.5 text-sm">Invoice no.<input class="h-9 rounded-md border bg-background px-3" name="invoice_no" placeholder="Automatic"></label><label class="grid gap-1.5 text-sm"><?= $isSales ? 'Customer' : 'Supplier' ?><select class="h-9 rounded-md border bg-background px-3" name="party_key" required><option value="">Select</option><?php foreach ($parties as $party): ?><option value="<?= bx_h($party[$partyKeyField]) ?>"><?= bx_h($party[$partyNameField]) ?></option><?php endforeach; ?></select></label><label class="grid gap-1.5 text-sm">Posting date<input class="h-9 rounded-md border bg-background px-3" type="date" name="posting_date" value="<?= date('Y-m-d') ?>" required></label><label class="grid gap-1.5 text-sm">Due date<input class="h-9 rounded-md border bg-background px-3" type="date" name="due_date" value="<?= date('Y-m-d') ?>" required></label><?php if (!$isSales): ?><label class="grid gap-1.5 text-sm">Supplier reference<input class="h-9 rounded-md border bg-background px-3" name="supplier_reference" required></label><?php endif; ?></div>
                <div class="overflow-auto border"><table class="w-full min-w-[58rem] text-sm"><thead class="border-b bg-muted/40"><tr><th class="p-3 text-left">Description</th><th class="p-3">Qty</th><th class="p-3">Rate</th><th class="p-3">Account</th><th class="p-3">Tax Code</th><th class="p-3">Inclusive</th><th class="w-10"></th></tr></thead><tbody data-finance-lines-body><tr data-finance-line><td class="p-2"><input class="h-9 w-full rounded-md border bg-background px-3" data-line-field="description" required></td><td class="p-2"><input class="h-9 w-24 rounded-md border bg-background px-3" type="number" step="0.000001" value="1" data-line-field="quantity" required></td><td class="p-2"><input class="h-9 w-32 rounded-md border bg-background px-3" type="number" step="0.01" min="0" data-line-field="unit_amount" required></td><td class="p-2"><select class="h-9 w-52 rounded-md border bg-background px-3" data-line-field="account_key" required><option value="">Select</option><?php foreach ($accountingAccounts as $account): if ($account['is_group'] || $account['account_status'] !== 'ACTIVE' || !in_array($account['root_type'], $isSales ? ['INCOME'] : ['EXPENSE', 'ASSET'], true)) continue; ?><option value="<?= bx_h($account['account_key']) ?>"><?= bx_h($account['account_code'] . ' / ' . $account['account_name']) ?></option><?php endforeach; ?></select></td><td class="p-2"><select class="h-9 w-48 rounded-md border bg-background px-3" data-line-field="tax_code"><?php foreach ($isSales ? ['VAT12', 'ZERO_RATED', 'EXEMPT', 'OUT_OF_SCOPE', 'GOV_VAT12'] : ['INPUT_SERVICE_VAT12', 'INPUT_GOODS_VAT12', 'INPUT_CAPITAL_VAT12', 'EXEMPT', 'OUT_OF_SCOPE'] as $tax): ?><option><?= bx_h($tax) ?></option><?php endforeach; ?></select></td><td class="p-2 text-center"><input type="checkbox" data-line-field="price_inclusive"></td><td class="p-2"><button type="button" data-finance-line-remove class="inline-flex size-8 items-center justify-center rounded-md border" aria-label="Remove line"><span class="material-symbols-rounded text-base">delete</span></button></td></tr></tbody></table></div>
                <button type="button" data-finance-line-add class="inline-flex h-9 w-fit items-center gap-2 rounded-md border px-3 text-sm"><span class="material-symbols-rounded text-base">add</span>Add line</button>
            </div>
            <footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button type="submit" class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Save Draft</button></footer>
        </form>
    </section>
</div>
<?php if (!$isSales): ?>
<div id="finance-supplier-modal" data-record-modal<?= $financeModalStateAttributes("finance-supplier-modal") ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><section class="flex w-full max-w-2xl flex-col overflow-hidden rounded-lg border bg-card shadow-lg"><header class="yovel-finance-sticky-modal-header flex justify-between border-b bg-card px-5 py-4"><div><h3 class="font-semibold">New Supplier</h3><p class="mt-1 text-sm text-muted-foreground">Create the payable party before recording its invoice.</p></div><button type="button" data-record-modal-close class="size-8 rounded-md border" aria-label="Close"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" data-confirm-submit class="contents"><div class="grid gap-4 p-5"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="save_finance_supplier"><input type="hidden" name="section" value="purchase-invoices"><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm">Supplier code<input class="h-9 rounded-md border bg-background px-3" name="supplier_code" required></label><label class="grid gap-1.5 text-sm">Supplier name<input class="h-9 rounded-md border bg-background px-3" name="supplier_name" required></label><label class="grid gap-1.5 text-sm">TIN<input class="h-9 rounded-md border bg-background px-3" name="supplier_tin" placeholder="000-000-000-00000"></label><label class="grid gap-1.5 text-sm sm:col-span-2">Address<textarea class="min-h-24 rounded-md border bg-background p-3" name="supplier_address" maxlength="500"></textarea></label></div></div><footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Save Supplier</button></footer></form></section></div>
<?php endif; ?>
<?php $financeLifecycle = ['modal_id' => 'finance-invoice-lifecycle', 'section' => $activeAccountingFinanceSection, 'key_name' => 'invoice_key', 'document_type' => $type]; require __DIR__ . '/lifecycle-modal.php'; ?>
