<?php
$typeMap=['cost-centers'=>['cost-center','costCenters','cost_center_key','cost_center_code','cost_center_name'],'accounting-dimensions'=>['accounting-dimension','accountingDimensions','dimension_key','dimension_code','dimension_name'],'bank-accounts'=>['bank-account','bankAccounts','bank_account_key','bank_account_code','account_name']];
[$masterType,$dataKey,$keyField,$codeField,$nameField]=$typeMap[$activeAccountingFinanceSection];
$rows=$accountingFinanceData[$dataKey]??[];
?>
<div class="yovel-hr-two-panel grid min-h-0 gap-4 xl:grid-cols-[minmax(0,12fr)_minmax(16rem,8fr)]">
<section class="yovel-hr-panel flex flex-col rounded-lg border bg-card">
<header class="yovel-finance-sticky-panel-header flex items-start justify-between gap-3 border-b bg-card px-5 py-4"><div><h3 class="text-base font-semibold"><?= bx_h($activeAccountingFinanceMeta['label']) ?></h3><p class="mt-1 text-sm text-muted-foreground"><?= bx_h($activeAccountingFinanceMeta['description']) ?></p></div><button type="button" data-record-modal-open="finance-master-modal" class="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"><span class="material-symbols-rounded text-base">add</span>New</button></header>
<div class="yovel-hr-panel-body overflow-auto"><table class="w-full min-w-[42rem] text-left text-sm"><thead class="yovel-finance-sticky-table-header border-b bg-card text-xs text-muted-foreground"><tr><th class="px-5 py-3">Code</th><th class="px-5 py-3">Name</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Details</th></tr></thead><tbody class="divide-y"><?php foreach($rows as $row): ?><tr><td class="px-5 py-3 font-medium"><?= bx_h((string)$row[$codeField]) ?></td><td class="px-5 py-3"><?= bx_h((string)$row[$nameField]) ?></td><td class="px-5 py-3"><?= bx_h((string)($row['status']??'')) ?></td><td class="px-5 py-3 text-muted-foreground"><?php if($masterType==='cost-center'): ?><?= !empty($row['is_group'])?'Group':'Posting' ?><?php elseif($masterType==='accounting-dimension'): ?><?= count($row['values']??[]) ?> values<?php else: ?><?= bx_h((string)($row['bank_name']??'')) ?> · <?= bx_h((string)($row['currency']??'')) ?><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="4" class="px-5 py-10 text-center text-muted-foreground">No records yet.</td></tr><?php endif; ?></tbody></table></div>
</section><?php require __DIR__.'/feature-panel.php'; ?>
</div>
<div id="finance-master-modal" data-record-modal<?= $financeModalStateAttributes("finance-master-modal") ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="finance-master-title"><section class="flex max-h-[calc(100dvh-2rem)] w-full max-w-3xl flex-col overflow-hidden rounded-lg border bg-card shadow-lg"><header class="yovel-finance-sticky-modal-header flex items-start justify-between border-b bg-card px-5 py-4"><div><h3 id="finance-master-title" class="font-semibold">New <?= bx_h($activeAccountingFinanceMeta['label']) ?></h3><p class="mt-1 text-sm text-muted-foreground">Save a company-scoped Finance master.</p></div><button type="button" data-record-modal-close class="inline-flex size-8 items-center justify-center rounded-md border"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" data-confirm-submit class="contents"><div class="yovel-modal-scroll grid gap-4 overflow-y-auto p-5"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="save_finance_master"><input type="hidden" name="section" value="<?= bx_h($activeAccountingFinanceSection) ?>"><input type="hidden" name="master_type" value="<?= bx_h($masterType) ?>">
<?php if($masterType==='cost-center'): ?><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm">Code<input class="h-9 rounded-md border bg-background px-3" name="cost_center_code" required></label><label class="grid gap-1.5 text-sm">Name<input class="h-9 rounded-md border bg-background px-3" name="cost_center_name" required></label><label class="grid gap-1.5 text-sm">Parent<select class="h-9 rounded-md border bg-background px-3" name="parent_cost_center_key"><option value="">None</option><?php foreach($rows as $row):if(empty($row['is_group']))continue;?><option value="<?= bx_h($row['cost_center_key']) ?>"><?= bx_h($row['cost_center_name']) ?></option><?php endforeach;?></select></label><label class="inline-flex items-center gap-2 text-sm"><input type="checkbox" name="is_group" value="1">Group Cost Center</label></div>
<?php elseif($masterType==='accounting-dimension'): ?><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm">Code<input class="h-9 rounded-md border bg-background px-3" name="dimension_code" required></label><label class="grid gap-1.5 text-sm">Name<input class="h-9 rounded-md border bg-background px-3" name="dimension_name" required></label><label class="grid gap-1.5 text-sm">Reference type<select class="h-9 rounded-md border bg-background px-3" name="reference_type"><option>CUSTOM</option><option>PROJECT</option><option>BRANCH</option><option>DEPARTMENT</option></select></label><label class="inline-flex items-center gap-2 text-sm"><input type="checkbox" name="mandatory_for_profit_loss" value="1">Required on Profit/Loss</label></div><div class="grid gap-2"><p class="text-sm font-medium">First value</p><div class="grid gap-3 sm:grid-cols-2"><input class="h-9 rounded-md border bg-background px-3" name="values[0][value_code]" placeholder="Value code" required><input class="h-9 rounded-md border bg-background px-3" name="values[0][value_name]" placeholder="Value name" required></div></div>
<?php else: ?><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm">Code<input class="h-9 rounded-md border bg-background px-3" name="bank_account_code" required></label><label class="grid gap-1.5 text-sm">Bank name<input class="h-9 rounded-md border bg-background px-3" name="bank_name" required></label><label class="grid gap-1.5 text-sm">Account name<input class="h-9 rounded-md border bg-background px-3" name="account_name" required></label><label class="grid gap-1.5 text-sm">Masked account number<input class="h-9 rounded-md border bg-background px-3" name="masked_account_number"></label><label class="grid gap-1.5 text-sm">Ledger account<select class="h-9 rounded-md border bg-background px-3" name="ledger_account_key" required><option value="">Select</option><?php foreach($accountingAccounts as $account):if(!in_array($account['account_type'],['Bank','Cash'],true)||$account['account_status']!=='ACTIVE')continue;?><option value="<?= bx_h($account['account_key']) ?>"><?= bx_h($account['account_code'].' · '.$account['account_name']) ?></option><?php endforeach;?></select></label><label class="grid gap-1.5 text-sm">Currency<input class="h-9 rounded-md border bg-background px-3" name="currency" value="PHP" required></label></div><?php endif; ?>
<input type="hidden" name="status" value="ACTIVE"></div><footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button type="submit" class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Save</button></footer></form></section></div>
