<?php $financeSettings = $accountingFinanceData['financeSettings'] ?? []; ?>
<div id="finance-settings-modal" data-record-modal<?= $financeModalStateAttributes("finance-settings-modal") ?> hidden class="yovel-finance-operation-modal fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="finance-settings-title">
    <section class="flex max-h-[calc(100dvh-2rem)] w-full max-w-5xl flex-col overflow-hidden rounded-lg border bg-card shadow-lg">
        <header class="yovel-finance-sticky-modal-header flex items-start justify-between gap-4 border-b bg-card px-5 py-4"><div><h3 id="finance-settings-title" class="font-semibold">Finance Settings</h3><p class="mt-1 text-sm text-muted-foreground">Company currency, fiscal controls, BIR profile, and posting defaults.</p></div><button type="button" data-record-modal-close class="inline-flex size-8 items-center justify-center rounded-md border" aria-label="Close"><span class="material-symbols-rounded text-base">close</span></button></header>
        <form method="post" data-confirm-submit class="contents"><div class="yovel-modal-scroll grid gap-6 overflow-y-auto p-5"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="save_finance_settings"><input type="hidden" name="section" value="dashboard">
            <section><h4 class="mb-3 text-sm font-semibold">Company Accounting</h4><div class="grid gap-4 sm:grid-cols-3"><label class="grid gap-1.5 text-sm">Base currency<input class="h-9 rounded-md border bg-background px-3" name="base_currency" maxlength="3" value="<?= bx_h((string) ($financeSettings['base_currency'] ?? 'PHP')) ?>" required></label><label class="grid gap-1.5 text-sm">Currency precision<input class="h-9 rounded-md border bg-background px-3" type="number" min="0" max="6" name="currency_precision" value="<?= (int) ($financeSettings['currency_precision'] ?? 2) ?>" required></label><label class="grid gap-1.5 text-sm">Fiscal year starts<select class="h-9 rounded-md border bg-background px-3" name="fiscal_year_start_month"><?php foreach (range(1, 12) as $month): ?><option value="<?= $month ?>" <?= (int) ($financeSettings['fiscal_year_start_month'] ?? 1) === $month ? 'selected' : '' ?>><?= date('F', mktime(0, 0, 0, $month, 1)) ?></option><?php endforeach; ?></select></label></div></section>
            <section class="border-t pt-5"><h4 class="mb-3 text-sm font-semibold">Philippine BIR Profile</h4><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm">Registration<select class="h-9 rounded-md border bg-background px-3" name="vat_registration_type"><option <?= ($financeSettings['vat_registration_type'] ?? 'VAT') === 'VAT' ? 'selected' : '' ?>>VAT</option><option value="NON_VAT" <?= ($financeSettings['vat_registration_type'] ?? '') === 'NON_VAT' ? 'selected' : '' ?>>Non-VAT</option></select></label><label class="grid gap-1.5 text-sm">Registered name<input class="h-9 rounded-md border bg-background px-3" name="bir_registered_name" value="<?= bx_h((string) ($financeSettings['bir_registered_name'] ?? '')) ?>"></label><label class="grid gap-1.5 text-sm">TIN<input class="h-9 rounded-md border bg-background px-3" name="bir_tin" placeholder="000-000-000-00000" value="<?= bx_h((string) ($financeSettings['bir_tin'] ?? '')) ?>"></label><label class="grid gap-1.5 text-sm">Branch code<input class="h-9 rounded-md border bg-background px-3" name="bir_branch_code" inputmode="numeric" value="<?= bx_h((string) ($financeSettings['bir_branch_code'] ?? '')) ?>"></label><label class="grid gap-1.5 text-sm">RDO code<input class="h-9 rounded-md border bg-background px-3" name="bir_rdo_code" inputmode="numeric" value="<?= bx_h((string) ($financeSettings['bir_rdo_code'] ?? '')) ?>"></label></div></section>
            <section class="border-t pt-5"><h4 class="mb-3 text-sm font-semibold">Default Posting Accounts</h4><div class="grid gap-4 sm:grid-cols-2"><?php foreach (['default_receivable_account_key'=>'Receivable','default_payable_account_key'=>'Payable','default_income_account_key'=>'Income','default_expense_account_key'=>'Expense','default_output_vat_account_key'=>'Output VAT','default_input_vat_account_key'=>'Input VAT','retained_earnings_account_key'=>'Retained Earnings','round_off_account_key'=>'Round Off'] as $field => $label): ?><label class="grid gap-1.5 text-sm"><?= bx_h($label) ?><select class="h-9 rounded-md border bg-background px-3" name="<?= bx_h($field) ?>"><option value="">Not set</option><?php foreach ($accountingAccounts as $account): if ($account['is_group'] || $account['account_status'] !== 'ACTIVE') continue; ?><option value="<?= bx_h($account['account_key']) ?>" <?= (string) ($financeSettings[$field] ?? '') === (string) $account['account_key'] ? 'selected' : '' ?>><?= bx_h($account['account_code'] . ' / ' . $account['account_name']) ?></option><?php endforeach; ?></select></label><?php endforeach; ?></div></section>
        </div><footer class="flex justify-end gap-2 border-t bg-card px-5 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button class="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">Save Settings</button></footer></form>
    </section>
</div>
