<?php
declare(strict_types=1);

function yovel_admin_compliance_schema(): void
{
    $db = bx_db();
    $statements = [
        "CREATE TABLE IF NOT EXISTS project_company_compliance_rule_set (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            rule_set_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            jurisdiction_code CHAR(2) NOT NULL DEFAULT 'PH',
            rule_type VARCHAR(80) NOT NULL,
            rule_code VARCHAR(80) NOT NULL,
            rule_name VARCHAR(180) NOT NULL,
            version_number INT UNSIGNED NOT NULL DEFAULT 1,
            version_status ENUM('DRAFT','APPROVED','SUPERSEDED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            effective_from DATE NOT NULL,
            effective_to DATE NULL,
            authority_reference VARCHAR(160) NULL,
            authority_url VARCHAR(500) NULL,
            source_evidence_key CHAR(36) NULL,
            rule_json LONGTEXT NOT NULL,
            rule_sha256 CHAR(64) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            approved_by_admin_key CHAR(36) NULL,
            approved_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_rule_version (company_key_hash, jurisdiction_code, rule_type, rule_code, version_number),
            INDEX idx_cc_rule_company (company_key_hash),
            INDEX idx_cc_rule_effective (company_key_hash, jurisdiction_code, rule_type, version_status, effective_from, effective_to)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_tax_account_map (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            tax_account_map_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            rule_set_key CHAR(36) NOT NULL,
            mapping_code VARCHAR(80) NOT NULL,
            tax_role ENUM('OUTPUT_VAT','INPUT_VAT','WITHHOLDING','ADJUSTMENT','SETTLEMENT') NOT NULL,
            finance_account_key CHAR(36) NOT NULL,
            mapping_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_tax_map (company_key_hash, rule_set_key, mapping_code),
            INDEX idx_cc_tax_map_company (company_key_hash),
            INDEX idx_cc_tax_map_rule (company_key_hash, rule_set_key, mapping_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_template (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            template_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            template_code VARCHAR(80) NOT NULL,
            template_name VARCHAR(180) NOT NULL,
            document_type VARCHAR(80) NOT NULL,
            template_status ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            current_version_key CHAR(36) NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_template_code (company_key_hash, template_code),
            INDEX idx_cc_template_company (company_key_hash),
            INDEX idx_cc_template_status (company_key_hash, document_type, template_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_template_version (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            template_version_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            template_key CHAR(36) NOT NULL,
            version_number INT UNSIGNED NOT NULL,
            version_status ENUM('DRAFT','APPROVED','SUPERSEDED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            effective_from DATE NOT NULL,
            effective_to DATE NULL,
            schema_json LONGTEXT NOT NULL,
            schema_sha256 CHAR(64) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            approved_by_admin_key CHAR(36) NULL,
            approved_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_template_version (company_key_hash, template_key, version_number),
            INDEX idx_cc_template_ver_company (company_key_hash),
            INDEX idx_cc_template_ver_effective (company_key_hash, template_key, version_status, effective_from, effective_to)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_einvoice_record (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            einvoice_record_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            finance_document_key CHAR(36) NOT NULL,
            finance_document_sha256 CHAR(64) NOT NULL,
            document_type VARCHAR(80) NOT NULL,
            invoice_number VARCHAR(120) NOT NULL,
            schema_version VARCHAR(80) NOT NULL,
            rule_set_key CHAR(36) NOT NULL,
            template_version_key CHAR(36) NOT NULL,
            payload_json LONGTEXT NOT NULL,
            payload_sha256 CHAR(64) NOT NULL,
            transmission_status ENUM('DRAFT','VALIDATED','QUEUED','PROCESSING','ACKNOWLEDGED','REJECTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            acknowledgement_reference VARCHAR(180) NULL,
            correction_of_record_key CHAR(36) NULL,
            retention_until DATE NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_einvoice_source (company_key_hash, finance_document_key, schema_version, payload_sha256),
            INDEX idx_cc_einvoice_company (company_key_hash),
            INDEX idx_cc_einvoice_status (company_key_hash, transmission_status, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_import_batch (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            import_batch_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            batch_number VARCHAR(120) NOT NULL,
            schema_version VARCHAR(80) NOT NULL,
            source_file_name VARCHAR(255) NOT NULL,
            source_mime_type VARCHAR(120) NOT NULL,
            source_byte_size BIGINT UNSIGNED NOT NULL,
            source_sha256 CHAR(64) NOT NULL,
            batch_status ENUM('UPLOADED','VALIDATED','REJECTED','APPROVED','PROJECTING','PROJECTED','FAILED') NOT NULL DEFAULT 'UPLOADED',
            idempotency_key CHAR(64) NOT NULL,
            source_evidence_key CHAR(36) NULL,
            validation_json LONGTEXT NULL,
            validation_sha256 CHAR(64) NULL,
            error_message VARCHAR(1000) NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            approved_by_admin_key CHAR(36) NULL,
            approved_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_import_number (company_key_hash, batch_number),
            UNIQUE KEY uq_cc_import_source (company_key_hash, source_sha256),
            UNIQUE KEY uq_cc_import_idempotency (company_key_hash, idempotency_key),
            INDEX idx_cc_import_company (company_key_hash),
            INDEX idx_cc_import_status (company_key_hash, batch_status, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_import_item (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            import_item_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            import_batch_key CHAR(36) NOT NULL,
            source_fingerprint CHAR(64) NOT NULL,
            supplier_reference VARCHAR(180) NULL,
            supplier_tin VARCHAR(40) NULL,
            invoice_number VARCHAR(120) NOT NULL,
            invoice_date DATE NOT NULL,
            currency_code VARCHAR(20) NOT NULL DEFAULT 'PHP',
            net_amount DECIMAL(20,6) NOT NULL DEFAULT 0,
            tax_amount DECIMAL(20,6) NOT NULL DEFAULT 0,
            gross_amount DECIMAL(20,6) NOT NULL DEFAULT 0,
            item_status ENUM('STAGED','VALID','VALIDATION_FAILED','APPROVED','PROJECTED','FAILED') NOT NULL DEFAULT 'STAGED',
            payload_json LONGTEXT NOT NULL,
            payload_sha256 CHAR(64) NOT NULL,
            validation_json LONGTEXT NULL,
            finance_document_key CHAR(36) NULL,
            finance_document_sha256 CHAR(64) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_import_fingerprint (company_key_hash, source_fingerprint),
            INDEX idx_cc_import_item_company (company_key_hash),
            INDEX idx_cc_import_item_batch (company_key_hash, import_batch_key, item_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_withholding_authority (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            withholding_authority_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            authority_code VARCHAR(120) NOT NULL,
            version_number INT UNSIGNED NOT NULL DEFAULT 1,
            version_status ENUM('DRAFT','APPROVED','SUPERSEDED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            supplier_key CHAR(36) NULL,
            supplier_tin VARCHAR(40) NOT NULL,
            tax_category VARCHAR(80) NOT NULL,
            approved_rate DECIMAL(9,6) NOT NULL,
            amount_ceiling DECIMAL(20,6) NOT NULL DEFAULT 0,
            consumed_amount DECIMAL(20,6) NOT NULL DEFAULT 0,
            valid_from DATE NOT NULL,
            valid_to DATE NOT NULL,
            rule_set_key CHAR(36) NULL,
            source_evidence_key CHAR(36) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            approved_by_admin_key CHAR(36) NULL,
            approved_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_withholding_auth (company_key_hash, authority_code, version_number),
            INDEX idx_cc_withholding_auth_company (company_key_hash),
            INDEX idx_cc_withholding_auth_valid (company_key_hash, supplier_tin, tax_category, version_status, valid_from, valid_to)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_withholding_certificate (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            withholding_certificate_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            certificate_number VARCHAR(120) NOT NULL,
            certificate_status ENUM('DRAFT','ISSUED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            supplier_key CHAR(36) NULL,
            supplier_tin VARCHAR(40) NOT NULL,
            period_from DATE NOT NULL,
            period_to DATE NOT NULL,
            form_revision VARCHAR(80) NOT NULL,
            source_manifest_json LONGTEXT NOT NULL,
            source_manifest_sha256 CHAR(64) NOT NULL,
            payload_json LONGTEXT NOT NULL,
            payload_sha256 CHAR(64) NOT NULL,
            original_certificate_key CHAR(36) NULL,
            reprint_count INT UNSIGNED NOT NULL DEFAULT 0,
            output_evidence_key CHAR(36) NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            issued_by_admin_key CHAR(36) NULL,
            issued_at TIMESTAMP NULL,
            cancelled_by_admin_key CHAR(36) NULL,
            cancelled_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_certificate_number (company_key_hash, certificate_number),
            INDEX idx_cc_certificate_company (company_key_hash),
            INDEX idx_cc_certificate_period (company_key_hash, certificate_status, period_from, period_to)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_return_package (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            return_package_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            return_type VARCHAR(80) NOT NULL,
            period_from DATE NOT NULL,
            period_to DATE NOT NULL,
            filing_type ENUM('ORIGINAL','AMENDED') NOT NULL DEFAULT 'ORIGINAL',
            revision_number INT UNSIGNED NOT NULL DEFAULT 1,
            return_status ENUM('DRAFT','REVIEWED','APPROVED','SUPERSEDED') NOT NULL DEFAULT 'DRAFT',
            supersedes_return_key CHAR(36) NULL,
            form_revision VARCHAR(80) NOT NULL,
            source_manifest_json LONGTEXT NOT NULL,
            source_manifest_sha256 CHAR(64) NOT NULL,
            totals_json LONGTEXT NOT NULL,
            totals_sha256 CHAR(64) NOT NULL,
            source_evidence_key CHAR(36) NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            reviewed_by_admin_key CHAR(36) NULL,
            reviewed_at TIMESTAMP NULL,
            approved_by_admin_key CHAR(36) NULL,
            approved_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_return_revision (company_key_hash, return_type, period_from, period_to, revision_number),
            INDEX idx_cc_return_company (company_key_hash),
            INDEX idx_cc_return_period (company_key_hash, return_type, return_status, period_from, period_to)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_evidence (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            evidence_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            evidence_type VARCHAR(80) NOT NULL,
            source_module VARCHAR(80) NOT NULL,
            source_record_type VARCHAR(80) NOT NULL,
            source_record_key CHAR(36) NULL,
            original_file_name VARCHAR(255) NOT NULL,
            mime_type VARCHAR(120) NOT NULL,
            byte_size BIGINT UNSIGNED NOT NULL,
            storage_path VARCHAR(500) NOT NULL,
            sha256 CHAR(64) NOT NULL,
            metadata_json LONGTEXT NOT NULL,
            metadata_sha256 CHAR(64) NOT NULL,
            retention_rule_set_key CHAR(36) NULL,
            retention_until DATE NULL,
            evidence_status ENUM('ACTIVE','HELD','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_evidence_content (company_key_hash, sha256, source_record_type, source_record_key),
            INDEX idx_cc_evidence_company (company_key_hash),
            INDEX idx_cc_evidence_retention (company_key_hash, evidence_status, retention_until)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_approval (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            approval_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            record_type VARCHAR(80) NOT NULL,
            record_key CHAR(36) NOT NULL,
            approval_action ENUM('APPROVE','REJECT','PUBLISH','ISSUE','SUPERSEDE','ARCHIVE','CANCEL','REPRINT') NOT NULL,
            decision_status ENUM('PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING',
            record_sha256 CHAR(64) NOT NULL,
            comments VARCHAR(1000) NULL,
            requested_by_admin_key CHAR(36) NOT NULL,
            decided_by_admin_key CHAR(36) NULL,
            requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            decided_at TIMESTAMP NULL,
            UNIQUE KEY uq_cc_approval_decision (company_key_hash, record_type, record_key, approval_action, record_sha256),
            INDEX idx_cc_approval_company (company_key_hash),
            INDEX idx_cc_approval_pending (company_key_hash, decision_status, requested_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_export (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            export_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            export_type VARCHAR(80) NOT NULL,
            period_from DATE NULL,
            period_to DATE NULL,
            schema_version VARCHAR(80) NOT NULL,
            source_manifest_json LONGTEXT NOT NULL,
            source_manifest_sha256 CHAR(64) NOT NULL,
            payload_file_name VARCHAR(255) NULL,
            payload_mime_type VARCHAR(120) NULL,
            payload_byte_size BIGINT UNSIGNED NULL,
            payload_sha256 CHAR(64) NULL,
            row_count INT UNSIGNED NOT NULL DEFAULT 0,
            export_status ENUM('DRAFT','APPROVED','QUEUED','PROCESSING','SUCCEEDED','FAILED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            idempotency_key CHAR(64) NOT NULL,
            operations_job_key CHAR(36) NULL,
            acknowledgement_json LONGTEXT NULL,
            acknowledgement_sha256 CHAR(64) NULL,
            error_message VARCHAR(1000) NULL,
            output_evidence_key CHAR(36) NULL,
            retention_until DATE NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            approved_by_admin_key CHAR(36) NULL,
            approved_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_cc_export_idempotency (company_key_hash, idempotency_key),
            INDEX idx_cc_export_company (company_key_hash),
            INDEX idx_cc_export_status (company_key_hash, export_status, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_compliance_retention_hold (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            retention_hold_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            evidence_key CHAR(36) NOT NULL,
            hold_reference VARCHAR(160) NOT NULL,
            hold_reason VARCHAR(1000) NOT NULL,
            hold_status ENUM('ACTIVE','RELEASED') NOT NULL DEFAULT 'ACTIVE',
            placed_by_admin_key CHAR(36) NOT NULL,
            placed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            released_by_admin_key CHAR(36) NULL,
            released_at TIMESTAMP NULL,
            UNIQUE KEY uq_cc_hold_reference (company_key_hash, hold_reference),
            INDEX idx_cc_hold_company (company_key_hash),
            INDEX idx_cc_hold_evidence (company_key_hash, evidence_key, hold_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ];

    foreach ($statements as $index => $statement) {
        yovel_admin_db_execute($db, $statement, [], 'Compliance schema statement ' . ($index + 1));
    }

    $companyOwnedTables = [
        'project_company_compliance_rule_set',
        'project_company_compliance_tax_account_map',
        'project_company_compliance_template',
        'project_company_compliance_template_version',
        'project_company_compliance_einvoice_record',
        'project_company_compliance_import_batch',
        'project_company_compliance_import_item',
        'project_company_compliance_withholding_authority',
        'project_company_compliance_withholding_certificate',
        'project_company_compliance_return_package',
        'project_company_compliance_evidence',
        'project_company_compliance_approval',
        'project_company_compliance_export',
        'project_company_compliance_retention_hold',
    ];
    foreach ($companyOwnedTables as $table) {
        $companyKeyLength = (int) $db->GetOne(
            'SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?',
            [BUILDERX_DB_NAME, $table, 'company_key']
        );
        if ($companyKeyLength !== 1500) {
            yovel_admin_db_execute(
                $db,
                "ALTER TABLE `{$table}` MODIFY company_key VARCHAR(1500) NOT NULL",
                [],
                'Compliance company-key compatibility'
            );
        }
    }
}
