<?php
declare(strict_types=1);
$registerData = is_array($complianceData['einvoice_register'] ?? null) ? $complianceData['einvoice_register'] : ['availability' => 'UNAVAILABLE_DEPENDENCY', 'rows' => []];
$registerRows = is_array($registerData['rows'] ?? null) ? $registerData['rows'] : [];
$registerState = is_array($activeModuleFormState ?? null) ? $activeModuleFormState : [];
$registerFailedAction = (string) ($registerState['action'] ?? '');
$registerFailedInput = is_array($registerState['input'] ?? null) ? $registerState['input'] : [];
$registerValue = static fn (string $key, string $fallback = ''): string => (string) ($registerFailedInput[$key] ?? $fallback);
$registerOpen = static fn (string $action): string => $registerFailedAction === $action ? ' data-record-modal-open-on-load' : '';
$selectedRecordKey = trim((string) ($_GET['einvoice'] ?? ''));
if ($selectedRecordKey === '' && $registerRows !== []) $selectedRecordKey = (string) $registerRows[0]['einvoice_record_key'];
?>
<div data-compliance-einvoice-register>
<header class="flex flex-wrap items-start justify-between gap-3 border-b px-5 py-4"><div><h2 class="text-base font-semibold">Electronic invoice register</h2><p class="mt-1 text-sm text-muted-foreground">Compliance-owned immutable render snapshots and correction lineage.</p></div><span class="inline-flex h-7 items-center rounded-md bg-muted px-2 text-xs font-semibold"><?= bx_h((string) $registerData['availability']) ?></span></header>
<?php if (($registerData['availability'] ?? '') !== 'AVAILABLE'): ?><div class="m-5 border-l-4 border-amber-500 bg-amber-50 p-4 text-sm text-amber-950" role="status"><p class="font-semibold">Finance invoice snapshots unavailable</p><p class="mt-1 leading-6">Register data is withheld until the registered read-only owner provider is live. No source rows are fabricated.</p><code class="mt-2 block text-xs">accounting-finance.invoice-snapshot.v1</code></div><?php else: ?>
<div class="overflow-auto"><table class="w-full min-w-[52rem] text-sm"><thead class="border-b bg-muted/30 text-left text-xs text-muted-foreground"><tr><th class="px-5 py-3">Invoice</th><th class="px-5 py-3">Source</th><th class="px-5 py-3">Profile schema</th><th class="px-5 py-3">State</th><th class="px-5 py-3">Correction</th></tr></thead><tbody class="divide-y"><?php foreach ($registerRows as $row): ?><tr><td class="px-5 py-3"><a class="font-medium hover:underline" href="./?view=compliance-localization&amp;section=einvoice-register&amp;einvoice=<?= bx_h((string) $row['einvoice_record_key']) ?>"><?= bx_h((string) $row['invoice_number']) ?></a><span class="block text-xs text-muted-foreground"><?= bx_h((string) $row['document_type']) ?></span></td><td class="px-5 py-3 font-mono text-xs"><?= bx_h(substr((string) $row['finance_document_sha256'], 0, 12)) ?>...</td><td class="px-5 py-3"><?= bx_h((string) $row['schema_version']) ?></td><td class="px-5 py-3"><?= bx_h((string) $row['transmission_status']) ?></td><td class="px-5 py-3 font-mono text-xs"><?= bx_h(substr((string) (($row['correction_of_record_key'] ?? null) ?: '-'), 0, 12)) ?></td></tr><?php endforeach; ?><?php if ($registerRows === []): ?><tr><td colspan="5" class="px-5 py-10 text-center text-muted-foreground">No submitted Finance invoice snapshots match these filters.</td></tr><?php endif; ?></tbody></table></div>
<?php endif; ?>
</div>
<?php foreach ([['compliance-register-modal','register_compliance_einvoice','Register invoice','Register this submitted Finance invoice snapshot?'],['compliance-correction-modal','correct_compliance_einvoice','New correction','Register this submitted correction and preserve lineage?']] as [$id,$action,$title,$confirm]): ?><div id="<?= bx_h($id) ?>" data-record-modal<?= $registerOpen($action) ?> hidden class="fixed inset-0 z-[70] grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="<?= bx_h($id) ?>-title"><section class="w-[calc(100vw-2rem)] max-w-lg overflow-hidden rounded-lg border bg-popover shadow-lg"><header class="flex justify-between gap-4 border-b px-6 py-4"><div><h2 id="<?= bx_h($id) ?>-title" class="font-semibold"><?= bx_h($title) ?></h2><p class="mt-1 text-sm text-muted-foreground">Finance must return an exact immutable Submitted snapshot.</p></div><button type="button" data-record-modal-close class="size-8 rounded-md border" aria-label="Close <?= bx_h($title) ?> dialog"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" data-confirm-submit data-confirm-message="<?= bx_h($confirm) ?>" class="contents"><div class="grid gap-4 p-6"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="module_view" value="compliance-localization"><input type="hidden" name="action" value="<?= bx_h($action) ?>"><input type="hidden" name="section" value="einvoice-register"><label class="grid gap-1.5 text-sm">Finance document key<input name="finance_document_key" maxlength="36" required class="h-9 rounded-md border bg-background px-3 font-mono" value="<?= bx_h($registerValue('finance_document_key')) ?>"></label><?php if ($action === 'correct_compliance_einvoice'): ?><label class="grid gap-1.5 text-sm">Original register key<input name="correction_of_record_key" maxlength="36" required class="h-9 rounded-md border bg-background px-3 font-mono" value="<?= bx_h($registerValue('correction_of_record_key', $selectedRecordKey)) ?>"></label><?php endif; ?><button type="submit" class="h-9 w-fit rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"<?= empty($complianceData['finance_invoice_snapshot_available']) ? ' disabled' : '' ?>><?= bx_h($title) ?></button></div><footer class="flex justify-end border-t px-6 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button></footer></form></section></div><?php endforeach; ?>
<?php foreach ([['compliance-queue-modal','queue_compliance_einvoice','Queue transmission','Queue this validated e-invoice for transport?'],['compliance-retry-modal','retry_compliance_einvoice','Retry','Retry this rejected e-invoice with the same immutable payload?'],['compliance-cancel-modal','cancel_compliance_einvoice','Cancel','Cancel transmission without deleting the register record?']] as [$id,$action,$title,$confirm]): ?><div id="<?= bx_h($id) ?>" data-record-modal<?= $registerOpen($action) ?> hidden class="fixed inset-0 z-[70] grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="<?= bx_h($id) ?>-title"><section class="w-[calc(100vw-2rem)] max-w-lg overflow-hidden rounded-lg border bg-popover shadow-lg"><header class="flex justify-between border-b px-6 py-4"><h2 id="<?= bx_h($id) ?>-title" class="font-semibold"><?= bx_h($title) ?></h2><button type="button" data-record-modal-close class="size-8 rounded-md border" aria-label="Close <?= bx_h($title) ?> dialog"><span class="material-symbols-rounded text-base">close</span></button></header><form method="post" data-confirm-submit data-confirm-message="<?= bx_h($confirm) ?>" class="contents"><div class="grid gap-4 p-6"><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="module_view" value="compliance-localization"><input type="hidden" name="action" value="<?= bx_h($action) ?>"><input type="hidden" name="section" value="einvoice-register"><label class="grid gap-1.5 text-sm">Register key<input name="einvoice_record_key" maxlength="36" required class="h-9 rounded-md border bg-background px-3 font-mono" value="<?= bx_h($registerValue('einvoice_record_key', $selectedRecordKey)) ?>"></label><button type="submit" class="h-9 w-fit rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"><?= bx_h($title) ?></button></div><footer class="flex justify-end border-t px-6 py-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button></footer></form></section></div><?php endforeach; ?>
