<?php
declare(strict_types=1);

function yovel_admin_manufacturing_schema(): void
{
    $db = bx_db();
    $statements = [
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_audit (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            audit_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            record_type VARCHAR(80) NOT NULL,
            record_key VARCHAR(1500) NOT NULL,
            business_key VARCHAR(190) NOT NULL,
            audit_action VARCHAR(40) NOT NULL,
            persisted_values_json LONGTEXT NOT NULL,
            admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_mfg_audit_record (company_key_hash, record_type, business_key),
            INDEX idx_mfg_audit_created (company_key_hash, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_setting (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            setting_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            allow_overproduction_percent DECIMAL(9,4) NOT NULL DEFAULT 0,
            capacity_planning_enabled TINYINT(1) NOT NULL DEFAULT 1,
            default_wip_warehouse_key VARCHAR(1500) NULL,
            default_finished_goods_warehouse_key VARCHAR(1500) NULL,
            notes TEXT NULL,
            setting_status ENUM('ACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_setting_company (company_key_hash),
            INDEX idx_mfg_setting_status (company_key_hash, setting_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_form (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            form_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            target_section VARCHAR(80) NOT NULL,
            record_type VARCHAR(80) NOT NULL,
            form_title VARCHAR(180) NOT NULL,
            form_description VARCHAR(1000) NULL,
            form_status ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            current_form_version_key CHAR(36) NOT NULL,
            version_count INT UNSIGNED NOT NULL DEFAULT 1,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_form_title (company_key_hash, target_section, form_title),
            INDEX idx_mfg_form_target (company_key_hash, target_section, form_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_form_version (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            form_version_key CHAR(36) NOT NULL UNIQUE,
            form_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            target_section VARCHAR(80) NOT NULL,
            record_type VARCHAR(80) NOT NULL,
            version_number INT UNSIGNED NOT NULL,
            version_status ENUM('DRAFT','PUBLISHED') NOT NULL,
            schema_json LONGTEXT NOT NULL,
            schema_checksum CHAR(64) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_form_version (company_key_hash, form_key, version_number),
            INDEX idx_mfg_form_version_status (company_key_hash, form_key, version_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_form_audit (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            form_audit_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            form_key CHAR(36) NOT NULL,
            form_version_key CHAR(36) NOT NULL,
            audit_action VARCHAR(40) NOT NULL,
            schema_checksum CHAR(64) NOT NULL,
            admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_mfg_form_audit (company_key_hash, form_key, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_record_form_version (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            binding_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            record_type VARCHAR(80) NOT NULL,
            record_key VARCHAR(1500) NOT NULL,
            record_key_hash CHAR(64) NOT NULL,
            form_key CHAR(36) NOT NULL,
            form_version_key CHAR(36) NOT NULL,
            bound_by_admin_key CHAR(36) NOT NULL,
            bound_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_record_form (company_key_hash, record_type, record_key_hash),
            INDEX idx_mfg_record_form_version (company_key_hash, form_version_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_operation (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            operation_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            operation_code VARCHAR(80) NOT NULL,
            operation_name VARCHAR(180) NOT NULL,
            description VARCHAR(1000) NULL,
            hourly_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
            cost_account_key VARCHAR(1500) NULL,
            record_status ENUM('DRAFT','ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_operation_code (company_key_hash, operation_code),
            INDEX idx_mfg_operation_status (company_key_hash, record_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_sub_operation (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            sub_operation_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            parent_operation_key CHAR(36) NOT NULL,
            operation_key CHAR(36) NOT NULL,
            sequence_no INT UNSIGNED NOT NULL,
            duration_minutes DECIMAL(12,4) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_sub_operation_sequence (company_key_hash, parent_operation_key, sequence_no),
            UNIQUE KEY uq_mfg_sub_operation_ref (company_key_hash, parent_operation_key, operation_key),
            INDEX idx_mfg_sub_operation_parent (company_key_hash, parent_operation_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_routing (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            routing_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            routing_code VARCHAR(80) NOT NULL,
            routing_name VARCHAR(180) NOT NULL,
            record_status ENUM('DRAFT','ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_routing_code (company_key_hash, routing_code),
            INDEX idx_mfg_routing_status (company_key_hash, record_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_routing_operation (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            routing_operation_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            routing_key CHAR(36) NOT NULL,
            operation_key CHAR(36) NOT NULL,
            sequence_no INT UNSIGNED NOT NULL,
            duration_minutes DECIMAL(12,4) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_routing_operation_sequence (company_key_hash, routing_key, sequence_no),
            UNIQUE KEY uq_mfg_routing_operation_ref (company_key_hash, routing_key, operation_key),
            INDEX idx_mfg_routing_operation_parent (company_key_hash, routing_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_workstation_type (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            workstation_type_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            workstation_type_code VARCHAR(80) NOT NULL,
            workstation_type_name VARCHAR(180) NOT NULL,
            record_status ENUM('DRAFT','ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_workstation_type_code (company_key_hash, workstation_type_code),
            INDEX idx_mfg_workstation_type_status (company_key_hash, record_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_workstation_type_operation (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            workstation_type_operation_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            workstation_type_key CHAR(36) NOT NULL,
            operation_key CHAR(36) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_workstation_type_operation (company_key_hash, workstation_type_key, operation_key),
            INDEX idx_mfg_workstation_type_operation_parent (company_key_hash, workstation_type_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_working_hour (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            working_hour_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            workstation_type_key CHAR(36) NOT NULL,
            weekday_no TINYINT UNSIGNED NOT NULL,
            start_time TIME NOT NULL,
            end_time TIME NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_working_hour (company_key_hash, workstation_type_key, weekday_no, start_time, end_time),
            INDEX idx_mfg_working_hour_parent (company_key_hash, workstation_type_key, weekday_no)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_workstation_type_component (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            component_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            workstation_type_key CHAR(36) NOT NULL,
            component_name VARCHAR(180) NOT NULL,
            hourly_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
            cost_account_key VARCHAR(1500) NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_workstation_type_component (company_key_hash, workstation_type_key, component_name),
            INDEX idx_mfg_workstation_type_component_parent (company_key_hash, workstation_type_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_plant_floor (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            plant_floor_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            plant_floor_code VARCHAR(80) NOT NULL,
            plant_floor_name VARCHAR(180) NOT NULL,
            record_status ENUM('DRAFT','ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_plant_floor_code (company_key_hash, plant_floor_code),
            INDEX idx_mfg_plant_floor_status (company_key_hash, record_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_workstation (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            workstation_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            workstation_code VARCHAR(80) NOT NULL,
            workstation_name VARCHAR(180) NOT NULL,
            workstation_type_key CHAR(36) NOT NULL,
            plant_floor_key CHAR(36) NOT NULL,
            capacity_units INT UNSIGNED NOT NULL DEFAULT 1,
            hourly_rate DECIMAL(18,6) NOT NULL DEFAULT 0,
            cost_account_key VARCHAR(1500) NULL,
            holiday_dates_json LONGTEXT NOT NULL,
            record_status ENUM('DRAFT','ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_workstation_code (company_key_hash, workstation_code),
            INDEX idx_mfg_workstation_status (company_key_hash, record_status),
            INDEX idx_mfg_workstation_type (company_key_hash, workstation_type_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_workstation_cost (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            workstation_cost_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            workstation_key CHAR(36) NOT NULL,
            cost_type VARCHAR(80) NOT NULL,
            hourly_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
            cost_account_key VARCHAR(1500) NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_workstation_cost (company_key_hash, workstation_key, cost_type),
            INDEX idx_mfg_workstation_cost_parent (company_key_hash, workstation_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_workstation_component (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            component_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            workstation_key CHAR(36) NOT NULL,
            component_name VARCHAR(180) NOT NULL,
            hourly_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
            cost_account_key VARCHAR(1500) NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_workstation_component (company_key_hash, workstation_key, component_name),
            INDEX idx_mfg_workstation_component_parent (company_key_hash, workstation_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_bom (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            bom_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            bom_code VARCHAR(80) NOT NULL,
            item_key VARCHAR(1500) NOT NULL,
            revision INT UNSIGNED NOT NULL DEFAULT 1,
            quantity DECIMAL(18,9) NOT NULL,
            uom_key VARCHAR(80) NOT NULL,
            currency VARCHAR(20) NOT NULL,
            is_alternative TINYINT(1) NOT NULL DEFAULT 0,
            alternative_for_bom_key CHAR(36) NULL,
            effective_from DATE NOT NULL,
            effective_to DATE NULL,
            process_loss_percent DECIMAL(9,4) NOT NULL DEFAULT 0,
            lifecycle_status ENUM('DRAFT','SUBMITTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            amended_from_bom_key CHAR(36) NULL,
            submitted_version_key CHAR(36) NULL,
            expense_account_key VARCHAR(1500) NULL,
            material_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
            operation_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
            process_loss_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
            scrap_credit DECIMAL(18,6) NOT NULL DEFAULT 0,
            total_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
            cost_inputs_json LONGTEXT NULL,
            cost_calculation_hash CHAR(64) NULL,
            notes VARCHAR(2000) NULL,
            cancellation_reason VARCHAR(1000) NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            submitted_by_admin_key CHAR(36) NULL,
            cancelled_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            submitted_at DATETIME NULL,
            cancelled_at DATETIME NULL,
            UNIQUE KEY uq_mfg_bom_code (company_key_hash, bom_code),
            INDEX idx_mfg_bom_item (company_key_hash, item_key(190), lifecycle_status),
            INDEX idx_mfg_bom_alternative (company_key_hash, alternative_for_bom_key),
            INDEX idx_mfg_bom_amended (company_key_hash, amended_from_bom_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_bom_component (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            component_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            bom_key CHAR(36) NOT NULL,
            item_key VARCHAR(1500) NOT NULL,
            child_bom_key CHAR(36) NULL,
            sequence_no INT UNSIGNED NOT NULL,
            quantity DECIMAL(18,9) NOT NULL,
            uom_key VARCHAR(80) NOT NULL,
            conversion_factor DECIMAL(18,9) NOT NULL,
            stock_quantity DECIMAL(18,9) NOT NULL,
            stock_uom_code VARCHAR(80) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_bom_component_sequence (company_key_hash, bom_key, sequence_no),
            INDEX idx_mfg_bom_component_parent (company_key_hash, bom_key),
            INDEX idx_mfg_bom_component_child (company_key_hash, child_bom_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_bom_operation (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            bom_operation_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            bom_key CHAR(36) NOT NULL,
            operation_key CHAR(36) NOT NULL,
            sequence_no INT UNSIGNED NOT NULL,
            duration_minutes DECIMAL(18,6) NOT NULL,
            hourly_rate DECIMAL(18,6) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_bom_operation_sequence (company_key_hash, bom_key, sequence_no),
            INDEX idx_mfg_bom_operation_parent (company_key_hash, bom_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_bom_secondary_item (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            secondary_item_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            bom_key CHAR(36) NOT NULL,
            item_key VARCHAR(1500) NOT NULL,
            secondary_type ENUM('SCRAP','BY_PRODUCT','PROCESS_LOSS') NOT NULL,
            sequence_no INT UNSIGNED NOT NULL,
            quantity DECIMAL(18,9) NOT NULL,
            uom_key VARCHAR(80) NOT NULL,
            conversion_factor DECIMAL(18,9) NOT NULL,
            stock_quantity DECIMAL(18,9) NOT NULL,
            stock_uom_code VARCHAR(80) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_bom_secondary_sequence (company_key_hash, bom_key, sequence_no),
            INDEX idx_mfg_bom_secondary_parent (company_key_hash, bom_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_bom_version (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            version_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            bom_key CHAR(36) NOT NULL,
            revision INT UNSIGNED NOT NULL,
            snapshot_json LONGTEXT NOT NULL,
            snapshot_checksum CHAR(64) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_mfg_bom_version (company_key_hash, bom_key, revision),
            INDEX idx_mfg_bom_version_parent (company_key_hash, bom_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_bom_update_batch (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            update_batch_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            bom_key CHAR(36) NOT NULL,
            valuation_date DATE NOT NULL,
            input_checksum CHAR(64) NOT NULL,
            calculation_hash CHAR(64) NOT NULL,
            batch_status ENUM('COMPLETED','FAILED') NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_mfg_bom_update_batch (company_key_hash, bom_key, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_bom_update_log (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            update_log_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            update_batch_key CHAR(36) NOT NULL,
            bom_key CHAR(36) NOT NULL,
            log_type VARCHAR(40) NOT NULL,
            source_key VARCHAR(1500) NOT NULL,
            input_json LONGTEXT NOT NULL,
            result_json LONGTEXT NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_mfg_bom_update_log (company_key_hash, update_batch_key, x_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_manufacturing_downtime (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            downtime_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            workstation_key CHAR(36) NOT NULL,
            starts_at DATETIME NOT NULL,
            ends_at DATETIME NOT NULL,
            duration_minutes INT UNSIGNED NOT NULL,
            reason VARCHAR(500) NOT NULL,
            record_status ENUM('DRAFT','ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_mfg_downtime_station (company_key_hash, workstation_key, starts_at, ends_at),
            INDEX idx_mfg_downtime_status (company_key_hash, record_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ];
    foreach ($statements as $statement) {
        yovel_admin_manufacturing_execute($db, $statement, [], 'Manufacturing schema update');
    }
}
