<?php
declare(strict_types=1);

$root=dirname(__DIR__);
require_once $root.'/app/foundation.php';
require_once $root.'/company/admin/core/functions.php';
require_once $root.'/company/admin/modules/sales-crm/functions.php';
require_once $root.'/company/admin/modules/accounting-finance/functions.php';
require_once $root.'/company/admin/modules/accounting-finance/core.php';
require_once $root.'/company/admin/modules/accounting-finance/tax.php';
require_once $root.'/company/admin/modules/accounting-finance/ledger.php';
require_once $root.'/company/admin/modules/accounting-finance/invoices.php';
require_once $root.'/company/admin/modules/accounting-finance/payments.php';
function payment_assert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
function payment_error(callable $fn,string $needle):void{try{$fn();}catch(Throwable $e){payment_assert(str_contains(strtolower($e->getMessage()),strtolower($needle)),'Unexpected payment error: '.$e->getMessage());return;}throw new RuntimeException('Expected payment error: '.$needle);}
yovel_admin_sales_crm_schema();yovel_admin_accounting_finance_schema();yovel_admin_finance_core_schema();yovel_admin_general_ledger_schema();yovel_admin_finance_invoice_schema();yovel_admin_finance_payment_schema();$db=bx_db();
$f=$db->GetRow("SELECT c.company_key,c.company_key_hash,c.company_name,a.admin_key FROM project_company c JOIN project_company_admin a ON a.company_key_hash=c.company_key_hash AND a.admin_status='ACTIVE' WHERE c.company_status<>'DELETED' LIMIT 1");payment_assert((bool)$f,'Fixture required.');$company=['company_key'=>$f['company_key'],'company_key_hash'=>$f['company_key_hash'],'company_name'=>$f['company_name']];$admin=['admin_key'=>$f['admin_key']];$s=strtoupper(substr(str_replace('-','',bx_uuid()),0,10));
$keys=['customer'=>bx_uuid(),'invoice'=>bx_uuid(),'payment'=>bx_uuid(),'bad'=>bx_uuid(),'ar'=>bx_uuid(),'income'=>bx_uuid(),'vat'=>bx_uuid(),'bank'=>bx_uuid(),'bank2'=>bx_uuid()];
$sql="INSERT INTO project_company_accounting_account (account_key,company_key,company_key_hash,account_code,account_name,root_type,report_type,account_type,account_currency,is_group,balance_must_be,account_status,created_by_admin_key,updated_by_admin_key) VALUES (?,?,?,?,?,?,?,?,'PHP',0,'EITHER','ACTIVE',?,?)";
foreach([['ar','AR','ASSET','BALANCE_SHEET','Receivable'],['income','INC','INCOME','PROFIT_LOSS','Income Account'],['vat','VAT','LIABILITY','BALANCE_SHEET','Tax'],['bank','BANK','ASSET','BALANCE_SHEET','Bank'],['bank2','BANK2','ASSET','BALANCE_SHEET','Bank']] as [$k,$c,$r,$rep,$t])$db->Execute($sql,[$keys[$k],$company['company_key'],$company['company_key_hash'],$c.'_'.$s,$c.' '.$s,$r,$rep,$t,$admin['admin_key'],$admin['admin_key']]);
$db->Execute("INSERT INTO project_company_sales_customer (customer_key,company_key,company_key_hash,customer_code,customer_name,customer_status) VALUES (?,?,?,?,?,'ACTIVE')",[$keys['customer'],$company['company_key'],$company['company_key_hash'],'CUS_'.$s,'Customer '.$s]);
try{
 yovel_admin_persist_finance_settings($db,$company,$admin,['base_currency'=>'PHP','default_receivable_account_key'=>$keys['ar'],'default_income_account_key'=>$keys['income'],'default_output_vat_account_key'=>$keys['vat']]);
 yovel_admin_persist_finance_master($db,$company,$admin,'bank-account',['bank_account_code'=>'BANK_'.$s,'bank_name'=>'Test Bank','account_name'=>'Operating','ledger_account_key'=>$keys['bank'],'currency'=>'PHP']);
 $inv=yovel_admin_persist_finance_invoice($db,$company,$admin,'SALES',['invoice_key'=>$keys['invoice'],'invoice_no'=>'SI-'.$s,'posting_date'=>'2026-06-01','due_date'=>'2026-06-30','party_key'=>$keys['customer'],'lines'=>[['description'=>'Service','quantity'=>'1','unit_amount'=>'1000','account_key'=>$keys['income'],'tax_code'=>'VAT12']]]);yovel_admin_submit_finance_invoice($db,$company,$admin,'SALES',$keys['invoice']);
 $draft=yovel_admin_persist_payment_entry($db,$company,$admin,['payment_entry_key'=>$keys['payment'],'payment_no'=>'PAY-'.$s,'payment_type'=>'RECEIVE','posting_date'=>'2026-06-15','party_type'=>'CUSTOMER','party_key'=>$keys['customer'],'paid_to_account_key'=>$keys['bank'],'party_account_key'=>$keys['ar'],'paid_amount'=>'500','received_amount'=>'500','allocations'=>[['invoice_key'=>$keys['invoice'],'allocated_amount'=>'500']]]);payment_assert($draft['document_status']==='DRAFT','Payment Draft failed.');
 $submitted=yovel_admin_submit_payment_entry($db,$company,$admin,$keys['payment']);payment_assert($submitted['document_status']==='SUBMITTED','Payment submission failed.');payment_assert(yovel_admin_invoice_outstanding($company,$keys['invoice'])==='620.000000','Partial allocation failed.');payment_assert($submitted['unallocated_amount']==='0.000000','Payment allocation total failed.');
 payment_error(fn()=>yovel_admin_persist_payment_entry($db,$company,$admin,['payment_entry_key'=>$keys['bad'],'payment_no'=>'BAD-'.$s,'payment_type'=>'RECEIVE','posting_date'=>'2026-06-16','party_type'=>'CUSTOMER','party_key'=>$keys['customer'],'paid_to_account_key'=>$keys['bank'],'party_account_key'=>$keys['ar'],'paid_amount'=>'700','received_amount'=>'700','allocations'=>[['invoice_key'=>$keys['invoice'],'allocated_amount'=>'700']]]),'outstanding');
 $cancel=yovel_admin_cancel_payment_entry($db,$company,$admin,$keys['payment'],'2026-06-20','Payment fixture cancellation');payment_assert($cancel['document_status']==='CANCELLED','Payment cancellation failed.');payment_assert(yovel_admin_invoice_outstanding($company,$keys['invoice'])==='1120.000000','Cancellation did not restore outstanding.');
 $transfer=yovel_admin_persist_payment_entry($db,$company,$admin,['payment_no'=>'TR-'.$s,'payment_type'=>'INTERNAL_TRANSFER','posting_date'=>'2026-06-21','paid_from_account_key'=>$keys['bank'],'paid_to_account_key'=>$keys['bank2'],'paid_amount'=>'100','received_amount'=>'100']);$transferKey=$transfer['payment_entry_key'];$transfer=yovel_admin_submit_payment_entry($db,$company,$admin,$transferKey);payment_assert($transfer['document_status']==='SUBMITTED','Internal transfer failed.');
}finally{$h=$company['company_key_hash'];$paymentKeys=array_values(array_filter([$keys['payment'],$keys['bad'],$transferKey??'']));if($paymentKeys){$m=implode(',',array_fill(0,count($paymentKeys),'?'));$p=array_merge([$h],$paymentKeys);$db->Execute("DELETE FROM project_company_general_ledger_entry WHERE company_key_hash=? AND source_record_key IN ($m)",$p);$db->Execute("DELETE FROM project_company_general_ledger_transaction WHERE company_key_hash=? AND source_record_key IN ($m)",$p);$db->Execute("DELETE FROM project_company_finance_payment_allocation WHERE company_key_hash=? AND payment_entry_key IN ($m)",$p);$db->Execute("DELETE FROM project_company_finance_payment_deduction WHERE company_key_hash=? AND payment_entry_key IN ($m)",$p);$db->Execute("DELETE FROM project_company_finance_payment_entry WHERE company_key_hash=? AND payment_entry_key IN ($m)",$p);} $db->Execute('DELETE FROM project_company_general_ledger_entry WHERE company_key_hash=? AND source_record_key=?',[$h,$keys['invoice']]);$db->Execute('DELETE FROM project_company_general_ledger_transaction WHERE company_key_hash=? AND source_record_key=?',[$h,$keys['invoice']]);foreach(['project_company_finance_invoice_tax','project_company_finance_invoice_line','project_company_finance_payment_term','project_company_finance_invoice'] as $t)$db->Execute("DELETE FROM $t WHERE company_key_hash=? AND invoice_key=?",[$h,$keys['invoice']]);$db->Execute('DELETE FROM project_company_finance_bank_account WHERE company_key_hash=? AND ledger_account_key=?',[$h,$keys['bank']]);$db->Execute('DELETE FROM project_company_finance_setting WHERE company_key_hash=?',[$h]);$db->Execute('DELETE FROM project_company_sales_customer WHERE company_key_hash=? AND customer_key=?',[$h,$keys['customer']]);$db->Execute('DELETE FROM project_company_accounting_account WHERE company_key_hash=? AND account_key IN (?,?,?,?,?)',array_merge([$h],array_values(array_intersect_key($keys,array_flip(['ar','income','vat','bank','bank2'])))));}
echo "Accounting/Finance payment checks passed.\n";
