<?php
declare(strict_types=1);

$calendarProjection = is_array($activeModuleData['workforce_calendar_projection'] ?? null)
    ? $activeModuleData['workforce_calendar_projection']
    : yovel_admin_operations_workforce_projection_unavailable($company ?? [], 'HR calendar projection is unavailable.');
$calendarDirectories = is_array($calendarProjection['directories'] ?? null) ? $calendarProjection['directories'] : [];
$holidayLists = is_array($calendarDirectories['holiday_list']['records'] ?? null) ? $calendarDirectories['holiday_list']['records'] : [];
$holidays = is_array($calendarDirectories['holiday']['records'] ?? null) ? $calendarDirectories['holiday']['records'] : [];
$calendarRange = is_array($calendarProjection['calendar_range'] ?? null) ? $calendarProjection['calendar_range'] : [];
$calendarAvailable = ($calendarDirectories['holiday_list']['status'] ?? '') === 'AVAILABLE'
    && ($calendarDirectories['holiday']['status'] ?? '') === 'AVAILABLE';
ob_start();
?>
<div class="grid gap-4"><div class="grid gap-2"><h3 class="text-sm font-semibold">HR owner actions</h3><a class="inline-flex min-h-9 items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm font-medium hover:bg-muted/70" href="?view=hr&amp;section=attendance"><span class="material-symbols-rounded text-base" aria-hidden="true">open_in_new</span>Open HR attendance</a><a class="inline-flex min-h-9 items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm font-medium hover:bg-muted/70" href="?view=hr&amp;section=leave-requests"><span class="material-symbols-rounded text-base" aria-hidden="true">open_in_new</span>Open HR leave requests</a></div><div><h3 class="text-sm font-semibold">Projection range</h3><p class="mt-1 text-sm text-muted-foreground"><?= bx_h((string) ($calendarRange['from_date'] ?? 'Unavailable')) ?> to <?= bx_h((string) ($calendarRange['to_date'] ?? 'Unavailable')) ?></p></div></div>
<?php
$operationsSectionTools = (string) ob_get_clean();
?>
<div class="grid gap-5" data-operations-workforce-calendars>
    <div><h2 class="text-base font-semibold">Workforce calendars</h2><p class="mt-1 text-sm leading-6 text-muted-foreground">Exact read-only Holiday List and Holiday records from the verified HR calendar directory. Authoritative changes remain in HR.</p></div>
    <?php if (!$calendarAvailable): ?><div role="status" class="rounded-md bg-muted/60 p-4 text-sm"><p class="font-semibold">HR calendar unavailable</p><p class="mt-1 leading-6 text-muted-foreground">The HR calendar owner response is unavailable or invalid for this company and date range. Operations does not substitute empty or inferred holiday records.</p></div><?php endif; ?>
    <div class="grid gap-3 sm:grid-cols-2">
        <?php foreach (['holiday', 'holiday_list'] as $directoryKey): $directory = $calendarDirectories[$directoryKey] ?? []; ?>
            <div class="rounded-md bg-muted/40 p-4"><div class="flex items-start justify-between gap-3"><div><h3 class="text-sm font-semibold"><?= bx_h((string) ($directory['label'] ?? ucwords(str_replace('_', ' ', $directoryKey)))) ?></h3><p class="mt-1 text-xs text-muted-foreground"><?= count($directory['records'] ?? []) ?> owner records</p></div><span class="text-xs font-medium"><?= bx_h((string) ($directory['status'] ?? 'UNAVAILABLE_DEPENDENCY')) ?></span></div><p class="mt-3 text-sm leading-6 text-muted-foreground"><?= bx_h((string) ($directory['reason'] ?? 'HR calendar fields are unavailable.')) ?> This source is non-blocking.</p><?php if (($directory['unavailable_fields'] ?? []) !== []): ?><p class="mt-2 text-xs leading-5 text-muted-foreground">Unavailable fields: <?= bx_h(implode(', ', array_map('strval', $directory['unavailable_fields']))) ?>.</p><?php endif; ?></div>
        <?php endforeach; ?>
    </div>
    <div class="grid gap-3"><h3 class="text-sm font-semibold">Holiday lists</h3><div class="overflow-x-auto"><table class="w-full min-w-[44rem] text-left text-sm"><thead class="bg-muted/50 text-xs text-muted-foreground"><tr><th class="px-3 py-2.5">List</th><th class="px-3 py-2.5">Range</th><th class="px-3 py-2.5">Timezone</th><th class="px-3 py-2.5">Status</th></tr></thead><tbody class="divide-y"><?php if ($holidayLists === []): ?><tr><td colspan="4" class="px-3 py-8 text-center text-muted-foreground"><?= $calendarAvailable ? 'No holiday lists overlap this range.' : 'Holiday List records are unavailable from HR.' ?></td></tr><?php else: foreach ($holidayLists as $list): ?><tr><td class="px-3 py-2.5"><div class="font-medium"><?= bx_h((string) $list['holiday_list_name']) ?></div><div class="text-xs text-muted-foreground"><?= bx_h((string) $list['holiday_list_code']) ?></div></td><td class="px-3 py-2.5"><?= bx_h((string) $list['from_date']) ?> to <?= bx_h((string) $list['to_date']) ?></td><td class="px-3 py-2.5"><?= bx_h((string) $list['timezone_name']) ?></td><td class="px-3 py-2.5"><?= bx_h((string) $list['holiday_list_status']) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
    <div class="grid gap-3"><h3 class="text-sm font-semibold">Holidays</h3><div class="overflow-x-auto"><table class="w-full min-w-[38rem] text-left text-sm"><thead class="bg-muted/50 text-xs text-muted-foreground"><tr><th class="px-3 py-2.5">Date</th><th class="px-3 py-2.5">Description</th><th class="px-3 py-2.5">Holiday list reference</th><th class="px-3 py-2.5">Status</th></tr></thead><tbody class="divide-y"><?php if ($holidays === []): ?><tr><td colspan="4" class="px-3 py-8 text-center text-muted-foreground"><?= $calendarAvailable ? 'No holidays fall within this range.' : 'Holiday records are unavailable from HR.' ?></td></tr><?php else: foreach ($holidays as $holiday): ?><tr><td class="px-3 py-2.5"><?= bx_h((string) $holiday['holiday_date']) ?></td><td class="px-3 py-2.5 font-medium"><?= bx_h((string) $holiday['description']) ?></td><td class="px-3 py-2.5 font-mono text-xs break-all"><?= bx_h((string) $holiday['holiday_list_key']) ?></td><td class="px-3 py-2.5"><?= bx_h((string) $holiday['holiday_status']) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
</div>
