<?php
declare(strict_types=1);

$catalogProjection = is_array($activeModuleData['catalog_projection'] ?? null)
    ? $activeModuleData['catalog_projection']
    : ['directories' => yovel_admin_operations_catalog_empty_directories(), 'sources' => [], 'contexts' => ['warehouses' => []], 'owner_actions' => yovel_admin_operations_catalog_owner_actions()];
$catalogDirectories = is_array($catalogProjection['directories'] ?? null) ? $catalogProjection['directories'] : [];
$catalogUoms = is_array($catalogDirectories['uom']['records'] ?? null) ? $catalogDirectories['uom']['records'] : [];
$catalogConversions = is_array($catalogDirectories['uom_conversion_factor']['records'] ?? null) ? $catalogDirectories['uom_conversion_factor']['records'] : [];
$catalogSources = is_array($catalogProjection['sources'] ?? null) ? $catalogProjection['sources'] : [];
ob_start();
?>
<div class="grid gap-5">
    <div class="grid gap-2"><h3 class="text-sm font-semibold">Inventory owner actions</h3><?php foreach ($catalogProjection['owner_actions'] ?? [] as $action): ?><a class="inline-flex min-h-9 items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm font-medium hover:bg-muted/70" href="<?= bx_h((string) $action['href']) ?>"><span class="material-symbols-rounded text-base" aria-hidden="true">open_in_new</span><?= bx_h((string) $action['label']) ?></a><?php endforeach; ?></div>
    <div class="grid gap-3"><h3 class="text-sm font-semibold">Owner sources</h3><?php foreach ($catalogSources as $source): ?><div class="rounded-md bg-muted/40 p-3"><p class="text-sm font-medium"><?= bx_h((string) ($source['service'] ?? 'Inventory service')) ?></p><p class="mt-1 break-all text-xs font-medium"><?= bx_h((string) ($source['status'] ?? 'UNAVAILABLE_DEPENDENCY')) ?></p><?php if (($source['reason'] ?? '') !== ''): ?><p class="mt-2 text-xs leading-5 text-muted-foreground"><?= bx_h((string) $source['reason']) ?></p><?php endif; ?></div><?php endforeach; ?></div>
</div>
<?php
$operationsSectionTools = (string) ob_get_clean();
?>
<div class="grid gap-5" data-operations-catalog-units>
    <div><h2 class="text-base font-semibold">Catalog and unit projections</h2><p class="mt-1 text-sm leading-6 text-muted-foreground">Read-only Inventory UOM definitions and item conversion directions. Authoritative catalog changes remain in Inventory.</p></div>
    <div class="grid gap-3 sm:grid-cols-2">
        <?php foreach (['brand', 'item_group', 'uom', 'uom_conversion_factor'] as $directoryKey): $directory = $catalogDirectories[$directoryKey] ?? []; ?>
            <div class="rounded-md bg-muted/40 p-4"><div class="flex items-start justify-between gap-3"><h3 class="text-sm font-semibold"><?= bx_h((string) ($directory['label'] ?? ucwords(str_replace('_', ' ', $directoryKey)))) ?></h3><span class="break-all text-right text-xs font-medium"><?= bx_h((string) ($directory['status'] ?? 'UNAVAILABLE_DEPENDENCY')) ?></span></div><?php if (($directory['records'] ?? []) !== []): ?><p class="mt-2 text-xs text-muted-foreground">Verified owner records are available below.</p><?php endif; ?><?php if (($directory['reason'] ?? '') !== ''): ?><p role="status" class="mt-2 text-sm leading-6 text-muted-foreground"><?= bx_h((string) $directory['reason']) ?> This source is non-blocking.</p><?php endif; ?><?php if (($directory['unavailable_fields'] ?? []) !== []): ?><p class="mt-2 text-xs leading-5 text-muted-foreground">Unavailable fields: <?= bx_h(implode(', ', array_map('strval', $directory['unavailable_fields']))) ?>.</p><?php endif; ?></div>
        <?php endforeach; ?>
    </div>
    <div class="grid gap-3"><h3 class="text-sm font-semibold">Units of measure</h3><div class="overflow-x-auto"><table class="w-full min-w-[40rem] text-left text-sm"><thead class="bg-muted/50 text-xs text-muted-foreground"><tr><th class="px-3 py-2.5">Code</th><th class="px-3 py-2.5">Name</th><th class="px-3 py-2.5">Category</th><th class="px-3 py-2.5">Stable owner key</th></tr></thead><tbody class="divide-y"><?php if ($catalogUoms === []): ?><tr><td colspan="4" class="px-3 py-8 text-center text-muted-foreground"><?= ($catalogDirectories['uom']['status'] ?? '') === 'PARTIAL' ? 'No verified UOM records are exposed by current items.' : 'UOM records are unavailable from Inventory.' ?></td></tr><?php else: foreach ($catalogUoms as $uom): ?><tr><td class="px-3 py-2.5 font-medium"><?= bx_h((string) $uom['uom_code']) ?></td><td class="px-3 py-2.5"><?= bx_h((string) $uom['uom_name']) ?></td><td class="px-3 py-2.5"><?= bx_h((string) $uom['uom_category']) ?></td><td class="px-3 py-2.5 font-mono text-xs break-all"><?= bx_h((string) $uom['uom_key']) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
    <div class="grid gap-3"><h3 class="text-sm font-semibold">Conversion directions</h3><div class="overflow-x-auto"><table class="w-full min-w-[50rem] text-left text-sm"><thead class="bg-muted/50 text-xs text-muted-foreground"><tr><th class="px-3 py-2.5">From</th><th class="px-3 py-2.5">To stock UOM</th><th class="px-3 py-2.5">Category</th><th class="px-3 py-2.5">Factor</th><th class="px-3 py-2.5">Item reference</th></tr></thead><tbody class="divide-y"><?php if ($catalogConversions === []): ?><tr><td colspan="5" class="px-3 py-8 text-center text-muted-foreground"><?= ($catalogDirectories['uom_conversion_factor']['status'] ?? '') === 'AVAILABLE' ? 'No verified conversion rows are exposed by current items.' : 'UOM conversion records are unavailable from Inventory.' ?></td></tr><?php else: foreach ($catalogConversions as $conversion): ?><tr><td class="px-3 py-2.5 font-medium"><?= bx_h((string) $conversion['from_uom_code']) ?></td><td class="px-3 py-2.5"><?= bx_h((string) $conversion['to_uom_code']) ?></td><td class="px-3 py-2.5"><?= bx_h((string) $conversion['uom_category']) ?></td><td class="px-3 py-2.5 font-mono text-xs"><?= bx_h((string) $conversion['conversion_factor']) ?></td><td class="px-3 py-2.5 font-mono text-xs break-all"><?= bx_h((string) $conversion['item_key']) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
</div>
