<?php
declare(strict_types=1);

$commercialProjection = is_array($activeModuleData['commercial_projection'] ?? null) ? $activeModuleData['commercial_projection'] : [];
$commercialSources = is_array($commercialProjection['sources'] ?? null) ? $commercialProjection['sources'] : [];
$commercialDirectories = is_array($commercialProjection['directories'] ?? null) ? $commercialProjection['directories'] : yovel_admin_operations_commercial_empty_directories();
$commercialContexts = is_array($commercialProjection['contexts'] ?? null) ? $commercialProjection['contexts'] : ['customers' => [], 'items' => [], 'employees' => []];
ob_start();
?>
<div class="grid gap-2"><h3 class="text-sm font-semibold">Owner actions</h3><a class="inline-flex min-h-9 items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm font-medium hover:bg-muted/70" href="?view=accounting-finance&amp;section=dashboard"><span class="material-symbols-rounded text-base" aria-hidden="true">open_in_new</span>Open Finance setup</a><a class="inline-flex min-h-9 items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm font-medium hover:bg-muted/70" href="?view=sales-crm&amp;section=customers"><span class="material-symbols-rounded text-base" aria-hidden="true">open_in_new</span>Open Sales customers</a><a class="inline-flex min-h-9 items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm font-medium hover:bg-muted/70" href="?view=buying-procurement&amp;section=suppliers"><span class="material-symbols-rounded text-base" aria-hidden="true">open_in_new</span>Open Buying suppliers</a><a class="inline-flex min-h-9 items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm font-medium hover:bg-muted/70" href="?view=inventory-warehouse&amp;section=items"><span class="material-symbols-rounded text-base" aria-hidden="true">open_in_new</span>Open Inventory items</a><a class="inline-flex min-h-9 items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm font-medium hover:bg-muted/70" href="?view=hr&amp;section=employee-profiles"><span class="material-symbols-rounded text-base" aria-hidden="true">open_in_new</span>Open HR employees</a></div>
<?php
$operationsSectionTools = (string) ob_get_clean();
$commercialGroups = [
    'Finance' => ['currency_exchange', 'party_type'],
    'Sales' => ['customer_group', 'quotation_lost_reason', 'quotation_lost_reason_detail', 'sales_partner', 'sales_person', 'target_detail', 'territory'],
    'Buying and trade terms' => ['supplier_group', 'incoterm', 'terms_and_conditions'],
];
?>
<div class="grid gap-6" data-operations-commercial>
    <div><h2 class="text-base font-semibold">Commercial and trading masters</h2><p class="mt-1 text-sm leading-6 text-muted-foreground">Read-only owner projections preserve verified fields and name every unavailable dependency. Authoritative changes remain in their source modules.</p></div>
    <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3" data-commercial-sources><?php foreach ($commercialSources as $source): ?><div class="rounded-md bg-muted/40 p-3"><div class="grid gap-1"><h3 class="text-sm font-semibold"><?= bx_h((string) ($source['owner'] ?? 'Owner')) ?></h3><span class="break-all text-xs font-medium"><?= bx_h((string) ($source['status'] ?? 'UNAVAILABLE_DEPENDENCY')) ?></span></div><p class="mt-1 break-all text-xs text-muted-foreground"><?= bx_h((string) ($source['service'] ?? 'Service unavailable')) ?></p><?php if (($source['message'] ?? '') !== ''): ?><p role="status" class="mt-2 text-xs leading-5 text-muted-foreground"><?= bx_h((string) $source['message']) ?> This source is non-blocking.</p><?php endif; ?></div><?php endforeach; ?></div>
    <?php foreach ($commercialGroups as $groupLabel => $directoryKeys): ?>
        <section class="grid gap-3" aria-labelledby="commercial-<?= bx_h(yovel_admin_slug($groupLabel)) ?>"><div><h3 id="commercial-<?= bx_h(yovel_admin_slug($groupLabel)) ?>" class="text-sm font-semibold"><?= bx_h($groupLabel) ?></h3></div><div class="grid gap-3 sm:grid-cols-2"><?php foreach ($directoryKeys as $directoryKey): $directory = $commercialDirectories[$directoryKey] ?? []; ?><div class="rounded-md bg-muted/40 p-3"><div class="grid gap-1"><h4 class="text-sm font-semibold"><?= bx_h((string) ($directory['label'] ?? ucwords(str_replace('_', ' ', $directoryKey)))) ?></h4><span class="break-all text-xs font-medium"><?= bx_h((string) ($directory['status'] ?? 'UNAVAILABLE_DEPENDENCY')) ?></span><p class="text-xs text-muted-foreground"><?= ($directory['records'] ?? []) === [] ? 'No verified records exposed' : count($directory['records']) . ' verified records' ?></p></div><p class="mt-2 text-xs leading-5 text-muted-foreground"><?= bx_h((string) ($directory['reason'] ?? 'Owner directory unavailable.')) ?></p><?php if (($directory['records'] ?? []) !== []): ?><dl class="mt-3 grid gap-2"><?php foreach ($directory['records'] as $record): ?><div class="rounded-md bg-background/60 p-2"><?php foreach ($record as $field => $value): ?><div class="grid grid-cols-[minmax(7rem,1fr)_minmax(0,2fr)] gap-2 text-xs"><dt class="font-medium"><?= bx_h(ucwords(str_replace('_', ' ', (string) $field))) ?></dt><dd class="break-all text-muted-foreground"><?= bx_h((string) $value) ?></dd></div><?php endforeach; ?></div><?php endforeach; ?></dl><?php elseif (($directory['unavailable_fields'] ?? []) !== []): ?><p class="mt-2 text-xs leading-5 text-muted-foreground">Unavailable fields: <?= bx_h(implode(', ', array_map('strval', $directory['unavailable_fields']))) ?>.</p><?php endif; ?></div><?php endforeach; ?></div></section>
    <?php endforeach; ?>
    <section class="grid gap-3" aria-labelledby="commercial-context-heading"><div><h3 id="commercial-context-heading" class="text-sm font-semibold">Verified context, not target records</h3><p class="mt-1 text-sm leading-6 text-muted-foreground">Customer, Inventory item, and HR employee identities can support future owner joins. They are not converted into Customer Groups or Target Details.</p></div><div class="grid gap-3 sm:grid-cols-3"><?php foreach (['customers' => 'Sales customers', 'items' => 'Inventory items', 'employees' => 'HR employees'] as $contextKey => $contextLabel): $contextRecords = $commercialContexts[$contextKey] ?? []; ?><div class="rounded-md bg-muted/40 p-3"><h4 class="text-sm font-semibold"><?= bx_h($contextLabel) ?></h4><p class="mt-1 text-xs text-muted-foreground"><?= $contextRecords === [] ? 'Source unavailable or no verified references' : count($contextRecords) . ' verified references' ?></p></div><?php endforeach; ?></div></section>
    <section class="grid gap-3" aria-labelledby="commercial-related-gaps"><div><h3 id="commercial-related-gaps" class="text-sm font-semibold">Related owner gaps</h3></div><div class="grid gap-3 sm:grid-cols-2"><?php foreach (($commercialProjection['related_owner_gaps'] ?? []) as $gap): ?><div role="status" class="rounded-md bg-muted/60 p-3"><div class="text-xs font-medium"><?= bx_h((string) ($gap['status'] ?? 'UNAVAILABLE_DEPENDENCY')) ?></div><p class="mt-2 text-sm leading-6 text-muted-foreground"><?= bx_h((string) ($gap['message'] ?? 'Owner contract unavailable.')) ?></p><p class="mt-1 text-xs leading-5 text-muted-foreground">Unavailable fields: <?= bx_h(implode(', ', array_map('strval', $gap['fields'] ?? []))) ?>.</p></div><?php endforeach; ?></div></section>
</div>
