<?php
declare(strict_types=1);

function yovel_admin_support_service_schema(): void
{
    static $ready = false;
    if ($ready) {
        return;
    }

    $db = bx_db();
    $statements = [
        "CREATE TABLE IF NOT EXISTS project_company_support_setting (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            support_setting_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            setting_version INT UNSIGNED NOT NULL DEFAULT 1,
            close_issue_after_days SMALLINT UNSIGNED NOT NULL DEFAULT 7,
            portal_enabled TINYINT(1) NOT NULL DEFAULT 1,
            track_service_level_agreement TINYINT(1) NOT NULL DEFAULT 0,
            allow_resetting_service_level_agreement TINYINT(1) NOT NULL DEFAULT 0,
            greeting_title VARCHAR(160) NOT NULL DEFAULT 'We are here to help',
            greeting_subtitle VARCHAR(255) NOT NULL DEFAULT 'Browse help topics or open a request',
            operations_search_contract VARCHAR(120) NOT NULL DEFAULT 'operations.support-search.v1',
            operations_job_contract VARCHAR(120) NOT NULL DEFAULT 'operations.enqueue-job.v1',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_setting_company (company_key_hash),
            INDEX idx_project_company_support_setting_updated (company_key_hash, updated_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_search_source (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            search_source_key CHAR(36) NOT NULL UNIQUE,
            support_setting_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            source_version INT UNSIGNED NOT NULL DEFAULT 1,
            source_name VARCHAR(160) NOT NULL,
            source_type ENUM('API','LINK') NOT NULL,
            base_url VARCHAR(2048) NULL,
            query_route VARCHAR(255) NULL,
            search_term_param_name VARCHAR(80) NULL,
            response_result_key_path VARCHAR(255) NULL,
            post_route VARCHAR(255) NULL,
            post_route_key_list VARCHAR(500) NULL,
            post_title_key VARCHAR(80) NULL,
            post_description_key VARCHAR(80) NULL,
            source_doctype VARCHAR(160) NULL,
            result_title_field VARCHAR(80) NULL,
            result_preview_field VARCHAR(80) NULL,
            result_route_field VARCHAR(80) NULL,
            source_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_search_name (company_key_hash, source_name),
            INDEX idx_project_company_support_search_setting (company_key_hash, support_setting_key),
            INDEX idx_project_company_support_search_status (company_key_hash, source_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_issue_priority (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            issue_priority_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            priority_version INT UNSIGNED NOT NULL DEFAULT 1,
            priority_name VARCHAR(120) NOT NULL,
            priority_description VARCHAR(500) NULL,
            priority_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_priority_name (company_key_hash, priority_name),
            INDEX idx_project_company_support_priority_status (company_key_hash, priority_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_issue_type (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            issue_type_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            issue_type_version INT UNSIGNED NOT NULL DEFAULT 1,
            issue_type_name VARCHAR(120) NOT NULL,
            issue_type_description VARCHAR(500) NULL,
            issue_type_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_issue_type_name (company_key_hash, issue_type_name),
            INDEX idx_project_company_support_issue_type_status (company_key_hash, issue_type_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_issue (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            issue_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            issue_code VARCHAR(80) NOT NULL,
            issue_version INT UNSIGNED NOT NULL DEFAULT 1,
            form_schema_checksum CHAR(64) NOT NULL,
            subject VARCHAR(255) NOT NULL,
            description LONGTEXT NULL,
            issue_status ENUM('OPEN','REPLIED','ON_HOLD','RESOLVED','CLOSED') NOT NULL DEFAULT 'OPEN',
            issue_priority_key CHAR(36) NULL,
            issue_type_key CHAR(36) NULL,
            customer_key TEXT NULL,
            customer_key_hash CHAR(64) NULL,
            customer_code_snapshot VARCHAR(160) NULL,
            customer_name_snapshot VARCHAR(255) NULL,
            project_key TEXT NULL,
            project_key_hash CHAR(64) NULL,
            project_code_snapshot VARCHAR(160) NULL,
            project_name_snapshot VARCHAR(255) NULL,
            raised_by VARCHAR(190) NULL,
            assigned_admin_key CHAR(36) NULL,
            service_level_agreement_key CHAR(36) NULL,
            response_by DATETIME NULL,
            first_responded_on DATETIME NULL,
            first_response_seconds BIGINT UNSIGNED NULL,
            resolution_by DATETIME NULL,
            resolution_date DATETIME NULL,
            on_hold_since DATETIME NULL,
            total_hold_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0,
            sla_resolution_remaining_seconds BIGINT UNSIGNED NULL,
            agreement_status ENUM('FIRST_RESPONSE_DUE','RESOLUTION_DUE','FULFILLED','FAILED') NULL,
            via_customer_portal TINYINT(1) NOT NULL DEFAULT 0,
            opened_at DATETIME NOT NULL,
            archived_at DATETIME NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_issue_code (company_key_hash, issue_code),
            INDEX idx_project_company_support_issue_status (company_key_hash, issue_status, opened_at),
            INDEX idx_project_company_support_issue_priority (company_key_hash, issue_priority_key),
            INDEX idx_project_company_support_issue_customer (company_key_hash, customer_key_hash),
            INDEX idx_project_company_support_issue_project (company_key_hash, project_key_hash),
            INDEX idx_project_company_support_issue_sla (company_key_hash, service_level_agreement_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_issue_event (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            issue_event_key CHAR(36) NOT NULL UNIQUE,
            issue_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            event_type VARCHAR(80) NOT NULL,
            previous_status VARCHAR(40) NULL,
            next_status VARCHAR(40) NULL,
            external_event_key TEXT NULL,
            external_event_key_hash CHAR(64) NULL,
            event_payload LONGTEXT NULL,
            occurred_at DATETIME NOT NULL,
            created_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_project_company_support_issue_event_issue (company_key_hash, issue_key, occurred_at),
            INDEX idx_project_company_support_issue_event_external (company_key_hash, external_event_key_hash)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_sla (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            service_level_agreement_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            sla_code VARCHAR(120) NOT NULL,
            service_level_name VARCHAR(160) NOT NULL,
            sla_version INT UNSIGNED NOT NULL DEFAULT 1,
            form_schema_checksum CHAR(64) NOT NULL,
            document_type VARCHAR(120) NOT NULL DEFAULT 'ISSUE',
            timezone_name VARCHAR(64) NOT NULL DEFAULT 'UTC',
            entity_type ENUM('NONE','CUSTOMER','CUSTOMER_GROUP','TERRITORY') NOT NULL DEFAULT 'NONE',
            entity_key TEXT NULL,
            entity_key_hash CHAR(64) NULL,
            entity_name_snapshot VARCHAR(255) NULL,
            start_date DATE NULL,
            end_date DATE NULL,
            calendar_contract VARCHAR(120) NOT NULL DEFAULT 'operations.calendar-holiday-dates.v1',
            calendar_key TEXT NULL,
            is_default TINYINT(1) NOT NULL DEFAULT 0,
            enabled TINYINT(1) NOT NULL DEFAULT 1,
            apply_for_resolution TINYINT(1) NOT NULL DEFAULT 1,
            condition_json LONGTEXT NULL,
            sla_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_sla_code (company_key_hash, sla_code),
            INDEX idx_project_company_support_sla_status (company_key_hash, sla_status, enabled),
            INDEX idx_project_company_support_sla_entity (company_key_hash, entity_key_hash)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_sla_service_day (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            sla_service_day_key CHAR(36) NOT NULL UNIQUE,
            service_level_agreement_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            weekday TINYINT UNSIGNED NOT NULL,
            start_time TIME NOT NULL,
            end_time TIME NOT NULL,
            sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_sla_day (company_key_hash, service_level_agreement_key, weekday),
            INDEX idx_project_company_support_sla_day_parent (company_key_hash, service_level_agreement_key, sort_order)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_sla_priority (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            sla_priority_key CHAR(36) NOT NULL UNIQUE,
            service_level_agreement_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            issue_priority_key CHAR(36) NOT NULL,
            response_seconds BIGINT UNSIGNED NOT NULL,
            resolution_seconds BIGINT UNSIGNED NULL,
            is_default TINYINT(1) NOT NULL DEFAULT 0,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_sla_priority (company_key_hash, service_level_agreement_key, issue_priority_key),
            INDEX idx_project_company_support_sla_priority_parent (company_key_hash, service_level_agreement_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_sla_pause_status (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            sla_pause_status_key CHAR(36) NOT NULL UNIQUE,
            service_level_agreement_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            issue_status VARCHAR(40) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_sla_pause (company_key_hash, service_level_agreement_key, issue_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_sla_fulfilled_status (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            sla_fulfilled_status_key CHAR(36) NOT NULL UNIQUE,
            service_level_agreement_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            issue_status VARCHAR(40) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_sla_fulfilled (company_key_hash, service_level_agreement_key, issue_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_warranty_claim (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            warranty_claim_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            claim_code VARCHAR(80) NOT NULL,
            claim_version INT UNSIGNED NOT NULL DEFAULT 1,
            claim_status ENUM('OPEN','WORK_IN_PROGRESS','CLOSED','CANCELLED') NOT NULL DEFAULT 'OPEN',
            complaint_date DATE NOT NULL,
            complaint LONGTEXT NOT NULL,
            customer_key TEXT NOT NULL,
            customer_key_hash CHAR(64) NOT NULL,
            customer_code_snapshot VARCHAR(160) NULL,
            customer_name_snapshot VARCHAR(255) NOT NULL,
            item_key TEXT NULL,
            item_key_hash CHAR(64) NULL,
            item_code_snapshot VARCHAR(160) NULL,
            item_name_snapshot VARCHAR(255) NULL,
            serial_key TEXT NULL,
            serial_key_hash CHAR(64) NULL,
            serial_snapshot VARCHAR(255) NULL,
            asset_key TEXT NULL,
            asset_key_hash CHAR(64) NULL,
            warranty_status VARCHAR(40) NULL,
            warranty_expiry_date DATE NULL,
            service_address TEXT NULL,
            resolution_details LONGTEXT NULL,
            resolution_date DATETIME NULL,
            resolved_by_admin_key CHAR(36) NULL,
            project_service_work_key TEXT NULL,
            project_service_work_key_hash CHAR(64) NULL,
            handoff_idempotency_key CHAR(36) NULL,
            archived_at DATETIME NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_warranty_code (company_key_hash, claim_code),
            UNIQUE KEY uq_project_company_support_warranty_handoff (company_key_hash, handoff_idempotency_key),
            INDEX idx_project_company_support_warranty_status (company_key_hash, claim_status),
            INDEX idx_project_company_support_warranty_customer (company_key_hash, customer_key_hash)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_telephony_call_type (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            telephony_call_type_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            call_type_name VARCHAR(120) NOT NULL,
            call_type_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_call_type_name (company_key_hash, call_type_name)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_incoming_call_setting (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            incoming_call_setting_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            setting_version INT UNSIGNED NOT NULL DEFAULT 1,
            provider_key VARCHAR(120) NOT NULL,
            provider_contract VARCHAR(120) NOT NULL DEFAULT 'operations.telephony-provider.v1',
            call_routing ENUM('SEQUENTIAL','SIMULTANEOUS') NOT NULL DEFAULT 'SEQUENTIAL',
            greeting_message VARCHAR(500) NULL,
            agent_busy_message VARCHAR(500) NULL,
            agent_unavailable_message VARCHAR(500) NULL,
            setting_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_incoming_provider (company_key_hash, provider_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_incoming_call_schedule (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            incoming_call_schedule_key CHAR(36) NOT NULL UNIQUE,
            incoming_call_setting_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            weekday TINYINT UNSIGNED NOT NULL,
            from_time TIME NOT NULL,
            to_time TIME NOT NULL,
            employee_group_key TEXT NOT NULL,
            employee_group_key_hash CHAR(64) NOT NULL,
            employee_group_name_snapshot VARCHAR(255) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_project_company_support_call_schedule_parent (company_key_hash, incoming_call_setting_key, weekday)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_voice_call_setting (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            voice_call_setting_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            user_key TEXT NOT NULL,
            user_key_hash CHAR(64) NOT NULL,
            setting_version INT UNSIGNED NOT NULL DEFAULT 1,
            greeting_message VARCHAR(500) NULL,
            agent_busy_message VARCHAR(500) NULL,
            agent_unavailable_message VARCHAR(500) NULL,
            receiving_device ENUM('COMPUTER','PHONE') NOT NULL DEFAULT 'COMPUTER',
            setting_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_voice_user (company_key_hash, user_key_hash)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_call_log (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            call_log_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            provider_key VARCHAR(120) NOT NULL,
            provider_call_id VARCHAR(255) NOT NULL,
            call_version INT UNSIGNED NOT NULL DEFAULT 1,
            call_direction ENUM('INCOMING','OUTGOING') NOT NULL,
            call_status ENUM('RINGING','IN_PROGRESS','COMPLETED','FAILED','BUSY','NO_ANSWER','QUEUED','CANCELLED') NOT NULL,
            from_value VARCHAR(255) NULL,
            to_value VARCHAR(255) NULL,
            normalized_from VARCHAR(80) NULL,
            normalized_to VARCHAR(80) NULL,
            medium VARCHAR(80) NULL,
            started_at DATETIME NULL,
            ended_at DATETIME NULL,
            duration_seconds BIGINT UNSIGNED NULL,
            recording_url VARCHAR(2048) NULL,
            summary TEXT NULL,
            telephony_call_type_key CHAR(36) NULL,
            received_by_employee_key TEXT NULL,
            received_by_employee_key_hash CHAR(64) NULL,
            received_by_name_snapshot VARCHAR(255) NULL,
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_provider_call (company_key_hash, provider_key, provider_call_id),
            INDEX idx_project_company_support_call_status (company_key_hash, call_status, started_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_support_call_log_link (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            call_log_link_key CHAR(36) NOT NULL UNIQUE,
            call_log_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            owner_module VARCHAR(80) NOT NULL,
            record_type VARCHAR(80) NOT NULL,
            record_key TEXT NOT NULL,
            record_key_hash CHAR(64) NOT NULL,
            record_label_snapshot VARCHAR(255) NULL,
            created_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_support_call_link (company_key_hash, call_log_key, owner_module, record_type, record_key_hash),
            INDEX idx_project_company_support_call_link_reference (company_key_hash, owner_module, record_type, record_key_hash)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ];

    foreach ($statements as $statement) {
        yovel_admin_db_execute($db, $statement, [], 'Support / Service schema update');
    }

    $columns = [
        ['project_company_support_issue_priority', 'priority_version', 'INT UNSIGNED NOT NULL DEFAULT 1 AFTER company_key_hash'],
        ['project_company_support_issue_type', 'issue_type_version', 'INT UNSIGNED NOT NULL DEFAULT 1 AFTER company_key_hash'],
        ['project_company_support_issue', 'form_schema_checksum', "CHAR(64) NOT NULL DEFAULT '' AFTER issue_version"],
        ['project_company_support_issue', 'sla_resolution_remaining_seconds', 'BIGINT UNSIGNED NULL AFTER total_hold_seconds'],
        ['project_company_support_sla', 'form_schema_checksum', "CHAR(64) NOT NULL DEFAULT '' AFTER sla_version"],
        ['project_company_support_sla', 'timezone_name', "VARCHAR(64) NOT NULL DEFAULT 'UTC' AFTER document_type"],
    ];
    foreach ($columns as [$table, $column, $definition]) {
        $exists = (int) $db->GetOne(
            'SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?',
            [BUILDERX_DB_NAME, $table, $column]
        );
        if ($exists === 0) {
            yovel_admin_db_execute(
                $db,
                "ALTER TABLE {$table} ADD COLUMN {$column} {$definition}",
                [],
                'Support / Service schema migration'
            );
        }
    }
    $ready = true;
}
