<?php
declare(strict_types=1);

function yovel_admin_assets_maintenance_schema(): void
{
    $db = bx_db();
    $statements = [
        "CREATE TABLE IF NOT EXISTS project_company_asset_form (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            form_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            target_section VARCHAR(80) NOT NULL,
            record_type VARCHAR(80) NOT NULL,
            form_title VARCHAR(180) NOT NULL,
            form_description TEXT NOT NULL,
            form_status ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            current_version_key CHAR(36) NOT NULL,
            published_version_key CHAR(36) NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_form_title (company_key_hash, target_section, form_title),
            INDEX idx_project_company_asset_form_scope (company_key_hash, target_section, form_status),
            INDEX idx_project_company_asset_form_current (company_key_hash, current_version_key),
            INDEX idx_project_company_asset_form_published (company_key_hash, published_version_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_form_version (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            form_version_key CHAR(36) NOT NULL UNIQUE,
            form_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            target_section VARCHAR(80) NOT NULL,
            record_type VARCHAR(80) NOT NULL,
            form_title VARCHAR(180) NOT NULL,
            form_description TEXT NOT NULL,
            version_number INT UNSIGNED NOT NULL,
            version_status ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            schema_json LONGTEXT NOT NULL,
            schema_checksum CHAR(64) NOT NULL,
            version_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            published_by_admin_key VARCHAR(191) NULL,
            published_at TIMESTAMP NULL,
            archived_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_form_version (company_key_hash, form_key, version_number),
            UNIQUE KEY uq_project_company_asset_form_version_checksum (company_key_hash, form_key, version_checksum),
            INDEX idx_project_company_asset_form_version_scope (company_key_hash, form_key, version_status, version_number)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_form_submission (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            submission_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            form_key CHAR(36) NOT NULL,
            form_version_key CHAR(36) NOT NULL,
            target_section VARCHAR(80) NOT NULL,
            record_type VARCHAR(80) NOT NULL,
            subject_owner_key VARCHAR(1500) NULL,
            submission_status ENUM('SUBMITTED','ARCHIVED') NOT NULL DEFAULT 'SUBMITTED',
            values_json LONGTEXT NOT NULL,
            values_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_project_company_asset_submission_form (company_key_hash, form_key, form_version_key, submission_status),
            INDEX idx_project_company_asset_submission_subject (company_key_hash, subject_owner_key(191), submission_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_form_audit (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            audit_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            form_key CHAR(36) NOT NULL,
            form_version_key CHAR(36) NULL,
            submission_key CHAR(36) NULL,
            audit_action VARCHAR(40) NOT NULL,
            details_json LONGTEXT NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_project_company_asset_form_audit_scope (company_key_hash, form_key, created_at),
            INDEX idx_project_company_asset_form_audit_version (company_key_hash, form_version_key),
            INDEX idx_project_company_asset_form_audit_submission (company_key_hash, submission_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_location (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            location_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            location_code VARCHAR(80) NOT NULL,
            location_name VARCHAR(180) NOT NULL,
            parent_location_key CHAR(36) NULL,
            location_path TEXT NOT NULL,
            location_status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_location_code (company_key_hash, location_code),
            INDEX idx_project_company_asset_location_parent (company_key_hash, parent_location_key, location_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_linked_location (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            linked_location_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            location_key CHAR(36) NOT NULL,
            target_location_key CHAR(36) NOT NULL,
            link_status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
            immutable_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_linked_location (company_key_hash, location_key, target_location_key),
            INDEX idx_project_company_asset_linked_target (company_key_hash, target_location_key, link_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_category (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            category_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            category_code VARCHAR(80) NOT NULL,
            category_name VARCHAR(180) NOT NULL,
            category_status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_category_code (company_key_hash, category_code),
            INDEX idx_project_company_asset_category_scope (company_key_hash, category_status, category_name)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_category_account (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            category_account_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            category_key CHAR(36) NOT NULL,
            account_role ENUM('ASSET','ACCUMULATED_DEPRECIATION','DEPRECIATION_EXPENSE','GAIN_LOSS') NOT NULL,
            account_owner_key VARCHAR(1500) NOT NULL,
            account_label_snapshot VARCHAR(180) NOT NULL,
            immutable_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_category_account (company_key_hash, category_key, account_role),
            INDEX idx_project_company_asset_category_account_owner (company_key_hash, account_owner_key(191))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            asset_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            asset_code VARCHAR(100) NOT NULL,
            asset_name VARCHAR(180) NOT NULL,
            item_owner_key VARCHAR(1500) NOT NULL,
            item_code_snapshot VARCHAR(100) NOT NULL,
            item_name_snapshot VARCHAR(180) NOT NULL,
            category_key CHAR(36) NOT NULL,
            category_name_snapshot VARCHAR(180) NOT NULL,
            location_key CHAR(36) NOT NULL,
            location_name_snapshot VARCHAR(180) NOT NULL,
            custodian_employee_key VARCHAR(1500) NULL,
            custodian_code_snapshot VARCHAR(100) NOT NULL DEFAULT '',
            custodian_name_snapshot VARCHAR(180) NOT NULL DEFAULT '',
            purchase_reference_type ENUM('NONE','PURCHASE_RECEIPT','PURCHASE_INVOICE','OPENING') NOT NULL DEFAULT 'NONE',
            purchase_reference_key VARCHAR(1500) NULL,
            purchase_quantity DECIMAL(20,6) NOT NULL DEFAULT 1.000000,
            gross_purchase_amount DECIMAL(20,6) NOT NULL DEFAULT 0.000000,
            acquisition_date DATE NOT NULL,
            available_for_use_date DATE NOT NULL,
            lifecycle_status ENUM('AVAILABLE','IN_USE','IDLE','SOLD','SCRAPPED') NOT NULL DEFAULT 'AVAILABLE',
            document_status ENUM('DRAFT','SUBMITTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            amended_from_asset_key CHAR(36) NULL,
            amended_by_asset_key CHAR(36) NULL,
            cancellation_reason VARCHAR(500) NOT NULL DEFAULT '',
            notes TEXT NOT NULL,
            immutable_reference_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            submitted_by_admin_key VARCHAR(191) NULL,
            cancelled_by_admin_key VARCHAR(191) NULL,
            submitted_at TIMESTAMP NULL,
            cancelled_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_code (company_key_hash, asset_code),
            INDEX idx_project_company_asset_scope (company_key_hash, document_status, lifecycle_status),
            INDEX idx_project_company_asset_item (company_key_hash, item_owner_key(191)),
            INDEX idx_project_company_asset_location (company_key_hash, location_key, document_status),
            INDEX idx_project_company_asset_custodian (company_key_hash, custodian_employee_key(191)),
            INDEX idx_project_company_asset_amendment (company_key_hash, amended_from_asset_key, amended_by_asset_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_activity (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            activity_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            asset_key CHAR(36) NOT NULL,
            movement_key CHAR(36) NULL,
            activity_type VARCHAR(40) NOT NULL,
            activity_at DATETIME NOT NULL,
            from_location_key CHAR(36) NULL,
            to_location_key CHAR(36) NULL,
            from_custodian_employee_key VARCHAR(1500) NULL,
            to_custodian_employee_key VARCHAR(1500) NULL,
            details_json LONGTEXT NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_project_company_asset_activity_timeline (company_key_hash, asset_key, activity_at, x_id),
            INDEX idx_project_company_asset_activity_movement (company_key_hash, movement_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_movement (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            movement_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            movement_code VARCHAR(100) NOT NULL,
            movement_type ENUM('TRANSFER','CUSTODY','LOCATION') NOT NULL DEFAULT 'TRANSFER',
            posting_at DATETIME NOT NULL,
            to_location_key CHAR(36) NULL,
            to_location_name_snapshot VARCHAR(180) NOT NULL DEFAULT '',
            to_custodian_employee_key VARCHAR(1500) NULL,
            to_custodian_code_snapshot VARCHAR(100) NOT NULL DEFAULT '',
            to_custodian_name_snapshot VARCHAR(180) NOT NULL DEFAULT '',
            reason VARCHAR(500) NOT NULL,
            document_status ENUM('DRAFT','SUBMITTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            cancellation_reason VARCHAR(500) NOT NULL DEFAULT '',
            immutable_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            submitted_by_admin_key VARCHAR(191) NULL,
            cancelled_by_admin_key VARCHAR(191) NULL,
            submitted_at TIMESTAMP NULL,
            cancelled_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_movement_code (company_key_hash, movement_code),
            INDEX idx_project_company_asset_movement_scope (company_key_hash, document_status, posting_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_movement_item (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            movement_item_key CHAR(36) NOT NULL UNIQUE,
            movement_key CHAR(36) NOT NULL,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            asset_key CHAR(36) NOT NULL,
            asset_code_snapshot VARCHAR(100) NOT NULL,
            from_location_key CHAR(36) NOT NULL,
            from_location_name_snapshot VARCHAR(180) NOT NULL,
            from_custodian_employee_key VARCHAR(1500) NULL,
            from_custodian_code_snapshot VARCHAR(100) NOT NULL DEFAULT '',
            from_custodian_name_snapshot VARCHAR(180) NOT NULL DEFAULT '',
            immutable_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_movement_item (company_key_hash, movement_key, asset_key),
            INDEX idx_project_company_asset_movement_asset (company_key_hash, asset_key, movement_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_finance_book (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            finance_book_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            asset_key CHAR(36) NOT NULL,
            book_code VARCHAR(80) NOT NULL,
            book_name VARCHAR(180) NOT NULL,
            depreciation_method ENUM('STRAIGHT_LINE','DOUBLE_DECLINING','WRITTEN_DOWN_VALUE','MANUAL') NOT NULL,
            gross_amount_minor BIGINT UNSIGNED NOT NULL,
            salvage_value_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
            opening_depreciation_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
            period_count SMALLINT UNSIGNED NOT NULL,
            frequency_months SMALLINT UNSIGNED NOT NULL,
            daily_prorata TINYINT(1) NOT NULL DEFAULT 0,
            rate_basis_points INT UNSIGNED NOT NULL DEFAULT 0,
            book_status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
            immutable_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_finance_book_code (company_key_hash, asset_key, book_code),
            INDEX idx_project_company_asset_finance_book_scope (company_key_hash, asset_key, book_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_depreciation_schedule (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            schedule_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            asset_key CHAR(36) NOT NULL,
            finance_book_key CHAR(36) NOT NULL,
            schedule_version SMALLINT UNSIGNED NOT NULL,
            depreciation_method ENUM('STRAIGHT_LINE','DOUBLE_DECLINING','WRITTEN_DOWN_VALUE','MANUAL') NOT NULL,
            start_date DATE NOT NULL,
            posting_through_date DATE NOT NULL,
            period_count SMALLINT UNSIGNED NOT NULL,
            frequency_months SMALLINT UNSIGNED NOT NULL,
            daily_prorata TINYINT(1) NOT NULL DEFAULT 0,
            rate_basis_points INT UNSIGNED NOT NULL DEFAULT 0,
            gross_amount_minor BIGINT UNSIGNED NOT NULL,
            salvage_value_minor BIGINT UNSIGNED NOT NULL,
            opening_depreciation_minor BIGINT UNSIGNED NOT NULL,
            total_depreciation_minor BIGINT UNSIGNED NOT NULL,
            calculation_checksum CHAR(64) NOT NULL,
            document_status ENUM('DRAFT','SUBMITTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            lifecycle_status ENUM('ACTIVE','SUPERSEDED') NOT NULL DEFAULT 'ACTIVE',
            replacement_of_schedule_key CHAR(36) NULL,
            replaced_by_schedule_key CHAR(36) NULL,
            cancellation_reason VARCHAR(500) NOT NULL DEFAULT '',
            notes TEXT NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            submitted_by_admin_key VARCHAR(191) NULL,
            cancelled_by_admin_key VARCHAR(191) NULL,
            submitted_at TIMESTAMP NULL,
            cancelled_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_schedule_version (company_key_hash, finance_book_key, schedule_version),
            INDEX idx_project_company_asset_schedule_scope (company_key_hash, asset_key, document_status, lifecycle_status),
            INDEX idx_project_company_asset_schedule_replacement (company_key_hash, replacement_of_schedule_key, replaced_by_schedule_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_depreciation_line (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            depreciation_line_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            schedule_key CHAR(36) NOT NULL,
            line_no SMALLINT UNSIGNED NOT NULL,
            posting_date DATE NOT NULL,
            opening_value_minor BIGINT UNSIGNED NOT NULL,
            depreciation_amount_minor BIGINT UNSIGNED NOT NULL,
            accumulated_depreciation_minor BIGINT UNSIGNED NOT NULL,
            closing_value_minor BIGINT UNSIGNED NOT NULL,
            posting_status ENUM('PENDING','POSTED','REVERSED') NOT NULL DEFAULT 'PENDING',
            finance_transaction_key CHAR(36) NULL,
            finance_reversal_transaction_key CHAR(36) NULL,
            finance_calculation_hash CHAR(64) NULL,
            immutable_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            posted_at TIMESTAMP NULL,
            reversed_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_depreciation_line (company_key_hash, schedule_key, line_no),
            UNIQUE KEY uq_project_company_asset_depreciation_date (company_key_hash, schedule_key, posting_date),
            INDEX idx_project_company_asset_depreciation_due (company_key_hash, schedule_key, posting_status, posting_date)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_shift_factor (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            shift_factor_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            factor_code VARCHAR(80) NOT NULL,
            factor_name VARCHAR(180) NOT NULL,
            multiplier_basis_points INT UNSIGNED NOT NULL,
            factor_status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
            immutable_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_shift_factor_code (company_key_hash, factor_code),
            INDEX idx_project_company_asset_shift_factor_scope (company_key_hash, factor_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_shift_allocation (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            shift_allocation_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            asset_key CHAR(36) NOT NULL,
            finance_book_key CHAR(36) NOT NULL,
            schedule_key CHAR(36) NOT NULL,
            shift_factor_key CHAR(36) NOT NULL,
            effective_date DATE NOT NULL,
            reason VARCHAR(500) NOT NULL,
            document_status ENUM('DRAFT','SUBMITTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            replacement_schedule_key CHAR(36) NULL,
            immutable_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            submitted_by_admin_key VARCHAR(191) NULL,
            submitted_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_asset_shift_allocation (company_key_hash, schedule_key, effective_date),
            INDEX idx_project_company_asset_shift_allocation_scope (company_key_hash, asset_key, document_status, effective_date)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_value_adjustment (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            adjustment_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            asset_key CHAR(36) NOT NULL,
            adjustment_type ENUM('INCREASE','DECREASE') NOT NULL,
            posting_date DATE NOT NULL,
            amount_minor BIGINT UNSIGNED NOT NULL,
            reason VARCHAR(500) NOT NULL,
            document_status ENUM('DRAFT','SUBMITTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            finance_transaction_key CHAR(36) NULL,
            finance_reversal_transaction_key CHAR(36) NULL,
            finance_calculation_hash CHAR(64) NULL,
            cancellation_reason VARCHAR(500) NOT NULL DEFAULT '',
            immutable_checksum CHAR(64) NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            updated_by_admin_key VARCHAR(191) NOT NULL,
            submitted_by_admin_key VARCHAR(191) NULL,
            cancelled_by_admin_key VARCHAR(191) NULL,
            submitted_at TIMESTAMP NULL,
            cancelled_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_project_company_asset_adjustment_scope (company_key_hash, asset_key, document_status, posting_date),
            INDEX idx_project_company_asset_adjustment_finance (company_key_hash, finance_transaction_key, finance_reversal_transaction_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_asset_lifecycle_audit (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            audit_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            target_kind ENUM('LOCATION','CATEGORY','ASSET','MOVEMENT') NOT NULL,
            target_key CHAR(36) NOT NULL,
            audit_action VARCHAR(40) NOT NULL,
            details_json LONGTEXT NOT NULL,
            created_by_admin_key VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_project_company_asset_lifecycle_audit_scope (company_key_hash, target_kind, target_key, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ];

    foreach ($statements as $statement) {
        yovel_admin_assets_execute($db, $statement, [], 'Assets / Maintenance schema update');
    }
}
