<?php
declare(strict_types=1);

function yovel_admin_buying_schema(): void
{
    $db = bx_db();
    $statements = [
        "CREATE TABLE IF NOT EXISTS project_company_buying_setting (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            buying_setting_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            supplier_naming_mode ENUM('SUPPLIER_NAME','NAMING_SERIES','AUTO_NAME') NOT NULL DEFAULT 'NAMING_SERIES',
            default_supplier_group_key CHAR(36) NULL,
            default_buying_price_list_key CHAR(36) NULL,
            purchase_order_required TINYINT(1) NOT NULL DEFAULT 0,
            purchase_receipt_required TINYINT(1) NOT NULL DEFAULT 0,
            maintain_same_rate TINYINT(1) NOT NULL DEFAULT 0,
            maintain_same_rate_action ENUM('STOP','WARN') NOT NULL DEFAULT 'STOP',
            over_order_allowance DECIMAL(9,4) NOT NULL DEFAULT 0,
            over_transfer_allowance DECIMAL(9,4) NOT NULL DEFAULT 0,
            allow_zero_qty_purchase_order TINYINT(1) NOT NULL DEFAULT 0,
            allow_zero_qty_rfq TINYINT(1) NOT NULL DEFAULT 0,
            allow_zero_qty_supplier_quotation TINYINT(1) NOT NULL DEFAULT 0,
            setting_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_setting_company (company_key_hash),
            INDEX idx_project_company_buying_setting_status (company_key_hash, setting_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_number_series (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            number_series_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            series_code VARCHAR(80) NOT NULL,
            fiscal_year SMALLINT UNSIGNED NOT NULL,
            prefix VARCHAR(30) NOT NULL,
            next_number BIGINT UNSIGNED NOT NULL DEFAULT 1,
            padding TINYINT UNSIGNED NOT NULL DEFAULT 5,
            series_status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_series (company_key_hash, series_code, fiscal_year),
            INDEX idx_project_company_buying_series_status (company_key_hash, series_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_supplier (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            supplier_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            supplier_code VARCHAR(80) NOT NULL,
            supplier_name VARCHAR(200) NOT NULL,
            supplier_type ENUM('COMPANY','INDIVIDUAL','PARTNERSHIP') NOT NULL DEFAULT 'COMPANY',
            supplier_group_key CHAR(36) NULL,
            country_key CHAR(36) NULL,
            default_currency VARCHAR(20) NULL,
            default_price_list_key CHAR(36) NULL,
            payment_terms_key CHAR(36) NULL,
            tax_id VARCHAR(80) NULL,
            language_code VARCHAR(20) NULL,
            email VARCHAR(190) NULL,
            phone VARCHAR(80) NULL,
            website VARCHAR(220) NULL,
            supplier_details TEXT NULL,
            is_transporter TINYINT(1) NOT NULL DEFAULT 0,
            is_internal_supplier TINYINT(1) NOT NULL DEFAULT 0,
            represents_company_key VARCHAR(1500) NULL,
            on_hold TINYINT(1) NOT NULL DEFAULT 0,
            hold_type ENUM('ALL','INVOICES','PAYMENTS') NULL,
            release_date DATE NULL,
            warn_rfqs TINYINT(1) NOT NULL DEFAULT 0,
            warn_purchase_orders TINYINT(1) NOT NULL DEFAULT 0,
            prevent_rfqs TINYINT(1) NOT NULL DEFAULT 0,
            prevent_purchase_orders TINYINT(1) NOT NULL DEFAULT 0,
            supplier_status ENUM('DRAFT','ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_supplier_code (company_key_hash, supplier_code),
            INDEX idx_project_company_buying_supplier_status (company_key_hash, supplier_status),
            INDEX idx_project_company_buying_supplier_name (company_key_hash, supplier_name)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_supplier_customer_number (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            supplier_customer_number_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            supplier_key CHAR(36) NOT NULL,
            related_company_key VARCHAR(1500) NOT NULL,
            customer_number VARCHAR(120) NOT NULL,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_supplier_customer (company_key_hash, supplier_key, related_company_key),
            INDEX idx_project_company_buying_supplier_customer_status (company_key_hash, row_status),
            INDEX idx_project_company_buying_supplier_customer_supplier (company_key_hash, supplier_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_supplier_company (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            supplier_company_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            supplier_key CHAR(36) NOT NULL,
            allowed_company_key VARCHAR(1500) NOT NULL,
            allowed_company_hash CHAR(64) NOT NULL,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_supplier_company (company_key_hash, supplier_key, allowed_company_hash),
            INDEX idx_project_company_buying_supplier_company_status (company_key_hash, row_status),
            INDEX idx_project_company_buying_supplier_company_supplier (company_key_hash, supplier_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_rfq (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            rfq_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            rfq_number VARCHAR(80) NOT NULL,
            transaction_date DATE NOT NULL,
            schedule_date DATE NULL,
            subject VARCHAR(220) NOT NULL,
            terms LONGTEXT NULL,
            message_for_supplier LONGTEXT NULL,
            source_opportunity_key CHAR(36) NULL,
            amended_from_key CHAR(36) NULL,
            document_status ENUM('DRAFT','SUBMITTED','CANCELLED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            revision_no INT UNSIGNED NOT NULL DEFAULT 1,
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            submitted_by_admin_key CHAR(36) NULL,
            cancelled_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            submitted_at TIMESTAMP NULL,
            cancelled_at TIMESTAMP NULL,
            UNIQUE KEY uq_project_company_buying_rfq_number (company_key_hash, rfq_number),
            INDEX idx_project_company_buying_rfq_status (company_key_hash, document_status),
            INDEX idx_project_company_buying_rfq_date (company_key_hash, transaction_date)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_rfq_supplier (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            rfq_supplier_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            rfq_key CHAR(36) NOT NULL,
            supplier_key CHAR(36) NOT NULL,
            contact_key CHAR(36) NULL,
            email VARCHAR(190) NULL,
            send_email TINYINT(1) NOT NULL DEFAULT 0,
            delivery_status ENUM('NOT_REQUESTED','PENDING','SENT','FAILED','RECEIVED') NOT NULL DEFAULT 'NOT_REQUESTED',
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_rfq_supplier (company_key_hash, rfq_key, supplier_key),
            INDEX idx_project_company_buying_rfq_supplier_status (company_key_hash, row_status),
            INDEX idx_project_company_buying_rfq_supplier_delivery (company_key_hash, delivery_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_rfq_item (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            rfq_item_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            rfq_key CHAR(36) NOT NULL,
            line_no INT UNSIGNED NOT NULL,
            inventory_item_key CHAR(36) NOT NULL,
            item_code_snapshot VARCHAR(120) NOT NULL,
            item_name_snapshot VARCHAR(220) NOT NULL,
            description TEXT NULL,
            quantity DECIMAL(18,6) NOT NULL,
            uom_key CHAR(36) NOT NULL,
            uom_snapshot VARCHAR(80) NOT NULL,
            schedule_date DATE NOT NULL,
            warehouse_key CHAR(36) NULL,
            material_request_key CHAR(36) NULL,
            material_request_item_key CHAR(36) NULL,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_rfq_item_line (company_key_hash, rfq_key, line_no),
            INDEX idx_project_company_buying_rfq_item_status (company_key_hash, row_status),
            INDEX idx_project_company_buying_rfq_item_source (company_key_hash, material_request_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_supplier_quotation (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            supplier_quotation_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            quotation_number VARCHAR(80) NOT NULL,
            supplier_reference VARCHAR(120) NULL,
            supplier_key CHAR(36) NOT NULL,
            rfq_key CHAR(36) NULL,
            transaction_date DATE NOT NULL,
            valid_until DATE NULL,
            currency VARCHAR(20) NOT NULL,
            conversion_rate DECIMAL(18,8) NOT NULL DEFAULT 1,
            net_total DECIMAL(18,6) NOT NULL DEFAULT 0,
            tax_total DECIMAL(18,6) NOT NULL DEFAULT 0,
            grand_total DECIMAL(18,6) NOT NULL DEFAULT 0,
            calculation_snapshot_json LONGTEXT NULL,
            amended_from_key CHAR(36) NULL,
            document_status ENUM('DRAFT','SUBMITTED','STOPPED','EXPIRED','CANCELLED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            revision_no INT UNSIGNED NOT NULL DEFAULT 1,
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            submitted_by_admin_key CHAR(36) NULL,
            cancelled_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            submitted_at TIMESTAMP NULL,
            cancelled_at TIMESTAMP NULL,
            UNIQUE KEY uq_project_company_buying_supplier_quotation_number (company_key_hash, quotation_number),
            INDEX idx_project_company_buying_supplier_quotation_status (company_key_hash, document_status),
            INDEX idx_project_company_buying_supplier_quotation_supplier (company_key_hash, supplier_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_supplier_quotation_item (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            supplier_quotation_item_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            supplier_quotation_key CHAR(36) NOT NULL,
            line_no INT UNSIGNED NOT NULL,
            inventory_item_key CHAR(36) NOT NULL,
            item_code_snapshot VARCHAR(120) NOT NULL,
            item_name_snapshot VARCHAR(220) NOT NULL,
            description TEXT NULL,
            quantity DECIMAL(18,6) NOT NULL,
            uom_key CHAR(36) NOT NULL,
            uom_snapshot VARCHAR(80) NOT NULL,
            rate DECIMAL(18,6) NOT NULL DEFAULT 0,
            discount_percentage DECIMAL(9,4) NOT NULL DEFAULT 0,
            net_amount DECIMAL(18,6) NOT NULL DEFAULT 0,
            expected_delivery_date DATE NULL,
            warehouse_key CHAR(36) NULL,
            rfq_item_key CHAR(36) NULL,
            material_request_key CHAR(36) NULL,
            material_request_item_key CHAR(36) NULL,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_supplier_quotation_item_line (company_key_hash, supplier_quotation_key, line_no),
            INDEX idx_project_company_buying_supplier_quotation_item_status (company_key_hash, row_status),
            INDEX idx_project_company_buying_supplier_quotation_item_source (company_key_hash, rfq_item_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_purchase_order (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            purchase_order_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            purchase_order_number VARCHAR(80) NOT NULL,
            supplier_key CHAR(36) NOT NULL,
            supplier_quotation_key CHAR(36) NULL,
            transaction_date DATE NOT NULL,
            schedule_date DATE NULL,
            currency VARCHAR(20) NOT NULL,
            conversion_rate DECIMAL(18,8) NOT NULL DEFAULT 1,
            net_total DECIMAL(18,6) NOT NULL DEFAULT 0,
            tax_total DECIMAL(18,6) NOT NULL DEFAULT 0,
            grand_total DECIMAL(18,6) NOT NULL DEFAULT 0,
            received_percentage DECIMAL(9,4) NOT NULL DEFAULT 0,
            billed_percentage DECIMAL(9,4) NOT NULL DEFAULT 0,
            calculation_snapshot_json LONGTEXT NULL,
            is_subcontracted TINYINT(1) NOT NULL DEFAULT 0,
            is_drop_ship TINYINT(1) NOT NULL DEFAULT 0,
            sales_order_key CHAR(36) NULL,
            amended_from_key CHAR(36) NULL,
            document_status ENUM('DRAFT','SUBMITTED','ON_HOLD','TO_RECEIVE_AND_BILL','TO_BILL','TO_RECEIVE','COMPLETED','CLOSED','CANCELLED','DELIVERED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            revision_no INT UNSIGNED NOT NULL DEFAULT 1,
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            submitted_by_admin_key CHAR(36) NULL,
            cancelled_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            submitted_at TIMESTAMP NULL,
            cancelled_at TIMESTAMP NULL,
            UNIQUE KEY uq_project_company_buying_purchase_order_number (company_key_hash, purchase_order_number),
            INDEX idx_project_company_buying_purchase_order_status (company_key_hash, document_status),
            INDEX idx_project_company_buying_purchase_order_supplier (company_key_hash, supplier_key),
            INDEX idx_project_company_buying_purchase_order_date (company_key_hash, transaction_date)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_purchase_order_item (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            purchase_order_item_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            purchase_order_key CHAR(36) NOT NULL,
            line_no INT UNSIGNED NOT NULL,
            inventory_item_key CHAR(36) NOT NULL,
            item_code_snapshot VARCHAR(120) NOT NULL,
            item_name_snapshot VARCHAR(220) NOT NULL,
            description TEXT NULL,
            quantity DECIMAL(18,6) NOT NULL,
            uom_key CHAR(36) NOT NULL,
            uom_snapshot VARCHAR(80) NOT NULL,
            rate DECIMAL(18,6) NOT NULL DEFAULT 0,
            net_amount DECIMAL(18,6) NOT NULL DEFAULT 0,
            schedule_date DATE NOT NULL,
            warehouse_key CHAR(36) NULL,
            material_request_key CHAR(36) NULL,
            material_request_item_key CHAR(36) NULL,
            received_quantity DECIMAL(18,6) NOT NULL DEFAULT 0,
            returned_quantity DECIMAL(18,6) NOT NULL DEFAULT 0,
            billed_amount DECIMAL(18,6) NOT NULL DEFAULT 0,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_purchase_order_item_line (company_key_hash, purchase_order_key, line_no),
            INDEX idx_project_company_buying_purchase_order_item_status (company_key_hash, row_status),
            INDEX idx_project_company_buying_purchase_order_item_source (company_key_hash, material_request_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_purchase_order_supplied_item (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            supplied_item_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            purchase_order_key CHAR(36) NOT NULL,
            purchase_order_item_key CHAR(36) NOT NULL,
            main_inventory_item_key CHAR(36) NOT NULL,
            raw_inventory_item_key CHAR(36) NOT NULL,
            required_quantity DECIMAL(18,6) NOT NULL DEFAULT 0,
            supplied_quantity DECIMAL(18,6) NOT NULL DEFAULT 0,
            consumed_quantity DECIMAL(18,6) NOT NULL DEFAULT 0,
            returned_quantity DECIMAL(18,6) NOT NULL DEFAULT 0,
            rate DECIMAL(18,6) NOT NULL DEFAULT 0,
            reserve_warehouse_key CHAR(36) NULL,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_purchase_order_supplied_item (company_key_hash, purchase_order_item_key, raw_inventory_item_key),
            INDEX idx_project_company_buying_purchase_order_supplied_status (company_key_hash, row_status),
            INDEX idx_project_company_buying_purchase_order_supplied_order (company_key_hash, purchase_order_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_handoff (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            handoff_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            handoff_type ENUM('INVENTORY_RECEIPT','FINANCE_INVOICE') NOT NULL,
            idempotency_key VARCHAR(160) NOT NULL,
            purchase_order_key CHAR(36) NOT NULL,
            owner_record_key CHAR(36) NULL,
            request_snapshot_json LONGTEXT NOT NULL,
            response_snapshot_json LONGTEXT NULL,
            handoff_status ENUM('PENDING','COMPLETED','FAILED','CANCELLED','ARCHIVED') NOT NULL DEFAULT 'PENDING',
            failure_message VARCHAR(500) NULL,
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_handoff_idempotency (company_key_hash, handoff_type, idempotency_key),
            INDEX idx_project_company_buying_handoff_status (company_key_hash, handoff_status),
            INDEX idx_project_company_buying_handoff_order (company_key_hash, purchase_order_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_scorecard_definition (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            scorecard_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            supplier_key CHAR(36) NOT NULL,
            period_type ENUM('WEEK','MONTH','YEAR') NOT NULL DEFAULT 'MONTH',
            weighting_expression VARCHAR(500) NOT NULL,
            scorecard_status ENUM('DRAFT','ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_scorecard_supplier (company_key_hash, supplier_key),
            INDEX idx_project_company_buying_scorecard_status (company_key_hash, scorecard_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_scorecard_criteria (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            scorecard_criteria_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            scorecard_key CHAR(36) NOT NULL,
            criteria_code VARCHAR(80) NOT NULL,
            criteria_name VARCHAR(160) NOT NULL,
            max_score DECIMAL(9,4) NOT NULL,
            weight_percentage DECIMAL(9,4) NOT NULL,
            formula_expression VARCHAR(500) NOT NULL,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_scorecard_criteria (company_key_hash, scorecard_key, criteria_code),
            INDEX idx_project_company_buying_scorecard_criteria_status (company_key_hash, row_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_scorecard_variable (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            scorecard_variable_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            scorecard_key CHAR(36) NOT NULL,
            variable_code VARCHAR(80) NOT NULL,
            variable_label VARCHAR(160) NOT NULL,
            metric_path VARCHAR(220) NOT NULL,
            description TEXT NULL,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_scorecard_variable (company_key_hash, scorecard_key, variable_code),
            INDEX idx_project_company_buying_scorecard_variable_status (company_key_hash, row_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_scorecard_standing (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            scorecard_standing_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            scorecard_key CHAR(36) NOT NULL,
            standing_code VARCHAR(80) NOT NULL,
            standing_name VARCHAR(160) NOT NULL,
            color_token VARCHAR(40) NOT NULL,
            minimum_score DECIMAL(9,4) NOT NULL,
            maximum_score DECIMAL(9,4) NOT NULL,
            warn_rfqs TINYINT(1) NOT NULL DEFAULT 0,
            warn_purchase_orders TINYINT(1) NOT NULL DEFAULT 0,
            prevent_rfqs TINYINT(1) NOT NULL DEFAULT 0,
            prevent_purchase_orders TINYINT(1) NOT NULL DEFAULT 0,
            notify_supplier TINYINT(1) NOT NULL DEFAULT 0,
            notify_employee TINYINT(1) NOT NULL DEFAULT 0,
            employee_key CHAR(36) NULL,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_scorecard_standing (company_key_hash, scorecard_key, standing_code),
            INDEX idx_project_company_buying_scorecard_standing_status (company_key_hash, row_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_scorecard_period (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            scorecard_period_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            scorecard_key CHAR(36) NOT NULL,
            supplier_key CHAR(36) NOT NULL,
            period_start DATE NOT NULL,
            period_end DATE NOT NULL,
            total_score DECIMAL(9,4) NOT NULL DEFAULT 0,
            standing_key CHAR(36) NULL,
            metric_snapshot_json LONGTEXT NOT NULL,
            period_status ENUM('DRAFT','CALCULATED','PUBLISHED','ARCHIVED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_scorecard_period (company_key_hash, scorecard_key, period_start, period_end),
            INDEX idx_project_company_buying_scorecard_period_status (company_key_hash, period_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_buying_scorecard_period_score (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            scorecard_period_score_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            scorecard_period_key CHAR(36) NOT NULL,
            scorecard_criteria_key CHAR(36) NOT NULL,
            criteria_score DECIMAL(9,4) NOT NULL,
            weighted_score DECIMAL(9,4) NOT NULL,
            variable_snapshot_json LONGTEXT NOT NULL,
            row_status ENUM('ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NULL,
            updated_by_admin_key CHAR(36) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_company_buying_scorecard_period_score (company_key_hash, scorecard_period_key, scorecard_criteria_key),
            INDEX idx_project_company_buying_scorecard_period_score_status (company_key_hash, row_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ];

    foreach ($statements as $statement) {
        yovel_admin_db_execute($db, $statement, [], 'Buying / Procurement schema update');
    }
}
