<?php
declare(strict_types=1);

function yovel_admin_projects_schema(): void
{
    static $ready = false;
    if ($ready) {
        return;
    }
    $db = bx_db();
    $statements = [
        "CREATE TABLE IF NOT EXISTS project_company_project_settings (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            project_settings_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            ignore_employee_time_overlap TINYINT(1) NOT NULL DEFAULT 0,
            fetch_timesheet_in_sales_invoice TINYINT(1) NOT NULL DEFAULT 0,
            settings_status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_settings_company (company_key_hash),
            INDEX idx_project_settings_status (company_key_hash, settings_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_type (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            project_type_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            project_type_code VARCHAR(80) NOT NULL,
            project_type_name VARCHAR(160) NOT NULL,
            project_type_status ENUM('ACTIVE','INACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_type_code (company_key_hash, project_type_code),
            INDEX idx_project_type_status (company_key_hash, project_type_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_task_type (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            task_type_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            task_type_code VARCHAR(80) NOT NULL,
            task_type_name VARCHAR(160) NOT NULL,
            task_type_status ENUM('ACTIVE','INACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_task_type_code (company_key_hash, task_type_code),
            INDEX idx_project_task_type_status (company_key_hash, task_type_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_activity_type (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            activity_type_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            activity_type_code VARCHAR(80) NOT NULL,
            activity_type_name VARCHAR(160) NOT NULL,
            activity_type_status ENUM('ACTIVE','INACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_activity_type_code (company_key_hash, activity_type_code),
            INDEX idx_project_activity_type_status (company_key_hash, activity_type_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_activity_cost (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            activity_cost_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            activity_type_key CHAR(36) NOT NULL,
            employee_key CHAR(36) NOT NULL,
            effective_from DATE NOT NULL,
            effective_to DATE NULL,
            costing_rate DECIMAL(21,6) NOT NULL DEFAULT 0,
            billing_rate DECIMAL(21,6) NOT NULL DEFAULT 0,
            currency_code CHAR(3) NOT NULL DEFAULT 'PHP',
            activity_cost_status ENUM('ACTIVE','INACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_activity_cost_period (company_key_hash, activity_type_key, employee_key, effective_from),
            INDEX idx_project_activity_cost_active (company_key_hash, activity_cost_status, effective_from)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_record (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            project_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            project_code VARCHAR(80) NOT NULL,
            project_name VARCHAR(190) NOT NULL,
            project_type_key CHAR(36) NULL,
            customer_key CHAR(36) NULL,
            project_lead_employee_key CHAR(36) NULL,
            project_status ENUM('OPEN','ON_HOLD','COMPLETED','CANCELLED','DELETED') NOT NULL DEFAULT 'OPEN',
            completion_method ENUM('MANUAL','TASK_COMPLETION','TASK_PROGRESS','TASK_WEIGHT') NOT NULL DEFAULT 'MANUAL',
            percent_complete DECIMAL(7,4) NOT NULL DEFAULT 0,
            expected_start_date DATE NULL,
            expected_end_date DATE NULL,
            form_schema_key CHAR(36) NULL,
            form_schema_version INT UNSIGNED NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_record_code (company_key_hash, project_code),
            INDEX idx_project_record_status (company_key_hash, project_status, expected_end_date)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_template (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            project_template_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            template_code VARCHAR(80) NOT NULL,
            template_name VARCHAR(190) NOT NULL,
            project_type_key CHAR(36) NULL,
            template_status ENUM('DRAFT','ACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'DRAFT',
            form_schema_key CHAR(36) NULL,
            form_schema_version INT UNSIGNED NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_template_code (company_key_hash, template_code),
            INDEX idx_project_template_status (company_key_hash, template_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_template_task (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            project_template_task_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            project_template_key CHAR(36) NOT NULL,
            source_task_key CHAR(36) NULL,
            parent_template_task_key CHAR(36) NULL,
            task_subject VARCHAR(190) NOT NULL,
            relative_start_days INT NOT NULL DEFAULT 0,
            duration_days INT UNSIGNED NOT NULL DEFAULT 1,
            task_weight DECIMAL(9,4) NOT NULL DEFAULT 0,
            sort_order INT UNSIGNED NOT NULL DEFAULT 100,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_template_task_order (project_template_key, sort_order, project_template_task_key),
            INDEX idx_project_template_task_scope (company_key_hash, project_template_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_task (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            task_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            project_key CHAR(36) NULL,
            parent_task_key CHAR(36) NULL,
            task_type_key CHAR(36) NULL,
            task_code VARCHAR(80) NOT NULL,
            task_subject VARCHAR(190) NOT NULL,
            task_status ENUM('OPEN','WORKING','PENDING_REVIEW','OVERDUE','TEMPLATE','COMPLETED','CANCELLED','DELETED') NOT NULL DEFAULT 'OPEN',
            priority ENUM('LOW','MEDIUM','HIGH','URGENT') NOT NULL DEFAULT 'MEDIUM',
            progress DECIMAL(7,4) NOT NULL DEFAULT 0,
            expected_start_date DATE NULL,
            expected_end_date DATE NULL,
            completed_on DATE NULL,
            is_group TINYINT(1) NOT NULL DEFAULT 0,
            task_weight DECIMAL(9,4) NOT NULL DEFAULT 0,
            sort_order INT UNSIGNED NOT NULL DEFAULT 100,
            assigned_employee_key CHAR(36) NULL,
            assignment_request_key CHAR(64) NULL,
            assignment_status ENUM('UNASSIGNED','PENDING','SYNCED','FAILED') NOT NULL DEFAULT 'UNASSIGNED',
            assignment_error_code VARCHAR(64) NULL,
            external_assignment_key CHAR(36) NULL,
            form_schema_key CHAR(36) NULL,
            form_schema_version INT UNSIGNED NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_task_code (company_key_hash, task_code),
            UNIQUE KEY uq_project_task_assignment_request (company_key_hash, assignment_request_key),
            INDEX idx_project_task_project (company_key_hash, project_key, task_status),
            INDEX idx_project_task_parent (company_key_hash, parent_task_key),
            INDEX idx_project_task_order (company_key_hash, project_key, sort_order, task_key),
            INDEX idx_project_task_assignment (company_key_hash, assignment_status, assigned_employee_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_task_dependency (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            task_dependency_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            task_key CHAR(36) NOT NULL,
            depends_on_task_key CHAR(36) NOT NULL,
            dependency_status ENUM('ACTIVE','REMOVED') NOT NULL DEFAULT 'ACTIVE',
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_task_dependency (company_key_hash, task_key, depends_on_task_key),
            INDEX idx_project_task_dependent (company_key_hash, depends_on_task_key, dependency_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_user (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            project_user_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            project_key CHAR(36) NOT NULL,
            external_user_key CHAR(36) NOT NULL,
            membership_status ENUM('ACTIVE','REVOKED') NOT NULL DEFAULT 'ACTIVE',
            sync_status ENUM('PENDING','SYNCED','FAILED') NOT NULL DEFAULT 'PENDING',
            external_access_key CHAR(36) NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_user_membership (company_key_hash, project_key, external_user_key),
            INDEX idx_project_user_status (company_key_hash, membership_status, sync_status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_update (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            project_update_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            project_key CHAR(36) NOT NULL,
            amended_from_update_key CHAR(36) NULL,
            update_title VARCHAR(190) NOT NULL,
            update_body TEXT NOT NULL,
            percent_complete DECIMAL(7,4) NOT NULL DEFAULT 0,
            update_status ENUM('DRAFT','SUBMITTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
            form_schema_key CHAR(36) NULL,
            form_schema_version INT UNSIGNED NULL,
            submitted_by_admin_key CHAR(36) NULL,
            submitted_at TIMESTAMP NULL,
            cancelled_by_admin_key CHAR(36) NULL,
            cancelled_at TIMESTAMP NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            updated_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_project_update_project (company_key_hash, project_key, update_status, created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_company_project_form_schema (
            x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            form_schema_key CHAR(36) NOT NULL UNIQUE,
            company_key VARCHAR(1500) NOT NULL,
            company_key_hash CHAR(64) NOT NULL,
            target_type VARCHAR(64) NOT NULL,
            version_number INT UNSIGNED NOT NULL,
            schema_status ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
            schema_json LONGTEXT NOT NULL,
            schema_checksum CHAR(64) NOT NULL,
            created_by_admin_key CHAR(36) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_project_form_version (company_key_hash, target_type, version_number),
            UNIQUE KEY uq_project_form_status_checksum (company_key_hash, target_type, schema_status, schema_checksum),
            INDEX idx_project_form_active (company_key_hash, target_type, schema_status, version_number)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ];

    foreach ($statements as $statement) {
        yovel_admin_projects_db_execute($db, $statement, [], 'Projects schema update');
    }
    yovel_admin_projects_db_execute(
        $db,
        'ALTER TABLE project_company_project_record
         ADD COLUMN IF NOT EXISTS project_lead_employee_key CHAR(36) NULL AFTER customer_key',
        [],
        'Projects project-lead schema update'
    );
    yovel_admin_projects_db_execute(
        $db,
        'ALTER TABLE project_company_project_record
         ADD INDEX IF NOT EXISTS idx_project_record_lead (company_key_hash, project_lead_employee_key)',
        [],
        'Projects project-lead index update'
    );
    foreach ([
        "ADD COLUMN IF NOT EXISTS sort_order INT UNSIGNED NOT NULL DEFAULT 100 AFTER task_weight",
        "ADD COLUMN IF NOT EXISTS assigned_employee_key CHAR(36) NULL AFTER sort_order",
        "ADD COLUMN IF NOT EXISTS assignment_request_key CHAR(64) NULL AFTER assigned_employee_key",
        "ADD COLUMN IF NOT EXISTS assignment_status ENUM('UNASSIGNED','PENDING','SYNCED','FAILED') NOT NULL DEFAULT 'UNASSIGNED' AFTER assignment_request_key",
        "ADD COLUMN IF NOT EXISTS assignment_error_code VARCHAR(64) NULL AFTER assignment_status",
        'ADD UNIQUE INDEX IF NOT EXISTS uq_project_task_assignment_request (company_key_hash, assignment_request_key)',
        'ADD INDEX IF NOT EXISTS idx_project_task_order (company_key_hash, project_key, sort_order, task_key)',
        'ADD INDEX IF NOT EXISTS idx_project_task_assignment (company_key_hash, assignment_status, assigned_employee_key)',
    ] as $taskAlter) {
        yovel_admin_projects_db_execute(
            $db,
            'ALTER TABLE project_company_project_task ' . $taskAlter,
            [],
            'Projects task schema update'
        );
    }
    $ready = true;
}
