<?php
declare(strict_types=1);

function yovel_admin_finance_payment_schema():void
{
 $db=bx_db();$sql=[
 "CREATE TABLE IF NOT EXISTS project_company_finance_payment_entry (x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,payment_entry_key CHAR(36) NOT NULL UNIQUE,company_key CHAR(36) NOT NULL,company_key_hash CHAR(64) NOT NULL,payment_no VARCHAR(120) NOT NULL,payment_type ENUM('RECEIVE','PAY','INTERNAL_TRANSFER') NOT NULL,posting_date DATE NOT NULL,party_type ENUM('CUSTOMER','SUPPLIER','NONE') NOT NULL DEFAULT 'NONE',party_key CHAR(36) NULL,party_name VARCHAR(200) NULL,party_account_key CHAR(36) NULL,paid_from_account_key CHAR(36) NULL,paid_to_account_key CHAR(36) NULL,paid_amount DECIMAL(20,6) NOT NULL,received_amount DECIMAL(20,6) NOT NULL,currency VARCHAR(20) NOT NULL DEFAULT 'PHP',exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 1,allocated_amount DECIMAL(20,6) NOT NULL DEFAULT 0,unallocated_amount DECIMAL(20,6) NOT NULL DEFAULT 0,reference_no VARCHAR(120) NULL,reference_date DATE NULL,remarks VARCHAR(1000) NULL,document_status ENUM('DRAFT','SUBMITTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',gl_transaction_key CHAR(36) NULL,reversal_transaction_key CHAR(36) NULL,submitted_by_admin_key CHAR(36) NULL,submitted_at TIMESTAMP NULL,cancelled_by_admin_key CHAR(36) NULL,cancelled_at TIMESTAMP NULL,created_by_admin_key CHAR(36) NULL,updated_by_admin_key CHAR(36) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_project_company_finance_payment_no(company_key_hash,payment_no),INDEX idx_project_company_finance_payment_date(company_key_hash,posting_date,document_status),INDEX idx_project_company_finance_payment_party(company_key_hash,party_type,party_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS project_company_finance_payment_allocation (x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,payment_allocation_key CHAR(36) NOT NULL UNIQUE,payment_entry_key CHAR(36) NOT NULL,invoice_key CHAR(36) NOT NULL,company_key CHAR(36) NOT NULL,company_key_hash CHAR(64) NOT NULL,allocated_amount DECIMAL(20,6) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_project_company_finance_payment_allocation(company_key_hash,payment_entry_key,invoice_key),INDEX idx_project_company_finance_allocation_invoice(company_key_hash,invoice_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS project_company_finance_payment_deduction (x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,payment_deduction_key CHAR(36) NOT NULL UNIQUE,payment_entry_key CHAR(36) NOT NULL,company_key CHAR(36) NOT NULL,company_key_hash CHAR(64) NOT NULL,account_key CHAR(36) NOT NULL,amount DECIMAL(20,6) NOT NULL,description VARCHAR(180) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_project_company_finance_payment_deduction(company_key_hash,payment_entry_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
 ];foreach($sql as $s)yovel_admin_db_execute($db,$s,[],'Finance Payment schema update');
 foreach([
  ['base_currency',"VARCHAR(20) NOT NULL DEFAULT 'PHP'"],['base_paid_amount','DECIMAL(20,6) NOT NULL DEFAULT 0'],['base_received_amount','DECIMAL(20,6) NOT NULL DEFAULT 0'],['write_off_amount','DECIMAL(20,6) NOT NULL DEFAULT 0'],['write_off_account_key','CHAR(36) NULL'],['exchange_gain_loss','DECIMAL(20,6) NOT NULL DEFAULT 0'],['exchange_gain_loss_account_key','CHAR(36) NULL']
 ] as [$column,$definition])yovel_admin_finance_ensure_column($db,'project_company_finance_payment_entry',$column,$definition);
 yovel_admin_finance_ensure_column($db,'project_company_finance_payment_allocation','write_off_amount','DECIMAL(20,6) NOT NULL DEFAULT 0');
}

function yovel_admin_finance_payment_type(string $type):string{$type=strtoupper(trim($type));if(!in_array($type,['RECEIVE','PAY','INTERNAL_TRANSFER'],true))throw new InvalidArgumentException('Payment type is invalid.');return $type;}

function yovel_admin_finance_payment_allocations(ADOConnection $db,array $company,string $type,string $partyKey,array $allocations,bool $lock=false):array
{
 $hash=(string)$company['company_key_hash'];$expected=$type==='RECEIVE'?'SALES':'PURCHASE';$rows=[];$total='0.000000';$seen=[];
 $writeOffTotal='0.000000';
 foreach($allocations as $allocation){if(!is_array($allocation))throw new InvalidArgumentException('Payment allocations must be structured rows.');$invoiceKey=trim((string)($allocation['invoice_key']??''));$amount=yovel_admin_finance_money($allocation['allocated_amount']??'0');$writeOff=yovel_admin_finance_money($allocation['write_off_amount']??'0');if(!yovel_admin_is_uuid($invoiceKey)||bccomp($amount,'0',6)===-1||bccomp($writeOff,'0',6)===-1||(bccomp($amount,'0',6)===0&&bccomp($writeOff,'0',6)===0)||isset($seen[$invoiceKey]))throw new InvalidArgumentException('Payment allocation reference and amount are invalid.');$seen[$invoiceKey]=true;$invoice=$db->GetRow("SELECT invoice_key,party_key,outstanding_amount,document_type,document_status,is_return FROM project_company_finance_invoice WHERE company_key_hash=? AND invoice_key=?".($lock?' FOR UPDATE':''),[$hash,$invoiceKey]);if(!$invoice||(string)$invoice['document_status']!=='SUBMITTED'||(string)$invoice['document_type']!==$expected||(int)$invoice['is_return']===1)throw new InvalidArgumentException('Payment allocation requires an open Submitted invoice of the matching type.');if((string)$invoice['party_key']!==$partyKey)throw new InvalidArgumentException('Payment allocation invoice belongs to a different party.');if(bccomp(bcadd($amount,$writeOff,6),(string)$invoice['outstanding_amount'],6)===1)throw new InvalidArgumentException('Payment allocation and write-off exceed the invoice outstanding amount.');$rows[]=['payment_allocation_key'=>bx_uuid(),'invoice_key'=>$invoiceKey,'allocated_amount'=>$amount,'write_off_amount'=>$writeOff];$total=bcadd($total,$amount,6);$writeOffTotal=bcadd($writeOffTotal,$writeOff,6);}
 return ['rows'=>$rows,'total'=>yovel_admin_finance_money($total),'write_off_total'=>yovel_admin_finance_money($writeOffTotal),'settled_total'=>yovel_admin_finance_money(bcadd($total,$writeOffTotal,6))];
}

function yovel_admin_persist_payment_entry(ADOConnection $db,array $company,array $admin,array $input,?array $dependencyOverrides=null):array
{
 yovel_admin_finance_core_schema();yovel_admin_finance_invoice_schema();yovel_admin_finance_payment_schema();[$companyKey,$hash,$adminKey]=yovel_admin_finance_scope($company,$admin);$key=trim((string)($input['payment_entry_key']??''));if($key!==''&&!yovel_admin_is_uuid($key))throw new InvalidArgumentException('Payment Entry key is invalid.');$type=yovel_admin_finance_payment_type((string)($input['payment_type']??''));$date=yovel_admin_optional_date((string)($input['posting_date']??''),'Payment posting date');if($date==='')throw new InvalidArgumentException('Payment posting date is required.');$no=substr(trim((string)($input['payment_no']??'')),0,120);if($no==='')$no=yovel_admin_finance_next_number($db,$company,$admin,'PAYMENT_ENTRY','PAY-',(int)substr($date,0,4));$paid=yovel_admin_finance_money($input['paid_amount']??'0');$received=yovel_admin_finance_money($input['received_amount']??$paid);if(bccomp($paid,'0',6)!==1||bccomp($received,'0',6)!==1)throw new InvalidArgumentException('Payment amounts must be positive.');$partyType=$type==='RECEIVE'?'CUSTOMER':($type==='PAY'?'SUPPLIER':'NONE');$partyKey=$partyType==='NONE'?'':trim((string)($input['party_key']??''));$partyName='';$services=yovel_admin_finance_invoice_dependency_gateway($dependencyOverrides??[]);if($partyType!=='NONE'){$contract=$partyType==='CUSTOMER'?'sales-crm.customer-reference.v1':'buying-procurement.supplier-reference.v1';$party=yovel_admin_finance_invoice_owner_record($company,$contract,$partyKey,$services);$partyName=(string)($party[$partyType==='CUSTOMER'?'customer_name':'supplier_name']??'');if($partyName==='')throw new InvalidArgumentException('Payment party must be active and belong to this company.');}
 $partyAccount=$partyType==='NONE'?null:yovel_admin_finance_account_key($db,$hash,$input['party_account_key']??'','Payment party account',$partyType==='CUSTOMER'?['ASSET']:['LIABILITY'],[$partyType==='CUSTOMER'?'Receivable':'Payable']);$from=yovel_admin_finance_account_key($db,$hash,$input['paid_from_account_key']??'','Paid-from account',['ASSET'],['Bank','Cash']);$to=yovel_admin_finance_account_key($db,$hash,$input['paid_to_account_key']??'','Paid-to account',['ASSET'],['Bank','Cash']);if($type==='RECEIVE'&&$to===null)throw new InvalidArgumentException('Receive Payment requires a Bank or Cash paid-to account.');if($type==='PAY'&&$from===null)throw new InvalidArgumentException('Pay Payment requires a Bank or Cash paid-from account.');if($type==='INTERNAL_TRANSFER'&&($from===null||$to===null||$from===$to))throw new InvalidArgumentException('Internal Transfer requires different Bank or Cash accounts.');$allocationInput=is_array($input['allocations']??null)?$input['allocations']:[];$globalWriteOff=yovel_admin_finance_money($input['write_off_amount']??'0');if(bccomp($globalWriteOff,'0',6)===1){if(count($allocationInput)!==1)throw new InvalidArgumentException('A Payment write-off requires exactly one invoice allocation.');$allocationInput[0]['write_off_amount']=$globalWriteOff;}$alloc=$type==='INTERNAL_TRANSFER'?['rows'=>[],'total'=>'0.000000','write_off_total'=>'0.000000','settled_total'=>'0.000000']:yovel_admin_finance_payment_allocations($db,$company,$type,$partyKey,$allocationInput);if(bccomp($alloc['total'],$paid,6)===1)throw new InvalidArgumentException('Payment allocations exceed the paid amount.');$unallocated=yovel_admin_finance_money(bcsub($paid,$alloc['total'],6));$currency=strtoupper(trim((string)($input['currency']??'PHP')));$rate=yovel_admin_finance_money($input['exchange_rate']??'1',8);if(preg_match('/^[A-Z]{3}$/',$currency)!==1||bccomp($rate,'0',8)!==1)throw new InvalidArgumentException('Payment currency or exchange rate is invalid.');$settings=yovel_admin_finance_settings($company,$admin);$baseCurrency=(string)($settings['base_currency']??'PHP');$basePaid=yovel_admin_finance_money(bcmul($paid,$rate,6));$baseReceived=yovel_admin_finance_money(bcmul($received,$rate,6));$writeOffAccount=bccomp($alloc['write_off_total'],'0',6)===1?yovel_admin_finance_account_key($db,$hash,$input['write_off_account_key']??'','Write-off account',['EXPENSE','INCOME']):null;if(bccomp($alloc['write_off_total'],'0',6)===1&&$writeOffAccount===null)throw new InvalidArgumentException('Write-off account is required.');$exchangeDifference=yovel_admin_finance_money(bcsub($baseReceived,$basePaid,6));$exchangeAccount=bccomp($exchangeDifference,'0',6)!==0?yovel_admin_finance_account_key($db,$hash,$input['exchange_gain_loss_account_key']??'','Exchange gain/loss account',['EXPENSE','INCOME']):null;if(bccomp($exchangeDifference,'0',6)!==0&&$exchangeAccount===null)throw new InvalidArgumentException('Exchange gain/loss account is required.');
 if($db->BeginTrans()===false)throw new RuntimeException('Payment Entry transaction could not start.');
 try{
  $existing=$key!==''?$db->GetRow('SELECT * FROM project_company_finance_payment_entry WHERE company_key_hash=? AND payment_entry_key=? FOR UPDATE',[$hash,$key]):$db->GetRow('SELECT * FROM project_company_finance_payment_entry WHERE company_key_hash=? AND payment_no=? FOR UPDATE',[$hash,$no]);
  if($existing&&(string)$existing['document_status']!=='DRAFT')throw new InvalidArgumentException('Submitted or Cancelled Payment Entries are immutable.');
  $key=$existing?(string)$existing['payment_entry_key']:($key!==''?$key:bx_uuid());
  yovel_admin_db_execute($db,"INSERT INTO project_company_finance_payment_entry(payment_entry_key,company_key,company_key_hash,payment_no,payment_type,posting_date,party_type,party_key,party_name,party_account_key,paid_from_account_key,paid_to_account_key,paid_amount,received_amount,currency,exchange_rate,base_currency,base_paid_amount,base_received_amount,allocated_amount,unallocated_amount,write_off_amount,write_off_account_key,exchange_gain_loss,exchange_gain_loss_account_key,reference_no,reference_date,remarks,document_status,created_by_admin_key,updated_by_admin_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'DRAFT',?,?) ON DUPLICATE KEY UPDATE payment_type=VALUES(payment_type),posting_date=VALUES(posting_date),party_type=VALUES(party_type),party_key=VALUES(party_key),party_name=VALUES(party_name),party_account_key=VALUES(party_account_key),paid_from_account_key=VALUES(paid_from_account_key),paid_to_account_key=VALUES(paid_to_account_key),paid_amount=VALUES(paid_amount),received_amount=VALUES(received_amount),currency=VALUES(currency),exchange_rate=VALUES(exchange_rate),base_currency=VALUES(base_currency),base_paid_amount=VALUES(base_paid_amount),base_received_amount=VALUES(base_received_amount),allocated_amount=VALUES(allocated_amount),unallocated_amount=VALUES(unallocated_amount),write_off_amount=VALUES(write_off_amount),write_off_account_key=VALUES(write_off_account_key),exchange_gain_loss=VALUES(exchange_gain_loss),exchange_gain_loss_account_key=VALUES(exchange_gain_loss_account_key),reference_no=VALUES(reference_no),reference_date=VALUES(reference_date),remarks=VALUES(remarks),updated_by_admin_key=VALUES(updated_by_admin_key)",[$key,$companyKey,$hash,$no,$type,$date,$partyType,$partyKey?:null,$partyName?:null,$partyAccount,$from,$to,$paid,$received,$currency,$rate,$baseCurrency,$basePaid,$baseReceived,$alloc['total'],$unallocated,$alloc['write_off_total'],$writeOffAccount,$exchangeDifference,$exchangeAccount,substr(trim((string)($input['reference_no']??'')),0,120)?:null,yovel_admin_optional_date((string)($input['reference_date']??''),'Payment reference date')?:null,substr(trim((string)($input['remarks']??'')),0,1000)?:null,$adminKey,$adminKey],'Payment Entry save');
  yovel_admin_db_execute($db,'DELETE FROM project_company_finance_payment_allocation WHERE company_key_hash=? AND payment_entry_key=?',[$hash,$key],'Payment allocation reset');
  foreach($alloc['rows'] as $a)yovel_admin_db_execute($db,'INSERT INTO project_company_finance_payment_allocation(payment_allocation_key,payment_entry_key,invoice_key,company_key,company_key_hash,allocated_amount,write_off_amount) VALUES(?,?,?,?,?,?,?)',[$a['payment_allocation_key'],$key,$a['invoice_key'],$companyKey,$hash,$a['allocated_amount'],$a['write_off_amount']],'Payment allocation save');
  if(is_callable($input['_checkpoint']??null))$input['_checkpoint']('after_payment_allocations');
  $saved=yovel_admin_payment_entry($company,$key,false);if(!$saved||count($saved['allocations'])!==count($alloc['rows'])||(string)$saved['unallocated_amount']!==$unallocated||(string)$saved['base_paid_amount']!==$basePaid)throw new RuntimeException('Payment Entry read-back verification failed.');
  bx_audit($existing?'UPDATE':'CREATE','project_company_finance_payment_entry',$key,['company_key'=>$companyKey,'payment_no'=>$no,'payment_type'=>$type,'paid_amount'=>$paid,'base_paid_amount'=>$basePaid,'write_off_amount'=>$alloc['write_off_total'],'exchange_gain_loss'=>$exchangeDifference,'admin_key'=>$adminKey],'Company administrator saved a Payment Entry Draft.');
  if($db->CommitTrans()===false)throw new RuntimeException('Payment Entry transaction could not commit.');return $saved;
 }catch(Throwable $e){$db->RollbackTrans();throw $e;}
}

function yovel_admin_submit_payment_entry(ADOConnection $db,array $company,array $admin,string $key):array
{
 yovel_admin_finance_core_schema();yovel_admin_finance_invoice_schema();yovel_admin_finance_payment_schema();yovel_admin_general_ledger_schema();[$companyKey,$hash,$adminKey]=yovel_admin_finance_scope($company,$admin);$preview=yovel_admin_payment_entry($company,$key);if(!$preview)throw new InvalidArgumentException('Payment Entry was not found for this company.');yovel_admin_finance_assert_open_period($company,(string)$preview['posting_date'],false);if($db->BeginTrans()===false)throw new RuntimeException('Payment submission transaction could not start.');
 try{
  $h=$db->GetRow('SELECT * FROM project_company_finance_payment_entry WHERE company_key_hash=? AND payment_entry_key=? FOR UPDATE',[$hash,$key]);if(!$h||(string)$h['document_status']!=='DRAFT')throw new InvalidArgumentException('Only a Draft Payment Entry can be submitted.');
  $stored=$db->GetAll('SELECT * FROM project_company_finance_payment_allocation WHERE company_key_hash=? AND payment_entry_key=? ORDER BY x_id',[$hash,$key]);$alloc=yovel_admin_finance_payment_allocations($db,$company,(string)$h['payment_type'],(string)($h['party_key']??''),$stored,true);if(bccomp($alloc['total'],(string)$h['allocated_amount'],6)!==0||bccomp($alloc['write_off_total'],(string)$h['write_off_amount'],6)!==0)throw new RuntimeException('Payment allocation changed before submission.');
  foreach($alloc['rows'] as $a){$settled=bcadd($a['allocated_amount'],$a['write_off_amount'],6);yovel_admin_db_execute($db,'UPDATE project_company_finance_invoice SET outstanding_amount=outstanding_amount-?,base_outstanding_amount=base_outstanding_amount-(?*exchange_rate),updated_by_admin_key=? WHERE company_key_hash=? AND invoice_key=? AND document_status=\'SUBMITTED\'',[$settled,$settled,$adminKey,$hash,$a['invoice_key']],'Invoice allocation update');}
  $type=(string)$h['payment_type'];$currency=['transaction_currency'=>$h['currency'],'exchange_rate'=>$h['exchange_rate']];
  if($type==='RECEIVE')$entries=[array_merge($currency,['account_key'=>$h['paid_to_account_key'],'debit'=>$h['base_received_amount'],'credit'=>'0','transaction_debit'=>$h['received_amount'],'transaction_credit'=>'0']),array_merge($currency,['account_key'=>$h['party_account_key'],'debit'=>'0','credit'=>bcadd($h['base_paid_amount'],bcmul($h['write_off_amount'],$h['exchange_rate'],6),6),'transaction_debit'=>'0','transaction_credit'=>bcadd($h['paid_amount'],$h['write_off_amount'],6),'party_type'=>'CUSTOMER','party'=>$h['party_name']])];
  elseif($type==='PAY')$entries=[array_merge($currency,['account_key'=>$h['party_account_key'],'debit'=>bcadd($h['base_paid_amount'],bcmul($h['write_off_amount'],$h['exchange_rate'],6),6),'credit'=>'0','transaction_debit'=>bcadd($h['paid_amount'],$h['write_off_amount'],6),'transaction_credit'=>'0','party_type'=>'SUPPLIER','party'=>$h['party_name']]),array_merge($currency,['account_key'=>$h['paid_from_account_key'],'debit'=>'0','credit'=>$h['base_received_amount'],'transaction_debit'=>'0','transaction_credit'=>$h['received_amount']])];
  else $entries=[array_merge($currency,['account_key'=>$h['paid_to_account_key'],'debit'=>$h['base_received_amount'],'credit'=>'0','transaction_debit'=>$h['received_amount'],'transaction_credit'=>'0']),array_merge($currency,['account_key'=>$h['paid_from_account_key'],'debit'=>'0','credit'=>$h['base_paid_amount'],'transaction_debit'=>'0','transaction_credit'=>$h['paid_amount']])];
  $writeOffBase=yovel_admin_finance_money(bcmul((string)$h['write_off_amount'],(string)$h['exchange_rate'],6));if(bccomp($writeOffBase,'0',6)===1)$entries[]=array_merge($currency,['account_key'=>$h['write_off_account_key'],'debit'=>$type==='RECEIVE'?$writeOffBase:'0','credit'=>$type==='PAY'?$writeOffBase:'0','transaction_debit'=>$type==='RECEIVE'?$h['write_off_amount']:'0','transaction_credit'=>$type==='PAY'?$h['write_off_amount']:'0']);
  $debit='0.000000';$credit='0.000000';foreach($entries as $entry){$debit=bcadd($debit,(string)$entry['debit'],6);$credit=bcadd($credit,(string)$entry['credit'],6);}$difference=bcsub($debit,$credit,6);if(bccomp($difference,'0',6)!==0){if(!yovel_admin_is_uuid((string)($h['exchange_gain_loss_account_key']??'')))throw new InvalidArgumentException('Exchange gain/loss account is required to balance this Payment Entry.');$entries[]=['account_key'=>$h['exchange_gain_loss_account_key'],'debit'=>bccomp($difference,'0',6)===-1?yovel_admin_finance_abs($difference):'0','credit'=>bccomp($difference,'0',6)===1?$difference:'0'];}
  $posted=yovel_admin_post_general_ledger_transaction($db,$company,$admin,['posting_date'=>$h['posting_date'],'voucher_type'=>'PAYMENT_ENTRY','voucher_no'=>$h['payment_no'],'source_module'=>'PAYMENT_ENTRY','source_record_key'=>$key,'remarks'=>$h['remarks']??'','base_currency'=>$h['base_currency'],'entries'=>$entries],false,false);
  yovel_admin_db_execute($db,"UPDATE project_company_finance_payment_entry SET document_status='SUBMITTED',gl_transaction_key=?,submitted_by_admin_key=?,submitted_at=CURRENT_TIMESTAMP,updated_by_admin_key=? WHERE company_key_hash=? AND payment_entry_key=?",[$posted['transaction_key'],$adminKey,$adminKey,$hash,$key],'Payment Entry submission');$saved=yovel_admin_payment_entry($company,$key,false);if(!$saved||(string)$saved['document_status']!=='SUBMITTED')throw new RuntimeException('Payment Entry submission read-back verification failed.');bx_audit('SUBMIT','project_company_finance_payment_entry',$key,['company_key'=>$companyKey,'payment_no'=>$h['payment_no'],'gl_transaction_key'=>$posted['transaction_key'],'write_off_amount'=>$h['write_off_amount'],'exchange_gain_loss'=>$h['exchange_gain_loss'],'admin_key'=>$adminKey],'Company administrator submitted a Payment Entry.');if($db->CommitTrans()===false)throw new RuntimeException('Payment submission transaction could not commit.');return $saved;
 }catch(Throwable $e){$db->RollbackTrans();throw $e;}
}

function yovel_admin_cancel_payment_entry(ADOConnection $db,array $company,array $admin,string $key,string $date,string $reason):array
{
 yovel_admin_finance_core_schema();yovel_admin_finance_payment_schema();yovel_admin_general_ledger_schema();[$companyKey,$hash,$adminKey]=yovel_admin_finance_scope($company,$admin);$date=yovel_admin_optional_date($date,'Cancellation posting date');if(!yovel_admin_is_uuid($key)||$date===''||trim($reason)==='')throw new InvalidArgumentException('Payment cancellation reference, date, and reason are required.');yovel_admin_finance_assert_open_period($company,$date,false);if($db->BeginTrans()===false)throw new RuntimeException('Payment cancellation transaction could not start.');try{$h=$db->GetRow('SELECT * FROM project_company_finance_payment_entry WHERE company_key_hash=? AND payment_entry_key=? FOR UPDATE',[$hash,$key]);if(!$h||(string)$h['document_status']!=='SUBMITTED')throw new InvalidArgumentException('Only a Submitted Payment Entry can be cancelled.');$alloc=$db->GetAll('SELECT * FROM project_company_finance_payment_allocation WHERE company_key_hash=? AND payment_entry_key=?',[$hash,$key]);foreach($alloc as $a){$settled=bcadd((string)$a['allocated_amount'],(string)$a['write_off_amount'],6);yovel_admin_db_execute($db,'UPDATE project_company_finance_invoice SET outstanding_amount=outstanding_amount+?,base_outstanding_amount=base_outstanding_amount+(?*exchange_rate),updated_by_admin_key=? WHERE company_key_hash=? AND invoice_key=?',[$settled,$settled,$adminKey,$hash,$a['invoice_key']],'Payment cancellation allocation restore');}$rev=yovel_admin_reverse_general_ledger_transaction($db,$company,$admin,(string)$h['gl_transaction_key'],$date,trim($reason),false,false);yovel_admin_db_execute($db,"UPDATE project_company_finance_payment_entry SET document_status='CANCELLED',reversal_transaction_key=?,cancelled_by_admin_key=?,cancelled_at=CURRENT_TIMESTAMP,updated_by_admin_key=? WHERE company_key_hash=? AND payment_entry_key=?",[$rev['transaction_key'],$adminKey,$adminKey,$hash,$key],'Payment Entry cancellation');$saved=yovel_admin_payment_entry($company,$key,false);if(!$saved||(string)$saved['document_status']!=='CANCELLED')throw new RuntimeException('Payment Entry cancellation read-back verification failed.');bx_audit('CANCEL','project_company_finance_payment_entry',$key,['company_key'=>$companyKey,'payment_no'=>$h['payment_no'],'reversal_transaction_key'=>$rev['transaction_key'],'admin_key'=>$adminKey],'Company administrator cancelled a Payment Entry through an additive reversal.');if($db->CommitTrans()===false)throw new RuntimeException('Payment cancellation transaction could not commit.');return $saved;}catch(Throwable $e){$db->RollbackTrans();throw $e;}
}

function yovel_admin_payment_entry(array $company,string $key,bool $schema=true):?array{if($schema)yovel_admin_finance_payment_schema();if(!yovel_admin_is_uuid($key))return null;$h=(string)($company['company_key_hash']??'');$row=bx_db()->GetRow('SELECT * FROM project_company_finance_payment_entry WHERE company_key_hash=? AND payment_entry_key=?',[$h,$key]);if(!$row)return null;$a=bx_db()->GetAll('SELECT * FROM project_company_finance_payment_allocation WHERE company_key_hash=? AND payment_entry_key=? ORDER BY x_id',[$h,$key]);$row['allocations']=is_array($a)?$a:[];return $row;}
function yovel_admin_payment_entries(array $company,array $filters=[]):array{yovel_admin_finance_payment_schema();$rows=bx_db()->GetAll('SELECT * FROM project_company_finance_payment_entry WHERE company_key_hash=? ORDER BY posting_date DESC,x_id DESC LIMIT 1000',[(string)($company['company_key_hash']??'')]);return is_array($rows)?$rows:[];}
function yovel_admin_open_invoice_references(array $company,string $type,string $partyKey):array{yovel_admin_finance_invoice_schema();$rows=bx_db()->GetAll("SELECT invoice_key,invoice_no,posting_date,due_date,grand_total,outstanding_amount FROM project_company_finance_invoice WHERE company_key_hash=? AND document_type=? AND party_key=? AND document_status='SUBMITTED' AND is_return=0 AND outstanding_amount>0 ORDER BY due_date,invoice_no",[(string)$company['company_key_hash'],yovel_admin_finance_invoice_type($type),$partyKey]);return is_array($rows)?$rows:[];}
function yovel_admin_invoice_allocations(array $company,string $invoiceKey):array{$rows=bx_db()->GetAll("SELECT a.*,p.payment_no,p.posting_date,p.document_status FROM project_company_finance_payment_allocation a JOIN project_company_finance_payment_entry p ON p.payment_entry_key=a.payment_entry_key AND p.company_key_hash=a.company_key_hash WHERE a.company_key_hash=? AND a.invoice_key=? ORDER BY p.posting_date,p.x_id",[(string)$company['company_key_hash'],$invoiceKey]);return is_array($rows)?$rows:[];}

function yovel_admin_finance_payment_allocations_from_post():array{$j=trim((string)($_POST['allocations_json']??''));if($j==='')return [];$v=json_decode($j,true,512,JSON_THROW_ON_ERROR);if(!is_array($v))throw new InvalidArgumentException('Payment allocations JSON is invalid.');return $v;}
function yovel_admin_save_payment_action(array $company,array $admin):string{return yovel_admin_finance_run_form_action($company,'save_finance_payment',static function()use($company,$admin):string{$i=$_POST;$i['allocations']=yovel_admin_finance_payment_allocations_from_post();$s=yovel_admin_persist_payment_entry(bx_db(),$company,$admin,$i);$GLOBALS['yovel_admin_saved_finance_document_key']=$s['payment_entry_key'];return 'Payment Entry Draft saved.';});}
function yovel_admin_submit_payment_action(array $company,array $admin):string{return yovel_admin_finance_run_form_action($company,'submit_finance_payment',static function()use($company,$admin):string{$s=yovel_admin_submit_payment_entry(bx_db(),$company,$admin,(string)($_POST['payment_entry_key']??''));$GLOBALS['yovel_admin_saved_finance_document_key']=$s['payment_entry_key'];return 'Payment Entry submitted and allocated.';});}
function yovel_admin_cancel_payment_action(array $company,array $admin):string{return yovel_admin_finance_run_form_action($company,'cancel_finance_payment',static function()use($company,$admin):string{$s=yovel_admin_cancel_payment_entry(bx_db(),$company,$admin,(string)($_POST['payment_entry_key']??''),(string)($_POST['cancellation_posting_date']??date('Y-m-d')),(string)($_POST['cancellation_reason']??''));$GLOBALS['yovel_admin_saved_finance_document_key']=$s['payment_entry_key'];return 'Payment Entry cancelled and allocations restored.';});}
