<?php
declare(strict_types=1);

function yovel_admin_finance_report_dates(string $from, string $to): array
{
    $from=yovel_admin_optional_date($from,'Report start date');$to=yovel_admin_optional_date($to,'Report end date');
    if($from===''||$to===''||$to<$from)throw new InvalidArgumentException('Report date range is invalid.');
    return [$from,$to];
}

function yovel_admin_profit_loss_report(array $company,string $from,string $to,array $filters=[]):array
{
    [$from,$to]=yovel_admin_finance_report_dates($from,$to);$hash=(string)$company['company_key_hash'];
    $rows=bx_db()->GetAll("SELECT a.account_key,a.account_code,a.account_name,a.parent_account_key,a.root_type,COALESCE(SUM(CASE WHEN e.voucher_type<>'PERIOD_CLOSE' THEN e.debit ELSE 0 END),0) debit,COALESCE(SUM(CASE WHEN e.voucher_type<>'PERIOD_CLOSE' THEN e.credit ELSE 0 END),0) credit FROM project_company_accounting_account a LEFT JOIN project_company_general_ledger_entry e ON e.account_key=a.account_key AND e.company_key_hash=a.company_key_hash AND e.posting_date BETWEEN ? AND ? WHERE a.company_key_hash=? AND a.root_type IN ('INCOME','EXPENSE') AND a.account_status<>'DELETED' GROUP BY a.x_id ORDER BY a.root_type DESC,a.sort_order,a.account_code",[$from,$to,$hash]);
    $income='0.000000';$expense='0.000000';foreach($rows as &$row){$amount=(string)$row['root_type']==='INCOME'?bcsub((string)$row['credit'],(string)$row['debit'],6):bcsub((string)$row['debit'],(string)$row['credit'],6);$row['amount']=yovel_admin_finance_money($amount);if((string)$row['root_type']==='INCOME')$income=bcadd($income,$amount,6);else $expense=bcadd($expense,$amount,6);}unset($row);
    return ['date_from'=>$from,'date_to'=>$to,'rows'=>$rows,'total_income'=>yovel_admin_finance_money($income),'total_expense'=>yovel_admin_finance_money($expense),'net_profit_loss'=>yovel_admin_finance_money(bcsub($income,$expense,6))];
}

function yovel_admin_balance_sheet_report(array $company,string $asOf,array $filters=[]):array
{
    $asOf=yovel_admin_optional_date($asOf,'Balance Sheet date');if($asOf==='')throw new InvalidArgumentException('Balance Sheet date is required.');$hash=(string)$company['company_key_hash'];
    $rows=bx_db()->GetAll("SELECT a.account_key,a.account_code,a.account_name,a.parent_account_key,a.root_type,COALESCE(SUM(e.debit),0) debit,COALESCE(SUM(e.credit),0) credit FROM project_company_accounting_account a LEFT JOIN project_company_general_ledger_entry e ON e.account_key=a.account_key AND e.company_key_hash=a.company_key_hash AND e.posting_date<=? WHERE a.company_key_hash=? AND a.root_type IN ('ASSET','LIABILITY','EQUITY') AND a.account_status<>'DELETED' GROUP BY a.x_id ORDER BY FIELD(a.root_type,'ASSET','LIABILITY','EQUITY'),a.sort_order,a.account_code",[$asOf,$hash]);$tot=['ASSET'=>'0.000000','LIABILITY'=>'0.000000','EQUITY'=>'0.000000'];foreach($rows as &$row){$amount=(string)$row['root_type']==='ASSET'?bcsub((string)$row['debit'],(string)$row['credit'],6):bcsub((string)$row['credit'],(string)$row['debit'],6);$row['amount']=yovel_admin_finance_money($amount);$tot[$row['root_type']]=bcadd($tot[$row['root_type']],$amount,6);}unset($row);$currentEarnings=yovel_admin_finance_money((string)bx_db()->GetOne("SELECT COALESCE(SUM(e.credit-e.debit),0) FROM project_company_general_ledger_entry e JOIN project_company_accounting_account a ON a.account_key=e.account_key AND a.company_key_hash=e.company_key_hash WHERE e.company_key_hash=? AND e.posting_date<=? AND a.root_type IN ('INCOME','EXPENSE')",[$hash,$asOf]));$equityWithCurrent=bcadd($tot['EQUITY'],$currentEarnings,6);$difference=bcsub($tot['ASSET'],bcadd($tot['LIABILITY'],$equityWithCurrent,6),6);
    if(bccomp(yovel_admin_finance_abs($difference),'0.000001',6)===1)throw new RuntimeException('Balance Sheet is out of balance by '.yovel_admin_finance_money($difference).'.');
    return ['as_of'=>$asOf,'rows'=>$rows,'total_assets'=>yovel_admin_finance_money($tot['ASSET']),'total_liabilities'=>yovel_admin_finance_money($tot['LIABILITY']),'total_equity'=>yovel_admin_finance_money($tot['EQUITY']),'current_earnings'=>$currentEarnings,'liabilities_and_equity'=>yovel_admin_finance_money(bcadd($tot['LIABILITY'],$equityWithCurrent,6)),'difference'=>yovel_admin_finance_money($difference)];
}

function yovel_admin_cash_flow_report(array $company,string $from,string $to,array $filters=[]):array
{
    [$from,$to]=yovel_admin_finance_report_dates($from,$to);$hash=(string)$company['company_key_hash'];$rows=bx_db()->GetAll("SELECT e.*,a.account_type,MAX(CASE WHEN counterpart_account.account_type='Fixed Asset' THEN 1 ELSE 0 END) counterpart_investing,MAX(CASE WHEN counterpart_account.root_type='EQUITY' OR (counterpart_account.root_type='LIABILITY' AND COALESCE(counterpart_account.account_type,'') NOT IN ('Payable','Tax')) THEN 1 ELSE 0 END) counterpart_financing FROM project_company_general_ledger_entry e JOIN project_company_accounting_account a ON a.account_key=e.account_key AND a.company_key_hash=e.company_key_hash LEFT JOIN project_company_general_ledger_entry counterpart ON counterpart.company_key_hash=e.company_key_hash AND counterpart.transaction_key=e.transaction_key AND counterpart.ledger_entry_key<>e.ledger_entry_key LEFT JOIN project_company_accounting_account counterpart_account ON counterpart_account.company_key_hash=counterpart.company_key_hash AND counterpart_account.account_key=counterpart.account_key WHERE e.company_key_hash=? AND e.posting_date BETWEEN ? AND ? AND a.account_type IN ('Bank','Cash') GROUP BY e.x_id ORDER BY e.posting_date,e.x_id",[$hash,$from,$to]);$groups=['OPERATING'=>'0.000000','INVESTING'=>'0.000000','FINANCING'=>'0.000000'];foreach($rows as &$row){$class=(int)$row['counterpart_investing']===1?'INVESTING':((int)$row['counterpart_financing']===1?'FINANCING':'OPERATING');$amount=bcsub((string)$row['debit'],(string)$row['credit'],6);$row['cash_flow_class']=$class;$row['amount']=yovel_admin_finance_money($amount);$groups[$class]=bcadd($groups[$class],$amount,6);}unset($row);return ['date_from'=>$from,'date_to'=>$to,'rows'=>$rows,'operating'=>yovel_admin_finance_money($groups['OPERATING']),'investing'=>yovel_admin_finance_money($groups['INVESTING']),'financing'=>yovel_admin_finance_money($groups['FINANCING']),'net_cash_change'=>yovel_admin_finance_money(array_reduce($groups,fn($c,$v)=>bcadd($c,$v,6),'0'))];
}

function yovel_admin_budget_variance_report(array $company,string $budgetKey):array{return yovel_admin_budget_actuals($company,$budgetKey);}
function yovel_admin_receivables_report(array $company,string $asOf):array{return yovel_admin_receivable_aging($company,$asOf);}
function yovel_admin_payables_report(array $company,string $asOf):array{return yovel_admin_payable_aging($company,$asOf);}

function yovel_admin_bir_2550q_report(array $company,int $year,int $quarter,array $adjustments=[]):array
{
    if($year<1900||$year>2500||$quarter<1||$quarter>4)throw new InvalidArgumentException('BIR VAT year or quarter is invalid.');$startMonth=(($quarter-1)*3)+1;$from=sprintf('%04d-%02d-01',$year,$startMonth);$to=(new DateTimeImmutable($from))->modify('+3 months -1 day')->format('Y-m-d');$hash=(string)$company['company_key_hash'];$docs=bx_db()->GetAll("SELECT * FROM project_company_finance_invoice WHERE company_key_hash=? AND document_status='SUBMITTED' AND posting_date BETWEEN ? AND ? ORDER BY posting_date,invoice_no",[$hash,$from,$to]);$sales=['vatable'=>'0.000000','government'=>'0.000000','zero'=>'0.000000','exempt'=>'0.000000','output'=>'0.000000','withheld'=>'0.000000'];$purchase=['services'=>'0.000000','capital'=>'0.000000','goods'=>'0.000000','input'=>'0.000000','non_creditable'=>'0.000000'];foreach($docs as $doc){if((string)$doc['document_type']==='SALES'){$sales['vatable']=bcadd($sales['vatable'],(string)$doc['taxable_sales'],6);$sales['government']=bcadd($sales['government'],(string)$doc['government_sales'],6);$sales['zero']=bcadd($sales['zero'],(string)$doc['zero_rated_sales'],6);$sales['exempt']=bcadd($sales['exempt'],(string)$doc['exempt_sales'],6);$sales['output']=bcadd($sales['output'],(string)$doc['vat_amount'],6);$sales['withheld']=bcadd($sales['withheld'],(string)$doc['creditable_vat_withheld'],6);}else{$taxes=bx_db()->GetAll('SELECT bir_classification,taxable_base,vat_amount,creditable_input_vat,non_creditable_input_vat FROM project_company_finance_invoice_tax WHERE company_key_hash=? AND invoice_key=?',[$hash,$doc['invoice_key']]);foreach($taxes as $tax){$bucket=(string)$tax['bir_classification']==='INPUT_CAPITAL'?'capital':((string)$tax['bir_classification']==='INPUT_GOODS'?'goods':'services');$purchase[$bucket]=bcadd($purchase[$bucket],(string)$tax['taxable_base']??'0',6);$purchase['input']=bcadd($purchase['input'],(string)$tax['creditable_input_vat'],6);$purchase['non_creditable']=bcadd($purchase['non_creditable'],(string)$tax['non_creditable_input_vat'],6);}}}$prior=yovel_admin_finance_money($adjustments['prior_input_tax_credit']??'0');$other=yovel_admin_finance_money($adjustments['other_adjustments']??'0');$allowable=bcadd($purchase['input'],$prior,6);$net=bcsub(bcsub(bcadd($sales['output'],$other,6),$allowable,6),$sales['withheld'],6);return ['report_name'=>'BIR Form 2550Q Review Worksheet','report_version'=>'April 2024 ENCS working computation','filing_status'=>strtoupper((string)($adjustments['filing_status']??'ORIGINAL')),'year'=>$year,'quarter'=>$quarter,'date_from'=>$from,'date_to'=>$to,'sales'=>$sales,'purchases'=>$purchase,'prior_input_tax_credit'=>$prior,'other_adjustments'=>$other,'allowable_input_tax'=>yovel_admin_finance_money($allowable),'net_vat_payable'=>bccomp($net,'0',6)>=0?yovel_admin_finance_money($net):'0.000000','excess_input_vat'=>bccomp($net,'0',6)<0?yovel_admin_finance_money(bcmul($net,'-1',6)):'0.000000','documents'=>$docs,'export_rows'=>yovel_admin_ph_vat_export_rows($docs)];
}
