<?php
$attendanceWorkspace = is_array($hrData['attendance'] ?? null) ? $hrData['attendance'] : [];
$attendanceRows = is_array($attendanceWorkspace['attendance'] ?? null) ? $attendanceWorkspace['attendance'] : [];
$checkinRows = is_array($attendanceWorkspace['checkins'] ?? null) ? $attendanceWorkspace['checkins'] : [];
$attendanceRequests = is_array($attendanceWorkspace['attendanceRequests'] ?? null) ? $attendanceWorkspace['attendanceRequests'] : [];
$shiftTypes = is_array($attendanceWorkspace['shiftTypes'] ?? null) ? $attendanceWorkspace['shiftTypes'] : [];
$shiftLocations = is_array($attendanceWorkspace['shiftLocations'] ?? null) ? $attendanceWorkspace['shiftLocations'] : [];
$shiftSchedules = is_array($attendanceWorkspace['shiftSchedules'] ?? null) ? $attendanceWorkspace['shiftSchedules'] : [];
$shiftAssignments = is_array($attendanceWorkspace['shiftAssignments'] ?? null) ? $attendanceWorkspace['shiftAssignments'] : [];
$shiftRequests = is_array($attendanceWorkspace['shiftRequests'] ?? null) ? $attendanceWorkspace['shiftRequests'] : [];
$overtimeTypes = is_array($attendanceWorkspace['overtimeTypes'] ?? null) ? $attendanceWorkspace['overtimeTypes'] : [];
$overtimeSlips = is_array($attendanceWorkspace['overtimeSlips'] ?? null) ? $attendanceWorkspace['overtimeSlips'] : [];
$attendanceEmployees = is_array($hrData['employees'] ?? null) ? $hrData['employees'] : [];
$attendanceFormState = is_array($activeModuleFormState ?? null) ? $activeModuleFormState : [];
$attendanceOldInput = is_array($attendanceFormState['input'] ?? null) ? $attendanceFormState['input'] : [];
$attendanceFailedAction = (string) ($attendanceFormState['action'] ?? '');
$attendanceOld = static fn (string $key, mixed $fallback = ''): mixed => array_key_exists($key, $attendanceOldInput) ? $attendanceOldInput[$key] : $fallback;
$attendanceOpen = static fn (string $action): bool => $attendanceFailedAction === $action;
$attendanceMode = strtolower(trim((string) ($_GET['mode'] ?? 'list')));
if (!in_array($attendanceMode, ['list', 'calendar', 'tool'], true)) {
    $attendanceMode = 'list';
}
$selectedDate = yovel_admin_optional_date((string) ($_GET['date'] ?? date('Y-m-d')), 'Selected attendance date');
$attendanceStatusCounts = array_fill_keys(['PRESENT', 'ABSENT', 'HALF_DAY', 'WORK_FROM_HOME', 'ON_LEAVE'], 0);
foreach ($attendanceRows as $row) {
    if ((string) ($row['attendance_date'] ?? '') === $selectedDate && isset($attendanceStatusCounts[(string) ($row['attendance_status'] ?? '')])) {
        $attendanceStatusCounts[(string) $row['attendance_status']]++;
    }
}
$attendanceInput = 'mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm';
$attendanceTextarea = 'mt-1 min-h-24 w-full rounded-md border bg-background px-3 py-2 text-sm';
$attendanceModalClass = 'fixed inset-0 z-40 grid place-items-center bg-background/80 p-4 backdrop-blur-sm';
$attendanceDialogClass = 'flex max-h-[calc(100dvh-2rem)] w-[calc(100vw-2rem)] max-w-3xl flex-col overflow-hidden rounded-lg border bg-popover shadow-lg';
$employeeOptions = static function (array $employees, string $selected = ''): void {
    foreach ($employees as $employee) {
        $key = (string) $employee['employee_key']; ?>
        <option value="<?= bx_h($key) ?>" <?= $selected === $key ? 'selected' : '' ?>><?= bx_h((string) $employee['employee_name']) ?> · <?= bx_h((string) $employee['employee_code']) ?></option>
    <?php }
};
?>

<style>
    .yovel-hr-attendance-layout > * { min-width: 0; }
    .yovel-hr-attendance-scroll { max-width: 100%; min-width: 0; overflow-x: auto; overscroll-behavior-inline: contain; }
    @media (min-width: 1280px) {
        .yovel-hr-attendance-layout { grid-template-columns: minmax(0, 12fr) minmax(16rem, 8fr); }
    }
    @media (max-width: 1279px) {
        .yovel-hr-attendance-layout { grid-template-columns: minmax(0, 1fr); }
    }
</style>

<div class="yovel-hr-attendance-layout grid min-h-0 gap-3">
    <section class="yovel-hr-panel min-w-0 overflow-hidden rounded-lg border bg-card" aria-labelledby="hr-attendance-title">
        <header class="border-b px-5 py-4">
            <div class="flex flex-wrap items-start justify-between gap-4">
                <div>
                    <h2 id="hr-attendance-title" class="text-base font-semibold">Shift &amp; Attendance</h2>
                    <p class="mt-1 text-sm leading-6 text-muted-foreground">Review raw check-ins, daily attendance, requests, schedules, and overtime without mixing source records.</p>
                </div>
                <div class="flex flex-wrap gap-2">
                    <button type="button" data-record-modal-open="hr-checkin-modal" class="inline-flex h-9 items-center gap-2 rounded-md border bg-background px-3 text-sm font-medium hover:bg-muted"><span class="material-symbols-rounded text-base" aria-hidden="true">fingerprint</span>Add Check-in</button>
                    <button type="button" data-record-modal-open="hr-attendance-modal" class="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground hover:bg-primary/90"><span class="material-symbols-rounded text-base" aria-hidden="true">fact_check</span>Mark Attendance</button>
                </div>
            </div>
        </header>

        <nav class="flex flex-wrap gap-1 border-b px-5 py-3" aria-label="Attendance workspace modes">
            <?php foreach (['list' => ['list_alt', 'List'], 'calendar' => ['calendar_month', 'Calendar'], 'tool' => ['checklist', 'Attendance Tool']] as $mode => [$icon, $label]): ?>
                <a data-attendance-mode="<?= bx_h($mode) ?>" href="./?view=hr&amp;section=attendance&amp;mode=<?= bx_h($mode) ?>" class="inline-flex h-9 items-center gap-2 rounded-md px-3 text-sm font-medium <?= $attendanceMode === $mode ? 'bg-secondary text-secondary-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground' ?>"><span class="material-symbols-rounded text-base" aria-hidden="true"><?= bx_h($icon) ?></span><?= bx_h($label) ?></a>
            <?php endforeach; ?>
        </nav>

        <div class="min-h-0 p-5">
            <?php if ($attendanceMode === 'calendar'): ?>
                <section data-attendance-mode="calendar" aria-labelledby="attendance-calendar-title">
                    <div class="flex flex-wrap items-end justify-between gap-3 border-b pb-4">
                        <div><h3 id="attendance-calendar-title" class="text-sm font-semibold">Daily Status</h3><p class="mt-1 text-xs text-muted-foreground">A clear company view for the selected attendance date.</p></div>
                        <form method="get" class="flex items-end gap-2"><input type="hidden" name="view" value="hr"><input type="hidden" name="section" value="attendance"><input type="hidden" name="mode" value="calendar"><label class="text-xs font-medium">Date<input type="date" name="date" value="<?= bx_h($selectedDate) ?>" class="mt-1 h-9 rounded-md border bg-background px-3 text-sm"></label><button class="h-9 rounded-md border px-3 text-sm font-medium" type="submit">Open</button></form>
                    </div>
                    <div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
                        <?php foreach ($attendanceStatusCounts as $status => $count): ?><div class="rounded-md border p-4"><p class="text-xs text-muted-foreground"><?= bx_h(ucwords(strtolower(str_replace('_', ' ', $status)))) ?></p><p class="mt-2 text-2xl font-semibold"><?= $count ?></p></div><?php endforeach; ?>
                    </div>
                    <div class="mt-5 grid divide-y rounded-md border">
                        <?php $selectedRows = array_values(array_filter($attendanceRows, static fn (array $row): bool => (string) ($row['attendance_date'] ?? '') === $selectedDate)); ?>
                        <?php if ($selectedRows === []): ?><p class="p-6 text-center text-sm text-muted-foreground">No attendance is marked for this date.</p><?php endif; ?>
                        <?php foreach ($selectedRows as $row): ?><div class="flex flex-wrap items-center justify-between gap-3 px-4 py-3"><div><p class="text-sm font-medium"><?= bx_h((string) $row['employee_name']) ?></p><p class="mt-0.5 text-xs text-muted-foreground"><?= bx_h((string) $row['employee_code']) ?> · <?= bx_h((string) $row['source_mode']) ?></p></div><span class="rounded-full bg-secondary px-2.5 py-1 text-xs font-medium"><?= bx_h((string) $row['attendance_status']) ?></span></div><?php endforeach; ?>
                    </div>
                </section>
            <?php elseif ($attendanceMode === 'tool'): ?>
                <section data-attendance-mode="tool" aria-labelledby="attendance-tool-title">
                    <div class="border-b pb-4"><h3 id="attendance-tool-title" class="text-sm font-semibold">Employee Attendance Tool</h3><p class="mt-1 text-xs leading-5 text-muted-foreground">Select employees and open Mark Attendance. The same confirmation and employee/date lock are used for single and bulk marking.</p></div>
                    <div class="mt-5 grid gap-2 sm:grid-cols-2">
                        <?php foreach ($attendanceEmployees as $employee): ?><label class="flex items-center gap-3 rounded-md border px-3 py-3 text-sm"><input type="checkbox" name="attendance_tool_employee[]" value="<?= bx_h((string) $employee['employee_key']) ?>"><span><span class="block font-medium"><?= bx_h((string) $employee['employee_name']) ?></span><span class="text-xs text-muted-foreground"><?= bx_h((string) $employee['employee_code']) ?></span></span></label><?php endforeach; ?>
                    </div>
                    <button type="button" data-record-modal-open="hr-attendance-tool-modal" class="mt-5 inline-flex h-9 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"><span class="material-symbols-rounded text-base" aria-hidden="true">done_all</span>Open bulk marking</button>
                </section>
            <?php else: ?>
                <section data-attendance-mode="list" aria-labelledby="attendance-list-title">
                    <div class="flex items-end justify-between gap-3 border-b pb-3"><div><h3 id="attendance-list-title" class="text-sm font-semibold">Attendance Records</h3><p class="mt-1 text-xs text-muted-foreground">One governed record per employee and date.</p></div><span class="rounded-full bg-secondary px-2.5 py-0.5 text-xs"><?= count($attendanceRows) ?> records</span></div>
                    <div class="yovel-hr-attendance-scroll">
                        <table class="w-full min-w-[48rem] text-left text-sm">
                            <thead class="text-xs text-muted-foreground"><tr><th class="px-3 py-3 font-medium">Date</th><th class="px-3 py-3 font-medium">Employee</th><th class="px-3 py-3 font-medium">Status</th><th class="px-3 py-3 font-medium">Hours</th><th class="px-3 py-3 font-medium">Source</th><th class="px-3 py-3 font-medium">Flags</th></tr></thead>
                            <tbody class="divide-y">
                                <?php if ($attendanceRows === []): ?><tr><td colspan="6" class="px-3 py-10 text-center text-sm text-muted-foreground">No attendance records yet. Add check-ins or mark attendance to begin.</td></tr><?php endif; ?>
                                <?php foreach ($attendanceRows as $row): ?><tr><td class="px-3 py-3 font-medium"><?= bx_h((string) $row['attendance_date']) ?></td><td class="px-3 py-3"><span class="block font-medium"><?= bx_h((string) $row['employee_name']) ?></span><span class="text-xs text-muted-foreground"><?= bx_h((string) $row['employee_code']) ?></span></td><td class="px-3 py-3"><span class="rounded-full bg-secondary px-2 py-0.5 text-xs"><?= bx_h((string) $row['attendance_status']) ?></span></td><td class="px-3 py-3 text-muted-foreground"><?= bx_h(number_format((float) $row['working_hours'], 2)) ?></td><td class="px-3 py-3"><span class="block text-xs font-medium"><?= bx_h((string) $row['source_mode']) ?></span><span class="block max-w-48 truncate text-xs text-muted-foreground"><?= bx_h((string) $row['source_reference']) ?></span></td><td class="px-3 py-3 text-xs text-muted-foreground"><?= (int) $row['late_entry'] === 1 ? 'Late' : '' ?><?= (int) $row['early_exit'] === 1 ? ((int) $row['late_entry'] === 1 ? ' · ' : '') . 'Early exit' : '' ?></td></tr><?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </section>
            <?php endif; ?>
        </div>
    </section>

    <aside class="yovel-hr-panel min-w-0 overflow-hidden rounded-lg border bg-card" aria-labelledby="hr-attendance-tools-title">
        <header class="border-b px-5 py-4"><h2 id="hr-attendance-tools-title" class="text-base font-semibold">Attendance Actions</h2><p class="mt-1 text-sm leading-6 text-muted-foreground">Requests, shift coverage, schedules, and overtime for this company.</p></header>
        <div class="grid gap-5 p-5">
            <section>
                <h3 class="text-xs font-semibold uppercase text-muted-foreground">Requests &amp; assignments</h3>
                <div class="mt-3 grid grid-cols-2 gap-2">
                    <button type="button" data-record-modal-open="hr-attendance-request-modal" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border bg-background px-3 text-sm font-medium hover:bg-muted"><span class="material-symbols-rounded text-base" aria-hidden="true">edit_calendar</span>Attendance request</button>
                    <button type="button" data-record-modal-open="hr-shift-assignment-modal" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border bg-background px-3 text-sm font-medium hover:bg-muted"><span class="material-symbols-rounded text-base" aria-hidden="true">badge</span>Assign shift</button>
                    <button type="button" data-record-modal-open="hr-shift-request-modal" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border bg-background px-3 text-sm font-medium hover:bg-muted"><span class="material-symbols-rounded text-base" aria-hidden="true">swap_horiz</span>Shift request</button>
                    <button type="button" data-record-modal-open="hr-overtime-modal" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border bg-background px-3 text-sm font-medium hover:bg-muted"><span class="material-symbols-rounded text-base" aria-hidden="true">more_time</span>Overtime slip</button>
                    <button type="button" data-record-modal-open="hr-shift-assignment-tool-modal" class="col-span-2 inline-flex min-h-10 items-center justify-center gap-2 rounded-md border bg-background px-3 text-sm font-medium hover:bg-muted"><span class="material-symbols-rounded text-base" aria-hidden="true">group_add</span>Shift Assignment Tool</button>
                </div>
            </section>
            <section class="border-t pt-5">
                <div class="flex items-center justify-between gap-3"><h3 class="text-sm font-semibold">Shift Masters</h3><span class="rounded-full bg-secondary px-2 py-0.5 text-xs"><?= count($shiftTypes) ?> shifts</span></div>
                <div class="mt-3 grid divide-y rounded-md border">
                    <?php if ($shiftTypes === []): ?><p class="p-3 text-sm text-muted-foreground">No shift types configured.</p><?php endif; ?>
                    <?php foreach (array_slice($shiftTypes, 0, 8) as $shift): ?><div class="flex items-center justify-between gap-3 px-3 py-3"><div class="min-w-0"><p class="truncate text-sm font-medium"><?= bx_h((string) $shift['shift_name']) ?></p><p class="mt-0.5 text-xs text-muted-foreground"><?= bx_h(substr((string) $shift['start_time'], 0, 5)) ?>–<?= bx_h(substr((string) $shift['end_time'], 0, 5)) ?> · <?= bx_h((string) $shift['timezone_name']) ?></p></div><span class="text-xs text-muted-foreground"><?= (int) $shift['enable_auto_attendance'] === 1 ? 'Auto' : 'Manual' ?></span></div><?php endforeach; ?>
                </div>
                <div class="mt-3 grid grid-cols-2 gap-2"><button type="button" data-record-modal-open="hr-shift-type-modal" class="h-9 rounded-md border text-sm font-medium hover:bg-muted">Add shift type</button><button type="button" data-record-modal-open="hr-shift-location-modal" class="h-9 rounded-md border text-sm font-medium hover:bg-muted">Add location</button><button type="button" data-record-modal-open="hr-shift-schedule-modal" class="h-9 rounded-md border text-sm font-medium hover:bg-muted">Add schedule</button><button type="button" data-record-modal-open="hr-overtime-type-modal" class="h-9 rounded-md border text-sm font-medium hover:bg-muted">Add overtime type</button></div>
            </section>
            <section class="border-t pt-5">
                <h3 class="text-sm font-semibold">Operational Snapshot</h3>
                <dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div class="rounded-md border p-3"><dt class="text-xs text-muted-foreground">Raw check-ins</dt><dd class="mt-1 text-lg font-semibold"><?= count($checkinRows) ?></dd></div><div class="rounded-md border p-3"><dt class="text-xs text-muted-foreground">Requests</dt><dd class="mt-1 text-lg font-semibold"><?= count($attendanceRequests) + count($shiftRequests) ?></dd></div><div class="rounded-md border p-3"><dt class="text-xs text-muted-foreground">Assignments</dt><dd class="mt-1 text-lg font-semibold"><?= count($shiftAssignments) ?></dd></div><div class="rounded-md border p-3"><dt class="text-xs text-muted-foreground">Payroll handoffs</dt><dd class="mt-1 text-lg font-semibold"><?= count($overtimeSlips) ?></dd></div></dl>
            </section>
        </div>
    </aside>
</div>

<?php
$modalHeader = static function (string $id, string $title, string $description): void { ?>
    <header class="flex items-start justify-between gap-4 border-b px-5 py-4"><div><h3 id="<?= bx_h($id) ?>" class="text-base font-semibold"><?= bx_h($title) ?></h3><p class="mt-1 text-sm text-muted-foreground"><?= bx_h($description) ?></p></div><button type="button" data-record-modal-close class="inline-flex size-8 items-center justify-center rounded-md border" aria-label="Close <?= bx_h($title) ?>">×</button></header>
<?php };
$modalHidden = static function (string $action): void { ?>
    <input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="<?= bx_h($action) ?>"><input type="hidden" name="module_view" value="hr"><input type="hidden" name="section" value="attendance">
<?php };
$modalActions = static function (string $label): void { ?>
    <div class="mt-5 flex justify-end gap-2 border-t pt-4"><button type="button" data-record-modal-close class="h-9 rounded-md border px-3 text-sm">Cancel</button><button type="submit" class="h-9 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"><?= bx_h($label) ?></button></div>
<?php };
?>

<div id="hr-checkin-modal" data-record-modal <?= $attendanceOpen('hr_attendance_save_checkin') ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-checkin-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-checkin-title', 'Add Employee Check-in', 'Keep the raw time event separate from derived attendance.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_save_checkin'); ?><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium sm:col-span-2">Employee<select name="employee_key" class="<?= $attendanceInput ?>" required><option value="">Select employee</option><?php $employeeOptions($attendanceEmployees, (string) $attendanceOld('employee_key')); ?></select></label><label class="text-sm font-medium">Log type<select name="log_type" class="<?= $attendanceInput ?>" required><option value="IN">IN</option><option value="OUT" <?= (string) $attendanceOld('log_type') === 'OUT' ? 'selected' : '' ?>>OUT</option></select></label><label class="text-sm font-medium">Time zone<input name="timezone_name" value="<?= bx_h((string) $attendanceOld('timezone_name', 'Asia/Manila')) ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Check-in time<input name="checkin_at" value="<?= bx_h((string) $attendanceOld('checkin_at', date('Y-m-d H:i:s'))) ?>" placeholder="YYYY-MM-DD HH:MM:SS" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Device ID<input name="device_id" value="<?= bx_h((string) $attendanceOld('device_id')) ?>" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium">Source system<input name="source_system" value="<?= bx_h((string) $attendanceOld('source_system', 'MANUAL')) ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Source reference<input name="source_reference" value="<?= bx_h((string) $attendanceOld('source_reference', 'MANUAL-' . date('YmdHis'))) ?>" class="<?= $attendanceInput ?>" required></label></div><?php $modalActions('Save Check-in'); ?></form></section></div>

<div id="hr-attendance-modal" data-record-modal <?= $attendanceOpen('hr_attendance_mark') ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-attendance-mark-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-attendance-mark-title', 'Mark Attendance', 'Create or correct the single governed employee/date record.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_mark'); ?><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium sm:col-span-2">Employee<select name="employee_key" class="<?= $attendanceInput ?>" required><option value="">Select employee</option><?php $employeeOptions($attendanceEmployees, (string) $attendanceOld('employee_key')); ?></select></label><label class="text-sm font-medium">Attendance date<input type="date" name="attendance_date" value="<?= bx_h((string) $attendanceOld('attendance_date', date('Y-m-d'))) ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Status<select name="attendance_status" class="<?= $attendanceInput ?>" required><?php foreach (['PRESENT','ABSENT','HALF_DAY','WORK_FROM_HOME','ON_LEAVE'] as $status): ?><option value="<?= $status ?>" <?= (string) $attendanceOld('attendance_status', 'PRESENT') === $status ? 'selected' : '' ?>><?= bx_h(ucwords(strtolower(str_replace('_', ' ', $status)))) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium sm:col-span-2">Source reference<input name="source_reference" value="<?= bx_h((string) $attendanceOld('source_reference', 'MANUAL-' . date('Ymd'))) ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium sm:col-span-2">Remarks<textarea name="remarks" class="<?= $attendanceTextarea ?>"><?= bx_h((string) $attendanceOld('remarks')) ?></textarea></label></div><?php $modalActions('Mark Attendance'); ?></form></section></div>

<div id="hr-attendance-tool-modal" data-record-modal <?= $attendanceOpen('hr_attendance_bulk_mark') ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-attendance-tool-modal-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-attendance-tool-modal-title', 'Employee Attendance Tool', 'Mark several employees in one locked, audited transaction.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_bulk_mark'); ?><div class="grid gap-4 sm:grid-cols-2"><fieldset class="sm:col-span-2"><legend class="text-sm font-medium">Employees</legend><div class="mt-2 grid max-h-52 gap-2 overflow-y-auto rounded-md border p-3 sm:grid-cols-2"><?php foreach ($attendanceEmployees as $employee): ?><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="employee_keys[]" value="<?= bx_h((string) $employee['employee_key']) ?>"><span><?= bx_h((string) $employee['employee_name']) ?></span></label><?php endforeach; ?></div></fieldset><label class="text-sm font-medium">Attendance date<input type="date" name="attendance_date" value="<?= date('Y-m-d') ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Status<select name="attendance_status" class="<?= $attendanceInput ?>"><option value="PRESENT">Present</option><option value="ABSENT">Absent</option><option value="HALF_DAY">Half Day</option><option value="WORK_FROM_HOME">Work From Home</option></select></label><label class="text-sm font-medium sm:col-span-2">Batch source reference<input name="source_reference" value="ATTENDANCE-TOOL-<?= date('YmdHis') ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium sm:col-span-2">Remarks<textarea name="remarks" class="<?= $attendanceTextarea ?>"></textarea></label></div><?php $modalActions('Mark Selected Employees'); ?></form></section></div>

<div id="hr-attendance-request-modal" data-record-modal <?= $attendanceOpen('hr_attendance_save_request') ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-attendance-request-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-attendance-request-title', 'Attendance Request', 'Request Work From Home or On Duty attendance for a date range.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_save_request'); ?><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium sm:col-span-2">Employee<select name="employee_key" class="<?= $attendanceInput ?>" required><option value="">Select employee</option><?php $employeeOptions($attendanceEmployees, (string) $attendanceOld('employee_key')); ?></select></label><label class="text-sm font-medium">From date<input type="date" name="from_date" value="<?= bx_h((string) $attendanceOld('from_date', date('Y-m-d'))) ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">To date<input type="date" name="to_date" value="<?= bx_h((string) $attendanceOld('to_date', date('Y-m-d'))) ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Reason<select name="reason" class="<?= $attendanceInput ?>"><option value="WORK_FROM_HOME">Work From Home</option><option value="ON_DUTY">On Duty</option></select></label><label class="text-sm font-medium">Status<select name="request_status" class="<?= $attendanceInput ?>"><option value="DRAFT">Draft</option></select></label><label class="text-sm font-medium sm:col-span-2">Explanation<textarea name="explanation" class="<?= $attendanceTextarea ?>"><?= bx_h((string) $attendanceOld('explanation')) ?></textarea></label></div><?php $modalActions('Save Request'); ?></form></section></div>

<div id="hr-shift-assignment-modal" data-record-modal <?= $attendanceOpen('hr_attendance_save_assignment') ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-shift-assignment-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-shift-assignment-title', 'Assign Shift', 'Assign a shift type or schedule with an effective date range.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_save_assignment'); ?><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium sm:col-span-2">Employee<select name="employee_key" class="<?= $attendanceInput ?>" required><option value="">Select employee</option><?php $employeeOptions($attendanceEmployees, (string) $attendanceOld('employee_key')); ?></select></label><label class="text-sm font-medium">Shift type<select name="shift_type_key" class="<?= $attendanceInput ?>" required><option value="">Select shift</option><?php foreach ($shiftTypes as $shift): ?><option value="<?= bx_h((string) $shift['shift_type_key']) ?>"><?= bx_h((string) $shift['shift_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Schedule<select name="shift_schedule_key" class="<?= $attendanceInput ?>"><option value="">None</option><?php foreach ($shiftSchedules as $schedule): ?><option value="<?= bx_h((string) $schedule['shift_schedule_key']) ?>"><?= bx_h((string) $schedule['schedule_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Location<select name="shift_location_key" class="<?= $attendanceInput ?>"><option value="">None</option><?php foreach ($shiftLocations as $location): ?><option value="<?= bx_h((string) $location['shift_location_key']) ?>"><?= bx_h((string) $location['location_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Status<select name="assignment_status" class="<?= $attendanceInput ?>"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label class="text-sm font-medium">Start date<input type="date" name="start_date" value="<?= bx_h((string) $attendanceOld('start_date', date('Y-m-d'))) ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">End date<input type="date" name="end_date" value="<?= bx_h((string) $attendanceOld('end_date')) ?>" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium sm:col-span-2">Source reference<input name="source_reference" value="<?= bx_h((string) $attendanceOld('source_reference', 'SHIFT-' . date('YmdHis'))) ?>" class="<?= $attendanceInput ?>" required></label></div><?php $modalActions('Save Assignment'); ?></form></section></div>

<div id="hr-shift-assignment-tool-modal" data-record-modal <?= $attendanceOpen('hr_attendance_bulk_assignment') ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-shift-assignment-tool-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-shift-assignment-tool-title', 'Shift Assignment Tool', 'Assign one shift pattern to several employees in one transaction.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_bulk_assignment'); ?><div class="grid gap-4 sm:grid-cols-2"><fieldset class="sm:col-span-2"><legend class="text-sm font-medium">Employees</legend><div class="mt-2 grid max-h-52 gap-2 overflow-y-auto rounded-md border p-3 sm:grid-cols-2"><?php foreach ($attendanceEmployees as $employee): ?><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="employee_keys[]" value="<?= bx_h((string) $employee['employee_key']) ?>"><span><?= bx_h((string) $employee['employee_name']) ?></span></label><?php endforeach; ?></div></fieldset><label class="text-sm font-medium">Shift type<select name="shift_type_key" class="<?= $attendanceInput ?>" required><option value="">Select shift</option><?php foreach ($shiftTypes as $shift): ?><option value="<?= bx_h((string) $shift['shift_type_key']) ?>"><?= bx_h((string) $shift['shift_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Schedule<select name="shift_schedule_key" class="<?= $attendanceInput ?>"><option value="">None</option><?php foreach ($shiftSchedules as $schedule): ?><option value="<?= bx_h((string) $schedule['shift_schedule_key']) ?>"><?= bx_h((string) $schedule['schedule_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Location<select name="shift_location_key" class="<?= $attendanceInput ?>"><option value="">None</option><?php foreach ($shiftLocations as $location): ?><option value="<?= bx_h((string) $location['shift_location_key']) ?>"><?= bx_h((string) $location['location_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Status<select name="assignment_status" class="<?= $attendanceInput ?>"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label class="text-sm font-medium">Start date<input type="date" name="start_date" value="<?= date('Y-m-d') ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">End date<input type="date" name="end_date" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium sm:col-span-2">Batch source reference<input name="source_reference" value="SHIFT-TOOL-<?= date('YmdHis') ?>" class="<?= $attendanceInput ?>" required></label></div><?php $modalActions('Assign Selected Employees'); ?></form></section></div>

<div id="hr-shift-request-modal" data-record-modal <?= $attendanceOpen('hr_attendance_save_shift_request') ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-shift-request-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-shift-request-title', 'Shift Request', 'Request a shift assignment for an employee and approver.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_save_shift_request'); ?><input type="hidden" name="approver_admin_key" value="<?= bx_h((string) ($admin['admin_key'] ?? '')) ?>"><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium sm:col-span-2">Employee<select name="employee_key" class="<?= $attendanceInput ?>" required><option value="">Select employee</option><?php $employeeOptions($attendanceEmployees, (string) $attendanceOld('employee_key')); ?></select></label><label class="text-sm font-medium">Shift type<select name="shift_type_key" class="<?= $attendanceInput ?>" required><option value="">Select shift</option><?php foreach ($shiftTypes as $shift): ?><option value="<?= bx_h((string) $shift['shift_type_key']) ?>"><?= bx_h((string) $shift['shift_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Status<select name="request_status" class="<?= $attendanceInput ?>"><option value="DRAFT">Draft</option></select></label><label class="text-sm font-medium">From date<input type="date" name="from_date" value="<?= bx_h((string) $attendanceOld('from_date', date('Y-m-d'))) ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">To date<input type="date" name="to_date" value="<?= bx_h((string) $attendanceOld('to_date')) ?>" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium sm:col-span-2">Reason<textarea name="reason" class="<?= $attendanceTextarea ?>"><?= bx_h((string) $attendanceOld('reason')) ?></textarea></label></div><?php $modalActions('Save Shift Request'); ?></form></section></div>

<div id="hr-shift-schedule-modal" data-record-modal <?= $attendanceOpen('hr_attendance_save_master') && strtoupper((string) ($attendanceOldInput['record_type'] ?? '')) === 'SHIFT_SCHEDULE' ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-shift-schedule-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-shift-schedule-title', 'Add Shift Schedule', 'Define a repeating weekly pattern for one shift type.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_save_master'); ?><input type="hidden" name="record_type" value="SHIFT_SCHEDULE"><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Schedule code<input name="schedule_code" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Schedule name<input name="schedule_name" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Shift type<select name="shift_type_key" class="<?= $attendanceInput ?>" required><option value="">Select shift</option><?php foreach ($shiftTypes as $shift): ?><option value="<?= bx_h((string) $shift['shift_type_key']) ?>"><?= bx_h((string) $shift['shift_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Frequency<select name="frequency_weeks" class="<?= $attendanceInput ?>"><?php for ($week = 1; $week <= 4; $week++): ?><option value="<?= $week ?>">Every <?= $week ?> week<?= $week > 1 ? 's' : '' ?></option><?php endfor; ?></select></label><fieldset class="sm:col-span-2"><legend class="text-sm font-medium">Repeat on</legend><div class="mt-2 flex flex-wrap gap-3"><?php foreach (['MON','TUE','WED','THU','FRI','SAT','SUN'] as $day): ?><label class="flex items-center gap-1.5 text-sm"><input type="checkbox" name="repeat_days[]" value="<?= $day ?>" <?= in_array($day, ['MON','TUE','WED','THU','FRI'], true) ? 'checked' : '' ?>><?= $day ?></label><?php endforeach; ?></div></fieldset><input type="hidden" name="schedule_status" value="ACTIVE"></div><?php $modalActions('Save Schedule'); ?></form></section></div>

<div id="hr-overtime-modal" data-record-modal <?= $attendanceOpen('hr_attendance_save_overtime') ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-overtime-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-overtime-title', 'Add Overtime Slip', 'Record validated overtime details for a future Payroll handoff.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_save_overtime'); ?><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium sm:col-span-2">Employee<select name="employee_key" class="<?= $attendanceInput ?>" required><option value="">Select employee</option><?php $employeeOptions($attendanceEmployees, (string) $attendanceOld('employee_key')); ?></select></label><label class="text-sm font-medium">Posting date<input type="date" name="posting_date" value="<?= date('Y-m-d') ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Status<select name="slip_status" class="<?= $attendanceInput ?>"><option value="DRAFT">Draft</option><option value="SUBMITTED">Submitted</option></select></label><label class="text-sm font-medium">Period start<input type="date" name="start_date" value="<?= date('Y-m-d') ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Period end<input type="date" name="end_date" value="<?= date('Y-m-d') ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Overtime date<input type="date" name="overtime_date" value="<?= date('Y-m-d') ?>" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Overtime type<select name="overtime_type_key" class="<?= $attendanceInput ?>" required><option value="">Select type</option><?php foreach ($overtimeTypes as $type): ?><option value="<?= bx_h((string) $type['overtime_type_key']) ?>"><?= bx_h((string) $type['overtime_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Overtime hours<input type="number" min="0.01" max="24" step="0.25" name="overtime_hours" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Standard working hours<input type="number" min="0.01" max="24" step="0.25" name="standard_working_hours" value="8" class="<?= $attendanceInput ?>" required></label></div><?php $modalActions('Save Overtime Slip'); ?></form></section></div>

<div id="hr-shift-type-modal" data-record-modal <?= $attendanceOpen('hr_attendance_save_master') && strtoupper((string) ($attendanceOldInput['record_type'] ?? '')) === 'SHIFT_TYPE' ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-shift-type-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-shift-type-title', 'Add Shift Type', 'Set time-zone aware shift windows and auto-attendance thresholds.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_save_master'); ?><input type="hidden" name="record_type" value="SHIFT_TYPE"><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Shift code<input name="shift_code" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Shift name<input name="shift_name" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Start time<input type="time" step="60" name="start_time" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">End time<input type="time" step="60" name="end_time" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Time zone<input name="timezone_name" value="Asia/Manila" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Check in before (minutes)<input type="number" min="0" max="1440" name="begin_checkin_before_minutes" value="60" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium">Check out after (minutes)<input type="number" min="0" max="1440" name="allow_checkout_after_minutes" value="60" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium">Half-day threshold<input type="number" min="0" max="24" step="0.25" name="half_day_threshold_hours" value="4" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium">Absent threshold<input type="number" min="0" max="24" step="0.25" name="absent_threshold_hours" value="2" class="<?= $attendanceInput ?>"></label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="enable_auto_attendance" value="1">Enable auto attendance</label><input type="hidden" name="shift_status" value="ACTIVE"></div><?php $modalActions('Save Shift Type'); ?></form></section></div>

<div id="hr-shift-location-modal" data-record-modal <?= $attendanceOpen('hr_attendance_save_master') && strtoupper((string) ($attendanceOldInput['record_type'] ?? '')) === 'SHIFT_LOCATION' ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-shift-location-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-shift-location-title', 'Add Shift Location', 'Set an optional check-in radius and coordinates.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_save_master'); ?><input type="hidden" name="record_type" value="SHIFT_LOCATION"><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium sm:col-span-2">Location name<input name="location_name" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Check-in radius (meters)<input type="number" min="0" max="100000" name="checkin_radius" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium">Status<select name="location_status" class="<?= $attendanceInput ?>"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label class="text-sm font-medium">Latitude<input type="number" min="-90" max="90" step="0.0000001" name="latitude" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium">Longitude<input type="number" min="-180" max="180" step="0.0000001" name="longitude" class="<?= $attendanceInput ?>"></label></div><?php $modalActions('Save Location'); ?></form></section></div>

<div id="hr-overtime-type-modal" data-record-modal <?= $attendanceOpen('hr_attendance_save_master') && strtoupper((string) ($attendanceOldInput['record_type'] ?? '')) === 'OVERTIME_TYPE' ? 'data-record-modal-open-on-load' : '' ?> class="<?= $attendanceModalClass ?>" role="dialog" aria-modal="true" aria-labelledby="hr-overtime-type-title" hidden><section class="<?= $attendanceDialogClass ?>"><?php $modalHeader('hr-overtime-type-title', 'Add Overtime Type', 'Define HR-side calculation metadata without writing Payroll records.'); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $modalHidden('hr_attendance_save_master'); ?><input type="hidden" name="record_type" value="OVERTIME_TYPE"><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Code<input name="overtime_code" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Name<input name="overtime_name" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Calculation<select name="calculation_method" class="<?= $attendanceInput ?>"><option value="FIXED_HOURLY_RATE">Fixed hourly rate</option><option value="SALARY_COMPONENT_BASED">Salary component based</option></select></label><label class="text-sm font-medium">Hourly rate<input type="number" min="0" step="0.01" name="hourly_rate" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium">Standard multiplier<input type="number" min="0.01" step="0.01" name="standard_multiplier" value="1" class="<?= $attendanceInput ?>" required></label><label class="text-sm font-medium">Maximum hours<input type="number" min="0.01" max="24" step="0.25" name="maximum_hours" class="<?= $attendanceInput ?>"></label><label class="text-sm font-medium sm:col-span-2">Salary component reference<input name="salary_component_reference" class="<?= $attendanceInput ?>"></label><input type="hidden" name="overtime_status" value="ACTIVE"></div><?php $modalActions('Save Overtime Type'); ?></form></section></div>
