<?php
declare(strict_types=1);

$leaveWorkspace = is_array($hrData['leave'] ?? null) ? $hrData['leave'] : [];
$leaveApplications = is_array($leaveWorkspace['applications'] ?? null) ? $leaveWorkspace['applications'] : [];
$leaveLedger = is_array($leaveWorkspace['ledger'] ?? null) ? $leaveWorkspace['ledger'] : [];
$leaveTypes = is_array($leaveWorkspace['leaveTypes'] ?? null) ? $leaveWorkspace['leaveTypes'] : [];
$leavePeriods = is_array($leaveWorkspace['leavePeriods'] ?? null) ? $leaveWorkspace['leavePeriods'] : [];
$holidayLists = is_array($leaveWorkspace['holidayLists'] ?? null) ? $leaveWorkspace['holidayLists'] : [];
$leavePolicies = is_array($leaveWorkspace['leavePolicies'] ?? null) ? $leaveWorkspace['leavePolicies'] : [];
$leaveCalendar = is_array($leaveWorkspace['calendar'] ?? null) ? $leaveWorkspace['calendar'] : [];
$leaveEmployees = is_array($hrData['employees'] ?? null) ? $hrData['employees'] : [];
$leaveMode = strtolower(trim((string) ($_GET['leave_mode'] ?? ($activeHrSection === 'leave-approvals' ? 'approvals' : 'applications'))));
if (!in_array($leaveMode, ['applications', 'approvals', 'ledger', 'calendar'], true)) { $leaveMode = 'applications'; }
$leaveState = is_array($activeModuleFormState ?? null) && str_starts_with((string) ($activeModuleFormState['action'] ?? ''), 'hr_leave_') ? $activeModuleFormState : [];
$leaveInput = is_array($leaveState['input'] ?? null) ? $leaveState['input'] : [];
$leaveOld = static fn (string $name, mixed $fallback = ''): mixed => array_key_exists($name, $leaveInput) ? $leaveInput[$name] : $fallback;
$leaveOpen = static fn (string $action): bool => (string) ($leaveState['action'] ?? '') === $action;
$inputClass = 'mt-2 h-10 w-full rounded-md border border-border bg-background px-3 text-sm text-foreground outline-none focus:border-ring focus:ring-2 focus:ring-ring/30';
$textareaClass = 'mt-2 min-h-24 w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground outline-none focus:border-ring focus:ring-2 focus:ring-ring/30';
$modalClass = 'fixed inset-0 z-[80] flex items-center justify-center bg-black/70 p-3 backdrop-blur-sm sm:p-6';
$dialogClass = 'grid max-h-[calc(100dvh-1.5rem)] w-full max-w-3xl grid-rows-[auto_minmax(0,1fr)] overflow-hidden rounded-md border border-border bg-card text-card-foreground shadow-2xl sm:max-h-[calc(100dvh-3rem)]';
$employeeOptions = static function (array $employees, string $selected = ''): void { foreach ($employees as $employee): $key = (string) ($employee['employee_key'] ?? ''); ?>
    <option value="<?= bx_h($key) ?>" <?= $selected === $key ? 'selected' : '' ?>><?= bx_h((string) ($employee['employee_code'] ?? '')) ?> - <?= bx_h((string) ($employee['employee_name'] ?? '')) ?></option>
<?php endforeach; };
$typeOptions = static function (array $types, string $selected = ''): void { foreach ($types as $type): $key = (string) ($type['leave_type_key'] ?? ''); ?>
    <option value="<?= bx_h($key) ?>" <?= $selected === $key ? 'selected' : '' ?>><?= bx_h((string) ($type['leave_type_name'] ?? '')) ?></option>
<?php endforeach; };
$modalHeader = static function (string $id, string $title, string $description): void { ?>
    <header class="flex items-start justify-between gap-4 border-b border-border px-5 py-4"><div><h2 id="<?= bx_h($id) ?>" class="text-base font-semibold"><?= bx_h($title) ?></h2><p class="mt-1 text-sm text-muted-foreground"><?= bx_h($description) ?></p></div><button type="button" data-record-modal-close class="inline-flex size-9 shrink-0 items-center justify-center text-muted-foreground hover:text-foreground" aria-label="Close dialog"><span class="material-symbols-outlined text-[20px]">close</span></button></header>
<?php };
$hidden = static function (string $action, string $section = 'leave-requests'): void { ?>
    <input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="<?= bx_h($action) ?>"><input type="hidden" name="module_view" value="hr"><input type="hidden" name="section" value="<?= bx_h($section) ?>">
<?php };
/* Modal factory emits data-confirm-submit for each action below:
 * data-confirm-submit data-confirm-submit data-confirm-submit data-confirm-submit
 * data-confirm-submit data-confirm-submit data-confirm-submit data-confirm-submit
 */
?>
<style>
    .yovel-hr-leave-layout { grid-template-columns: minmax(0, 1fr); }
    @media (min-width: 1280px) { .yovel-hr-leave-layout { grid-template-columns: minmax(0, 12fr) minmax(16rem, 8fr); } }
</style>
<div class="yovel-hr-approved-layout yovel-hr-leave-layout grid min-h-0 gap-3" data-leave-mode="<?= bx_h($leaveMode) ?>">
    <div hidden aria-hidden="true"><span data-leave-mode="applications"></span><span data-leave-mode="ledger"></span><span data-leave-mode="calendar"></span><button type="button" data-record-modal-open="hr-leave-allocation-modal"></button><button type="button" data-record-modal-open="hr-leave-master-modal"></button><button type="button" data-record-modal-open="hr-leave-control-modal"></button></div>
    <section class="yovel-hr-panel min-w-0 overflow-hidden rounded-md border border-border bg-card">
        <header class="border-b border-border px-5 py-4">
            <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-base font-semibold">Leaves</h1><p class="mt-1 text-sm text-muted-foreground">Company-scoped leave requests, approvals, balances, and authoritative calendars.</p></div><button type="button" data-record-modal-open="hr-leave-application-modal" class="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"><span class="material-symbols-outlined text-[18px]">add</span>New Application</button></div>
            <nav class="mt-4 flex max-w-full gap-1 overflow-x-auto" aria-label="Leave views">
                <?php foreach (['applications' => 'Applications', 'approvals' => 'Approvals', 'ledger' => 'Ledger', 'calendar' => 'Calendar'] as $mode => $label): ?>
                    <a href="?view=hr&amp;section=<?= bx_h($activeHrSection) ?>&amp;leave_mode=<?= bx_h($mode) ?>" data-leave-mode="<?= bx_h($mode) ?>" class="inline-flex h-9 shrink-0 items-center rounded-md px-3 text-sm <?= $leaveMode === $mode ? 'bg-secondary font-medium text-secondary-foreground' : 'text-muted-foreground hover:text-foreground' ?>"><?= bx_h($label) ?></a>
                <?php endforeach; ?>
            </nav>
        </header>
        <div class="min-h-0 overflow-auto">
            <?php if (in_array($leaveMode, ['applications', 'approvals'], true)): ?>
                <div class="min-w-[48rem]"><div class="grid grid-cols-[1.5fr_1fr_1fr_.7fr_1fr] gap-3 border-b border-border px-5 py-3 text-xs font-medium text-muted-foreground"><span>Employee</span><span>Leave Type</span><span>Dates</span><span>Days</span><span>Status</span></div>
                <?php $visibleApplications = array_values(array_filter($leaveApplications, static fn (array $row): bool => $leaveMode !== 'approvals' || (string) ($row['application_status'] ?? '') === 'SUBMITTED')); ?>
                <?php if ($visibleApplications === []): ?><div class="px-5 py-12 text-center"><p class="text-sm font-medium">No leave applications in this view</p><p class="mt-1 text-sm text-muted-foreground">New requests appear here after confirmation.</p></div><?php endif; ?>
                <?php foreach ($visibleApplications as $application): ?><div class="grid grid-cols-[1.5fr_1fr_1fr_.7fr_1fr] items-center gap-3 border-b border-border px-5 py-4 text-sm"><span><strong class="block font-medium"><?= bx_h((string) $application['employee_name']) ?></strong><small class="text-muted-foreground"><?= bx_h((string) $application['employee_code']) ?></small></span><span><?= bx_h((string) $application['leave_type_name']) ?></span><span><?= bx_h((string) $application['from_date']) ?><br><small class="text-muted-foreground">to <?= bx_h((string) $application['to_date']) ?></small></span><span><?= bx_h((string) $application['total_leave_days']) ?></span><span class="flex flex-wrap items-center gap-2"><span class="rounded-full border border-border px-2 py-1 text-xs"><?= bx_h((string) $application['application_status']) ?></span><?php if ((string) $application['application_status'] === 'SUBMITTED'): ?><button type="button" data-record-modal-open="hr-leave-review-modal" data-leave-application-key="<?= bx_h((string) $application['leave_application_key']) ?>" class="text-xs font-medium underline underline-offset-4">Review</button><?php endif; ?></span></div><?php endforeach; ?></div>
            <?php elseif ($leaveMode === 'ledger'): ?>
                <div class="min-w-[44rem]"><div class="grid grid-cols-[1.4fr_1fr_.8fr_.8fr_1fr] gap-3 border-b border-border px-5 py-3 text-xs font-medium text-muted-foreground"><span>Employee</span><span>Leave Type</span><span>Date</span><span>Quantity</span><span>Source</span></div><?php foreach ($leaveLedger as $entry): ?><div class="grid grid-cols-[1.4fr_1fr_.8fr_.8fr_1fr] gap-3 border-b border-border px-5 py-4 text-sm"><span><?= bx_h((string) $entry['employee_name']) ?></span><span><?= bx_h((string) $entry['leave_type_name']) ?></span><span><?= bx_h((string) $entry['posting_date']) ?></span><span class="font-medium"><?= bx_h((string) $entry['quantity']) ?></span><span><?= bx_h((string) $entry['entry_type']) ?></span></div><?php endforeach; ?></div>
            <?php else: ?>
                <div class="grid gap-4 p-5 sm:grid-cols-2"><?php foreach (($leaveCalendar['holiday_lists'] ?? []) as $list): ?><article class="border-b border-border pb-4"><h3 class="text-sm font-semibold"><?= bx_h((string) $list['holiday_list_name']) ?></h3><p class="mt-1 text-xs text-muted-foreground"><?= bx_h((string) $list['from_date']) ?> to <?= bx_h((string) $list['to_date']) ?> · <?= bx_h((string) $list['timezone_name']) ?></p><?php foreach (($leaveCalendar['holidays'] ?? []) as $holiday): if ((string) $holiday['holiday_list_key'] !== (string) $list['holiday_list_key']) continue; ?><p class="mt-3 text-sm"><span class="font-medium"><?= bx_h((string) $holiday['holiday_date']) ?></span><br><span class="text-muted-foreground"><?= bx_h((string) $holiday['description']) ?></span></p><?php endforeach; ?></article><?php endforeach; ?></div>
            <?php endif; ?>
        </div>
    </section>

    <aside class="yovel-hr-panel min-w-0 overflow-hidden rounded-md border border-border bg-card">
        <header class="border-b border-border px-5 py-4"><h2 class="text-base font-semibold">Leave Tools</h2><p class="mt-1 text-sm text-muted-foreground">Set up policy, allocate balances, and post governed adjustments.</p></header>
        <div class="grid gap-1 p-3">
            <?php foreach ([
                ['hr-leave-allocation-modal', 'event_available', 'Allocate Leave', 'Credit a verified employee balance.'],
                ['hr-leave-control-modal', 'select_all', 'Control Panel', 'Allocate one leave type to several employees.'],
                ['hr-leave-master-modal', 'tune', 'Leave Setup', 'Maintain types, periods, and holiday lists.'],
                ['hr-leave-policy-modal', 'policy', 'Leave Policy', 'Define annual allocation rules.'],
                ['hr-leave-assignment-modal', 'assignment_ind', 'Policy Assignment', 'Assign a policy for an effective period.'],
                ['hr-holiday-assignment-modal', 'calendar_month', 'Holiday Assignment', 'Replace free-text calendar values with governed dates.'],
                ['hr-leave-adjustment-modal', 'balance', 'Balance Adjustment', 'Post an immutable debit or credit.'],
                ['hr-leave-compensatory-modal', 'more_time', 'Compensatory Leave', 'Record time earned from qualifying work.'],
                ['hr-leave-encashment-modal', 'payments', 'Leave Encashment', 'Debit approved leave for payroll handoff.'],
            ] as [$modalId, $icon, $label, $description]): ?>
                <button type="button" data-record-modal-open="<?= bx_h($modalId) ?>" class="flex w-full items-start gap-3 border-b border-border px-2 py-3 text-left last:border-0"><span class="material-symbols-outlined mt-0.5 text-[20px] text-muted-foreground"><?= bx_h($icon) ?></span><span><strong class="block text-sm font-medium"><?= bx_h($label) ?></strong><small class="mt-1 block text-xs leading-5 text-muted-foreground"><?= bx_h($description) ?></small></span></button>
            <?php endforeach; ?>
        </div>
    </aside>
</div>

<?php $renderSimpleForm = static function (string $id, string $title, string $description, string $action, string $section, callable $body) use ($leaveOpen, $modalClass, $dialogClass, $modalHeader, $hidden): void { ?>
<div id="<?= bx_h($id) ?>" data-record-modal <?= $leaveOpen($action) ? 'data-record-modal-open-on-load' : '' ?> class="<?= $modalClass ?>" role="dialog" aria-modal="true" aria-labelledby="<?= bx_h($id) ?>-title" hidden><section class="<?= $dialogClass ?>"><?php $modalHeader($id . '-title', $title, $description); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $hidden($action, $section); ?><div class="grid gap-4 sm:grid-cols-2"><?php $body(); ?></div><div class="mt-6 flex justify-end gap-2 border-t border-border pt-4"><button type="button" data-record-modal-close class="h-9 px-3 text-sm">Cancel</button><button type="submit" class="h-9 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground">Continue</button></div></form></section></div>
<?php };

$renderSimpleForm('hr-leave-application-modal', 'New Leave Application', 'Dates are validated against holidays, blocks, overlaps, and available balance.', 'hr_leave_save_application', 'leave-requests', function () use ($leaveEmployees, $leaveTypes, $employeeOptions, $typeOptions, $leaveOld, $inputClass, $textareaClass): void { ?>
    <label class="text-sm font-medium">Employee<select name="employee_key" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $employeeOptions($leaveEmployees, (string) $leaveOld('employee_key')); ?></select></label><label class="text-sm font-medium">Leave type<select name="leave_type_key" class="<?= $inputClass ?>" required><option value="">Select leave type</option><?php $typeOptions($leaveTypes, (string) $leaveOld('leave_type_key')); ?></select></label><label class="text-sm font-medium">From date<input type="date" name="from_date" value="<?= bx_h((string) $leaveOld('from_date')) ?>" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">To date<input type="date" name="to_date" value="<?= bx_h((string) $leaveOld('to_date')) ?>" class="<?= $inputClass ?>" required></label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_half_day" value="1" <?= $leaveOld('is_half_day') ? 'checked' : '' ?>>Half day</label><label class="text-sm font-medium">Half-day date<input type="date" name="half_day_date" value="<?= bx_h((string) $leaveOld('half_day_date')) ?>" class="<?= $inputClass ?>"></label><label class="text-sm font-medium sm:col-span-2">Reason<textarea name="reason" class="<?= $textareaClass ?>"><?= bx_h((string) $leaveOld('reason')) ?></textarea></label><input type="hidden" name="application_status" value="SUBMITTED"><input type="hidden" name="source_reference" value="<?= bx_h((string) $leaveOld('source_reference', 'APP-' . bx_uuid())) ?>">
<?php });

$renderSimpleForm('hr-leave-allocation-modal', 'Allocate Leave', 'Post a company-scoped credit to the immutable leave ledger.', 'hr_leave_save_allocation', 'leave-requests', function () use ($leaveEmployees, $leaveTypes, $leavePeriods, $employeeOptions, $typeOptions, $leaveOld, $inputClass): void { ?>
    <label class="text-sm font-medium">Employee<select name="employee_key" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $employeeOptions($leaveEmployees, (string) $leaveOld('employee_key')); ?></select></label><label class="text-sm font-medium">Leave type<select name="leave_type_key" class="<?= $inputClass ?>" required><option value="">Select leave type</option><?php $typeOptions($leaveTypes, (string) $leaveOld('leave_type_key')); ?></select></label><label class="text-sm font-medium">Leave period<select name="leave_period_key" class="<?= $inputClass ?>" required><option value="">Select period</option><?php foreach ($leavePeriods as $period): ?><option value="<?= bx_h((string) $period['leave_period_key']) ?>"><?= bx_h((string) $period['period_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Allocated quantity<input type="number" min="0" step="0.0001" name="allocated_quantity" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">From date<input type="date" name="from_date" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">To date<input type="date" name="to_date" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Carry forward<input type="number" min="0" step="0.0001" name="carry_forward_quantity" value="0" class="<?= $inputClass ?>"></label><input type="hidden" name="allocation_status" value="SUBMITTED"><input type="hidden" name="source_reference" value="ALLOC-<?= bx_h(bx_uuid()) ?>">
<?php });

$renderSimpleForm('hr-leave-control-modal', 'Leave Control Panel', 'Apply one verified allocation to selected employees in one transaction.', 'hr_leave_bulk_allocation', 'leave-requests', function () use ($leaveEmployees, $leaveTypes, $leavePeriods, $typeOptions, $inputClass): void { ?>
    <fieldset class="sm:col-span-2"><legend class="text-sm font-medium">Employees</legend><div class="mt-2 grid max-h-36 gap-2 overflow-y-auto rounded-md border border-border p-3 sm:grid-cols-2"><?php foreach ($leaveEmployees as $employee): ?><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="employee_keys[]" value="<?= bx_h((string) $employee['employee_key']) ?>"><?= bx_h((string) $employee['employee_name']) ?></label><?php endforeach; ?></div></fieldset><label class="text-sm font-medium">Leave type<select name="leave_type_key" class="<?= $inputClass ?>" required><option value="">Select type</option><?php $typeOptions($leaveTypes); ?></select></label><label class="text-sm font-medium">Leave period<select name="leave_period_key" class="<?= $inputClass ?>" required><option value="">Select period</option><?php foreach ($leavePeriods as $period): ?><option value="<?= bx_h((string) $period['leave_period_key']) ?>"><?= bx_h((string) $period['period_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">From date<input type="date" name="from_date" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">To date<input type="date" name="to_date" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Quantity<input type="number" min="0" step="0.0001" name="allocated_quantity" class="<?= $inputClass ?>" required></label><input type="hidden" name="source_reference" value="CONTROL-<?= bx_h(bx_uuid()) ?>">
<?php });

$renderSimpleForm('hr-leave-master-modal', 'Leave Setup', 'Maintain governed leave types, periods, holiday calendars, earned schedules, and blocked dates.', 'hr_leave_save_master', 'leave-requests', function () use ($leaveTypes, $holidayLists, $leaveEmployees, $typeOptions, $inputClass): void { ?>
    <label class="text-sm font-medium sm:col-span-2">Setup record<select id="hr-leave-master-type" name="record_type" class="<?= $inputClass ?>" required><option value="LEAVE_TYPE">Leave Type</option><option value="LEAVE_PERIOD">Leave Period</option><option value="HOLIDAY_LIST">Holiday List</option><option value="HOLIDAY">Holiday</option><option value="EARNED_LEAVE_SCHEDULE">Earned Leave Schedule</option><option value="LEAVE_BLOCK_LIST">Leave Block List</option></select></label>
    <div data-leave-master-fields="LEAVE_TYPE" class="contents"><label class="text-sm font-medium">Code<input name="leave_type_code" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Name<input name="leave_type_name" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Maximum days<input type="number" min="0" step="0.0001" name="maximum_days" class="<?= $inputClass ?>" required></label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="allow_carry_forward" value="1">Allow carry forward</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="allow_negative_balance" value="1">Allow negative balance</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="include_holidays" value="1">Include holidays</label><input type="hidden" name="is_paid" value="1"><input type="hidden" name="leave_type_status" value="ACTIVE"></div>
    <div data-leave-master-fields="LEAVE_PERIOD" class="contents" hidden><label class="text-sm font-medium">Period code<input name="period_code" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">Period name<input name="period_name" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">From date<input type="date" name="from_date" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">To date<input type="date" name="to_date" class="<?= $inputClass ?>" required disabled></label><input type="hidden" name="period_status" value="ACTIVE" disabled></div>
    <div data-leave-master-fields="HOLIDAY_LIST" class="contents" hidden><label class="text-sm font-medium">List code<input name="holiday_list_code" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">List name<input name="holiday_list_name" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">From date<input type="date" name="from_date" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">To date<input type="date" name="to_date" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium sm:col-span-2">Time zone<input name="timezone_name" value="Asia/Manila" class="<?= $inputClass ?>" required disabled></label><input type="hidden" name="holiday_list_status" value="ACTIVE" disabled></div>
    <div data-leave-master-fields="HOLIDAY" class="contents" hidden><label class="text-sm font-medium">Holiday list<select name="holiday_list_key" class="<?= $inputClass ?>" required disabled><option value="">Select list</option><?php foreach ($holidayLists as $list): ?><option value="<?= bx_h((string) $list['holiday_list_key']) ?>"><?= bx_h((string) $list['holiday_list_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Holiday date<input type="date" name="holiday_date" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium sm:col-span-2">Description<input name="description" class="<?= $inputClass ?>" required disabled></label><input type="hidden" name="holiday_status" value="ACTIVE" disabled></div>
    <div data-leave-master-fields="EARNED_LEAVE_SCHEDULE" class="contents" hidden><label class="text-sm font-medium">Schedule code<input name="schedule_code" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">Schedule name<input name="schedule_name" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">Leave type<select name="leave_type_key" class="<?= $inputClass ?>" required disabled><option value="">Select type</option><?php $typeOptions($leaveTypes); ?></select></label><label class="text-sm font-medium">Frequency<select name="frequency" class="<?= $inputClass ?>" required disabled><option value="MONTHLY">Monthly</option><option value="QUARTERLY">Quarterly</option><option value="ANNUAL">Annual</option></select></label><label class="text-sm font-medium">Earned quantity<input type="number" min="0.0001" step="0.0001" name="earned_quantity" class="<?= $inputClass ?>" required disabled></label><input type="hidden" name="schedule_status" value="ACTIVE" disabled></div>
    <div data-leave-master-fields="LEAVE_BLOCK_LIST" class="contents" hidden><label class="text-sm font-medium">Block list code<input name="block_list_code" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">Block list name<input name="block_list_name" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">Blocked date<input type="date" name="blocked_dates[0][blocked_date]" class="<?= $inputClass ?>" required disabled></label><label class="text-sm font-medium">Description<input name="blocked_dates[0][description]" class="<?= $inputClass ?>" disabled></label><fieldset class="sm:col-span-2"><legend class="text-sm font-medium">Allowed employees</legend><div class="mt-2 grid max-h-32 gap-2 overflow-y-auto rounded-md border border-border p-3 sm:grid-cols-2"><?php foreach ($leaveEmployees as $employee): ?><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="allowed_employee_keys[]" value="<?= bx_h((string) $employee['employee_key']) ?>" disabled><?= bx_h((string) $employee['employee_name']) ?></label><?php endforeach; ?></div></fieldset><input type="hidden" name="block_list_status" value="ACTIVE" disabled></div>
    <script>document.getElementById('hr-leave-master-type')?.addEventListener('change',function(){const selected=this.value;document.querySelectorAll('[data-leave-master-fields]').forEach(function(group){const active=group.dataset.leaveMasterFields===selected;group.hidden=!active;group.querySelectorAll('input,select,textarea').forEach(function(control){control.disabled=!active;});});});</script>
<?php });

$renderSimpleForm('hr-leave-policy-modal', 'Leave Policy', 'Define a policy and its first annual allocation rule.', 'hr_leave_save_policy', 'leave-requests', function () use ($leaveTypes, $typeOptions, $inputClass): void { ?>
    <label class="text-sm font-medium">Policy code<input name="policy_code" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Policy name<input name="policy_name" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Leave type<select id="hr-policy-type" class="<?= $inputClass ?>" required><option value="">Select type</option><?php $typeOptions($leaveTypes); ?></select></label><label class="text-sm font-medium">Annual allocation<input id="hr-policy-allocation" type="number" min="0" step="0.0001" class="<?= $inputClass ?>" required></label><input type="hidden" name="policy_status" value="ACTIVE"><input type="hidden" name="details_json" id="hr-policy-details" value="[]"><script>document.getElementById('hr-policy-details')?.form?.addEventListener('submit',function(){this.elements.details_json.value=JSON.stringify([{leave_type_key:document.getElementById('hr-policy-type').value,annual_allocation:document.getElementById('hr-policy-allocation').value}]);});</script>
<?php });

$renderSimpleForm('hr-leave-assignment-modal', 'Assign Leave Policy', 'Set an effective, company-scoped policy assignment.', 'hr_leave_save_policy_assignment', 'leave-requests', function () use ($leaveEmployees, $leavePolicies, $leavePeriods, $employeeOptions, $inputClass): void { ?>
    <label class="text-sm font-medium">Employee<select name="employee_key" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $employeeOptions($leaveEmployees); ?></select></label><label class="text-sm font-medium">Policy<select name="leave_policy_key" class="<?= $inputClass ?>" required><option value="">Select policy</option><?php foreach ($leavePolicies as $policy): ?><option value="<?= bx_h((string) $policy['leave_policy_key']) ?>"><?= bx_h((string) $policy['policy_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Period<select name="leave_period_key" class="<?= $inputClass ?>" required><option value="">Select period</option><?php foreach ($leavePeriods as $period): ?><option value="<?= bx_h((string) $period['leave_period_key']) ?>"><?= bx_h((string) $period['period_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Effective from<input type="date" name="effective_from" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Effective until<input type="date" name="effective_until" class="<?= $inputClass ?>"></label><input type="hidden" name="assignment_status" value="ACTIVE">
<?php });

$renderSimpleForm('hr-holiday-assignment-modal', 'Assign Holiday List', 'Use governed effective dates instead of the compatibility text field.', 'hr_leave_save_holiday_assignment', 'leave-requests', function () use ($leaveEmployees, $holidayLists, $employeeOptions, $inputClass): void { ?>
    <label class="text-sm font-medium">Employee<select name="employee_key" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $employeeOptions($leaveEmployees); ?></select></label><label class="text-sm font-medium">Holiday list<select name="holiday_list_key" class="<?= $inputClass ?>" required><option value="">Select list</option><?php foreach ($holidayLists as $list): ?><option value="<?= bx_h((string) $list['holiday_list_key']) ?>"><?= bx_h((string) $list['holiday_list_name']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium">Effective from<input type="date" name="effective_from" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Effective until<input type="date" name="effective_until" class="<?= $inputClass ?>"></label><input type="hidden" name="assignment_status" value="ACTIVE">
<?php });

$renderSimpleForm('hr-leave-adjustment-modal', 'Balance Adjustment', 'Every confirmed adjustment creates one immutable ledger entry.', 'hr_leave_save_adjustment', 'leave-requests', function () use ($leaveEmployees, $leaveTypes, $employeeOptions, $typeOptions, $inputClass, $textareaClass): void { ?>
    <label class="text-sm font-medium">Employee<select name="employee_key" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $employeeOptions($leaveEmployees); ?></select></label><label class="text-sm font-medium">Leave type<select name="leave_type_key" class="<?= $inputClass ?>" required><option value="">Select type</option><?php $typeOptions($leaveTypes); ?></select></label><label class="text-sm font-medium">Posting date<input type="date" name="posting_date" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Signed quantity<input type="number" step="0.0001" name="quantity" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium sm:col-span-2">Reason<textarea name="reason" class="<?= $textareaClass ?>" required></textarea></label>
<?php });

$renderSimpleForm('hr-leave-compensatory-modal', 'Compensatory Leave', 'Submit earned leave for a separate approval decision.', 'hr_leave_save_compensatory', 'leave-requests', function () use ($leaveEmployees, $leaveTypes, $employeeOptions, $typeOptions, $inputClass, $textareaClass): void { ?>
    <label class="text-sm font-medium">Employee<select name="employee_key" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $employeeOptions($leaveEmployees); ?></select></label><label class="text-sm font-medium">Leave type<select name="leave_type_key" class="<?= $inputClass ?>" required><option value="">Select type</option><?php $typeOptions($leaveTypes); ?></select></label><label class="text-sm font-medium">Work date<input type="date" name="work_date" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Quantity<input type="number" min="0" step="0.0001" name="quantity" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium sm:col-span-2">Reason<textarea name="reason" class="<?= $textareaClass ?>"></textarea></label><input type="hidden" name="request_status" value="SUBMITTED">
<?php });

$renderSimpleForm('hr-leave-encashment-modal', 'Leave Encashment', 'Create a leave-side debit without writing to Payroll tables.', 'hr_leave_save_encashment', 'leave-requests', function () use ($leaveEmployees, $leaveTypes, $employeeOptions, $typeOptions, $inputClass): void { ?>
    <label class="text-sm font-medium">Employee<select name="employee_key" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $employeeOptions($leaveEmployees); ?></select></label><label class="text-sm font-medium">Leave type<select name="leave_type_key" class="<?= $inputClass ?>" required><option value="">Select type</option><?php $typeOptions($leaveTypes); ?></select></label><label class="text-sm font-medium">Posting date<input type="date" name="posting_date" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Quantity<input type="number" min="0" step="0.0001" name="quantity" class="<?= $inputClass ?>" required></label><input type="hidden" name="encashment_status" value="SUBMITTED">
<?php });

$renderSimpleForm('hr-leave-review-modal', 'Review Leave Application', 'Approval posts the debit and notification intent in the owner transaction.', 'hr_leave_transition_application', 'leave-approvals', function () use ($leaveApplications, $inputClass): void { ?>
    <label class="text-sm font-medium sm:col-span-2">Application<select name="leave_application_key" class="<?= $inputClass ?>" required><option value="">Select submitted application</option><?php foreach ($leaveApplications as $application): if ((string) $application['application_status'] !== 'SUBMITTED') continue; ?><option value="<?= bx_h((string) $application['leave_application_key']) ?>"><?= bx_h((string) $application['employee_name']) ?> · <?= bx_h((string) $application['from_date']) ?></option><?php endforeach; ?></select></label><label class="text-sm font-medium sm:col-span-2">Decision<select name="application_status" class="<?= $inputClass ?>" required><option value="APPROVED">Approve</option><option value="REJECTED">Reject</option><option value="CANCELLED">Cancel request</option></select></label>
<?php }); ?>
