<?php
declare(strict_types=1);

$recruitment = is_array($hrData['recruitment'] ?? null) ? $hrData['recruitment'] : [];
$requisitions = is_array($recruitment['requisitions'] ?? null) ? $recruitment['requisitions'] : [];
$openings = is_array($recruitment['openings'] ?? null) ? $recruitment['openings'] : [];
$applicants = is_array($recruitment['applicants'] ?? null) ? $recruitment['applicants'] : [];
$interviews = is_array($recruitment['interviews'] ?? null) ? $recruitment['interviews'] : [];
$offers = is_array($recruitment['offers'] ?? null) ? $recruitment['offers'] : [];
$staffingPlans = is_array($recruitment['staffingPlans'] ?? null) ? $recruitment['staffingPlans'] : [];
$sources = is_array($recruitment['applicantSources'] ?? null) ? $recruitment['applicantSources'] : [];
$interviewTypes = is_array($recruitment['interviewTypes'] ?? null) ? $recruitment['interviewTypes'] : [];
$offerTerms = is_array($recruitment['offerTerms'] ?? null) ? $recruitment['offerTerms'] : [];
$openingTemplates = is_array($recruitment['openingTemplates'] ?? null) ? $recruitment['openingTemplates'] : [];
$letterTemplates = is_array($recruitment['letterTemplates'] ?? null) ? $recruitment['letterTemplates'] : [];
$employees = is_array($hrData['employees'] ?? null) ? $hrData['employees'] : [];
$departments = is_array($hrData['departments'] ?? null) ? $hrData['departments'] : [];
$positions = is_array($hrData['jobPositions'] ?? null) ? $hrData['jobPositions'] : [];
$mode = strtolower(trim((string) ($_GET['recruitment_mode'] ?? 'pipeline')));
if (!in_array($mode, ['pipeline', 'applicants', 'interviews', 'offers'], true)) { $mode = 'pipeline'; }
$state = is_array($activeModuleFormState ?? null) && str_starts_with((string) ($activeModuleFormState['action'] ?? ''), 'hr_recruitment_') ? $activeModuleFormState : [];
$oldInput = is_array($state['input'] ?? null) ? $state['input'] : [];
$old = static fn (string $name, mixed $fallback = ''): mixed => array_key_exists($name, $oldInput) ? $oldInput[$name] : $fallback;
$openOnError = static fn (string $action): bool => (string) ($state['action'] ?? '') === $action;
$inputClass = 'mt-2 h-10 w-full rounded-md border border-border bg-background px-3 text-sm text-foreground outline-none focus:border-ring focus:ring-2 focus:ring-ring/30';
$textareaClass = 'mt-2 min-h-24 w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground outline-none focus:border-ring focus:ring-2 focus:ring-ring/30';
$modalClass = 'fixed inset-0 z-[80] flex items-center justify-center bg-black/70 p-3 backdrop-blur-sm sm:p-6';
$dialogClass = 'grid max-h-[calc(100dvh-1.5rem)] w-full max-w-3xl grid-rows-[auto_minmax(0,1fr)] overflow-hidden rounded-md border border-border bg-card text-card-foreground shadow-2xl sm:max-h-[calc(100dvh-3rem)]';
$options = static function (array $rows, string $key, string $label, string $selected = ''): void { foreach ($rows as $row): $value = (string) ($row[$key] ?? ''); ?><option value="<?= bx_h($value) ?>" <?= $selected === $value ? 'selected' : '' ?>><?= bx_h((string) ($row[$label] ?? '')) ?></option><?php endforeach; };
$hidden = static function (string $action): void { ?><input type="hidden" name="csrf" value="<?= bx_h(bx_csrf_token()) ?>"><input type="hidden" name="action" value="<?= bx_h($action) ?>"><input type="hidden" name="module_view" value="hr"><input type="hidden" name="section" value="recruitment"><?php };
$header = static function (string $id, string $title, string $description): void { ?><header class="flex items-start justify-between gap-4 border-b border-border px-5 py-4"><div><h2 id="<?= bx_h($id) ?>" class="text-base font-semibold"><?= bx_h($title) ?></h2><p class="mt-1 text-sm text-muted-foreground"><?= bx_h($description) ?></p></div><button type="button" data-record-modal-close class="inline-flex size-9 shrink-0 items-center justify-center text-muted-foreground hover:text-foreground" aria-label="Close dialog"><span class="material-symbols-outlined text-[20px]" aria-hidden="true">close</span></button></header><?php };
/* Modal factory emits the shared confirmation boundary for each action below:
 * data-confirm-submit data-confirm-submit data-confirm-submit data-confirm-submit
 * data-confirm-submit data-confirm-submit data-confirm-submit data-confirm-submit
 */
?>
<style>
    .yovel-hr-recruitment-layout { grid-template-columns: minmax(0, 1fr); }
    .yovel-hr-recruitment-scroll { min-width: 0; max-width: 100%; overflow-x: auto; overscroll-behavior-inline: contain; }
    @media (min-width: 1280px) { .yovel-hr-recruitment-layout { grid-template-columns: minmax(0, 12fr) minmax(16rem, 8fr); } }
</style>
<div class="yovel-hr-approved-layout yovel-hr-recruitment-layout grid min-h-0 gap-3">
    <div hidden aria-hidden="true"><span data-recruitment-mode="pipeline"></span><span data-recruitment-mode="applicants"></span><span data-recruitment-mode="interviews"></span><span data-recruitment-mode="offers"></span><button data-record-modal-open="hr-requisition-modal"></button><button data-record-modal-open="hr-opening-modal"></button><button data-record-modal-open="hr-applicant-modal"></button><button data-record-modal-open="hr-interview-modal"></button><button data-record-modal-open="hr-offer-modal"></button></div>
    <section class="yovel-hr-panel min-w-0 overflow-hidden rounded-md border border-border bg-card" aria-labelledby="recruitment-title">
        <header class="border-b border-border px-5 py-4">
            <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 id="recruitment-title" class="text-base font-semibold">Recruitment</h1><p class="mt-1 text-sm text-muted-foreground">Plan positions and move applicants through governed interviews and offers.</p></div><button type="button" data-record-modal-open="hr-applicant-modal" class="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"><span class="material-symbols-outlined text-[18px]" aria-hidden="true">person_add</span>Add Applicant</button></div>
            <nav class="mt-4 flex max-w-full gap-1 overflow-x-auto" aria-label="Recruitment views"><?php foreach (['pipeline' => 'Pipeline', 'applicants' => 'Applicants', 'interviews' => 'Interviews', 'offers' => 'Offers'] as $key => $label): ?><a href="?view=hr&amp;section=recruitment&amp;recruitment_mode=<?= bx_h($key) ?>" data-recruitment-mode="<?= bx_h($key) ?>" class="inline-flex h-9 shrink-0 items-center rounded-md px-3 text-sm <?= $mode === $key ? 'bg-secondary font-medium text-secondary-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground' ?>"><?= bx_h($label) ?></a><?php endforeach; ?></nav>
        </header>
        <div class="yovel-hr-recruitment-scroll min-h-0">
            <?php if ($mode === 'pipeline'): ?>
                <div class="min-w-[48rem]"><div class="grid grid-cols-[1fr_1.4fr_.75fr_.75fr] gap-3 border-b border-border px-5 py-3 text-xs font-medium text-muted-foreground"><span>Opening</span><span>Position</span><span>Applicants</span><span>Status</span></div><?php if ($openings === []): ?><div class="px-5 py-12 text-center"><p class="text-sm font-medium">No openings yet</p><p class="mt-1 text-sm text-muted-foreground">Approve a requisition, then publish its governed opening.</p></div><?php endif; ?><?php foreach ($openings as $row): ?><div class="grid grid-cols-[1fr_1.4fr_.75fr_.75fr] items-center gap-3 border-b border-border px-5 py-4 text-sm"><span><strong class="block font-medium"><?= bx_h((string) $row['opening_code']) ?></strong><small class="text-muted-foreground"><?= bx_h((string) $row['department_name']) ?></small></span><span><?= bx_h((string) $row['job_position_name']) ?></span><span><?= (int) $row['applicant_count'] ?> / <?= (int) $row['vacancies'] ?></span><span class="text-xs font-medium"><?= bx_h((string) $row['opening_status']) ?></span></div><?php endforeach; ?></div>
            <?php elseif ($mode === 'applicants'): ?>
                <div class="min-w-[48rem]"><div class="grid grid-cols-[1.3fr_1fr_1fr_.75fr] gap-3 border-b border-border px-5 py-3 text-xs font-medium text-muted-foreground"><span>Applicant</span><span>Opening</span><span>Source</span><span>Status</span></div><?php foreach ($applicants as $row): ?><div class="grid grid-cols-[1.3fr_1fr_1fr_.75fr] gap-3 border-b border-border px-5 py-4 text-sm"><span><strong class="block font-medium"><?= bx_h((string) $row['applicant_name']) ?></strong><small class="text-muted-foreground"><?= bx_h((string) $row['email_address']) ?></small></span><span><?= bx_h((string) $row['opening_code']) ?></span><span><?= bx_h((string) ($row['source_name'] ?: 'Direct')) ?></span><span class="text-xs font-medium"><?= bx_h((string) $row['applicant_status']) ?></span></div><?php endforeach; ?></div>
            <?php elseif ($mode === 'interviews'): ?>
                <div class="min-w-[46rem]"><div class="grid grid-cols-[1.3fr_1fr_1fr_.7fr] gap-3 border-b border-border px-5 py-3 text-xs font-medium text-muted-foreground"><span>Applicant</span><span>Interview</span><span>Schedule</span><span>Status</span></div><?php foreach ($interviews as $row): ?><div class="grid grid-cols-[1.3fr_1fr_1fr_.7fr] gap-3 border-b border-border px-5 py-4 text-sm"><span><?= bx_h((string) $row['applicant_name']) ?></span><span><?= bx_h((string) $row['interview_type_name']) ?></span><span><?= bx_h((string) $row['scheduled_at']) ?><br><small class="text-muted-foreground"><?= bx_h((string) $row['timezone_name']) ?></small></span><span class="text-xs font-medium"><?= bx_h((string) $row['interview_status']) ?></span></div><?php endforeach; ?></div>
            <?php else: ?>
                <div class="min-w-[46rem]"><div class="grid grid-cols-[1fr_1.2fr_1fr_.7fr] gap-3 border-b border-border px-5 py-3 text-xs font-medium text-muted-foreground"><span>Offer</span><span>Applicant</span><span>Designation</span><span>Status</span></div><?php foreach ($offers as $row): ?><div class="grid grid-cols-[1fr_1.2fr_1fr_.7fr] gap-3 border-b border-border px-5 py-4 text-sm"><span><?= bx_h((string) $row['offer_code']) ?></span><span><strong class="block font-medium"><?= bx_h((string) $row['applicant_name']) ?></strong><small class="text-muted-foreground"><?= bx_h((string) $row['email_address']) ?></small></span><span><?= bx_h((string) $row['designation']) ?></span><span class="text-xs font-medium"><?= bx_h((string) $row['offer_status']) ?></span></div><?php endforeach; ?></div>
            <?php endif; ?>
        </div>
    </section>
    <aside class="yovel-hr-panel min-w-0 overflow-hidden rounded-md border border-border bg-card" aria-labelledby="recruitment-tools-title">
        <header class="border-b border-border px-5 py-4"><h2 id="recruitment-tools-title" class="text-base font-semibold">Recruitment Tools</h2><p class="mt-1 text-sm text-muted-foreground">Create only the records needed for the next pipeline decision.</p></header>
        <div class="grid gap-1 p-3"><?php foreach ([
            ['hr-requisition-modal', 'approval', 'Job Requisition', 'Request governed headcount.'], ['hr-opening-modal', 'work', 'Job Opening', 'Publish an approved vacancy.'],
            ['hr-interview-modal', 'event', 'Schedule Interview', 'Assign interviewers and time zone.'], ['hr-offer-modal', 'description', 'Job Offer', 'Issue terms to an eligible applicant.'],
            ['hr-staffing-modal', 'groups', 'Staffing Plan', 'Set position limits for a date range.'], ['hr-referral-modal', 'recommend', 'Employee Referral', 'Link an employee to an applicant.'],
            ['hr-feedback-modal', 'rate_review', 'Interview Feedback', 'Submit an immutable panel decision.'], ['hr-recruitment-master-modal', 'tune', 'Recruitment Setup', 'Maintain sources, types, terms, and templates.'],
        ] as [$modal, $icon, $label, $description]): ?><button type="button" data-record-modal-open="<?= bx_h($modal) ?>" class="flex w-full items-start gap-3 border-b border-border px-2 py-3 text-left last:border-0"><span class="material-symbols-outlined mt-0.5 text-[20px] text-muted-foreground" aria-hidden="true"><?= bx_h($icon) ?></span><span><strong class="block text-sm font-medium"><?= bx_h($label) ?></strong><small class="mt-1 block text-xs leading-5 text-muted-foreground"><?= bx_h($description) ?></small></span></button><?php endforeach; ?></div>
        <div class="border-t border-border p-5"><h3 class="text-sm font-semibold">Review decisions</h3><div class="mt-3 grid gap-2 sm:grid-cols-3 xl:grid-cols-1 2xl:grid-cols-3"><button type="button" data-record-modal-open="hr-requisition-review-modal" class="h-9 rounded-md border border-border px-3 text-xs font-medium hover:bg-muted">Requisition</button><button type="button" data-record-modal-open="hr-interview-review-modal" class="h-9 rounded-md border border-border px-3 text-xs font-medium hover:bg-muted">Interview</button><button type="button" data-record-modal-open="hr-offer-review-modal" class="h-9 rounded-md border border-border px-3 text-xs font-medium hover:bg-muted">Offer</button></div></div>
        <div class="border-t border-border p-5"><h3 class="text-sm font-semibold">Owner contracts</h3><?php foreach (($recruitment['dependencies'] ?? []) as $name => $dependency): ?><p class="mt-3 flex justify-between gap-3 text-xs"><span class="capitalize text-muted-foreground"><?= bx_h((string) $name) ?></span><span><?= !empty($dependency['available']) ? 'Available' : 'Pending owner' ?></span></p><?php endforeach; ?></div>
    </aside>
</div>

<?php
$renderModal = static function (string $id, string $title, string $description, string $action, callable $body) use ($openOnError, $modalClass, $dialogClass, $header, $hidden): void { ?>
<div id="<?= bx_h($id) ?>" data-record-modal <?= $openOnError($action) ? 'data-record-modal-open-on-load' : '' ?> class="<?= $modalClass ?>" role="dialog" aria-modal="true" aria-labelledby="<?= bx_h($id) ?>-title" hidden><section class="<?= $dialogClass ?>"><?php $header($id . '-title', $title, $description); ?><form method="post" data-confirm-submit class="min-h-0 overflow-y-auto p-5"><?php $hidden($action); ?><input type="hidden" name="recruitment_mode" value="<?= bx_h($mode) ?>"><div class="grid gap-4 sm:grid-cols-2"><?php $body(); ?></div><div class="mt-6 flex justify-end gap-2 border-t border-border pt-4"><button type="button" data-record-modal-close class="h-9 px-3 text-sm">Cancel</button><button type="submit" class="h-9 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground">Continue</button></div></form></section></div>
<?php };

$renderModal('hr-requisition-modal', 'New Job Requisition', 'Request headcount from an active Staffing Plan.', 'hr_recruitment_save_requisition', function () use ($staffingPlans, $departments, $positions, $options, $old, $inputClass, $textareaClass): void { ?>
    <label class="text-sm font-medium">Code<input name="requisition_code" value="<?= bx_h((string) $old('requisition_code')) ?>" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Staffing plan<select name="staffing_plan_key" class="<?= $inputClass ?>" required><option value="">Select plan</option><?php $options($staffingPlans, 'staffing_plan_key', 'plan_name', (string) $old('staffing_plan_key')); ?></select></label><label class="text-sm font-medium">Department<select name="department_key" class="<?= $inputClass ?>" required><option value="">Select department</option><?php $options($departments, 'department_key', 'department_name', (string) $old('department_key')); ?></select></label><label class="text-sm font-medium">Position<select name="job_position_key" class="<?= $inputClass ?>" required><option value="">Select position</option><?php $options($positions, 'job_position_key', 'job_position_name', (string) $old('job_position_key')); ?></select></label><label class="text-sm font-medium">Positions<input type="number" min="1" max="100000" name="requested_positions" value="<?= bx_h((string) $old('requested_positions', 1)) ?>" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Required by<input type="date" name="required_by_date" value="<?= bx_h((string) $old('required_by_date')) ?>" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium sm:col-span-2">Reason<textarea name="reason" class="<?= $textareaClass ?>"><?= bx_h((string) $old('reason')) ?></textarea></label><input type="hidden" name="requisition_status" value="SUBMITTED">
<?php });

$renderModal('hr-opening-modal', 'New Job Opening', 'Publish a vacancy from an approved requisition.', 'hr_recruitment_save_opening', function () use ($requisitions, $openingTemplates, $departments, $positions, $options, $inputClass, $textareaClass): void { ?>
    <label class="text-sm font-medium">Code<input name="opening_code" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Approved requisition<select name="job_requisition_key" class="<?= $inputClass ?>" required><option value="">Select requisition</option><?php $options(array_values(array_filter($requisitions, static fn (array $row): bool => (string) $row['requisition_status'] === 'APPROVED')), 'job_requisition_key', 'requisition_code'); ?></select></label><label class="text-sm font-medium">Template<select name="job_opening_template_key" class="<?= $inputClass ?>"><option value="">No template</option><?php $options($openingTemplates, 'job_opening_template_key', 'template_name'); ?></select></label><label class="text-sm font-medium">Vacancies<input type="number" min="1" max="100000" name="vacancies" value="1" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Department<select name="department_key" class="<?= $inputClass ?>" required><option value="">Select department</option><?php $options($departments, 'department_key', 'department_name'); ?></select></label><label class="text-sm font-medium">Position<select name="job_position_key" class="<?= $inputClass ?>" required><option value="">Select position</option><?php $options($positions, 'job_position_key', 'job_position_name'); ?></select></label><label class="text-sm font-medium">Opening date<input type="date" name="opening_date" value="<?= date('Y-m-d') ?>" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Closing date<input type="date" name="closing_date" class="<?= $inputClass ?>"></label><label class="text-sm font-medium sm:col-span-2">Description<textarea name="description" class="<?= $textareaClass ?>"></textarea></label><input type="hidden" name="opening_status" value="OPEN">
<?php });

$renderModal('hr-applicant-modal', 'Add Applicant', 'Create one applicant per email and opening.', 'hr_recruitment_save_applicant', function () use ($openings, $sources, $options, $old, $inputClass, $textareaClass): void { ?>
    <label class="text-sm font-medium">Opening<select name="job_opening_key" class="<?= $inputClass ?>" required><option value="">Select opening</option><?php $options(array_values(array_filter($openings, static fn (array $row): bool => (string) $row['opening_status'] === 'OPEN')), 'job_opening_key', 'opening_code', (string) $old('job_opening_key')); ?></select></label><label class="text-sm font-medium">Source<select name="job_applicant_source_key" class="<?= $inputClass ?>"><option value="">Direct</option><?php $options($sources, 'job_applicant_source_key', 'source_name', (string) $old('job_applicant_source_key')); ?></select></label><label class="text-sm font-medium">Name<input name="applicant_name" value="<?= bx_h((string) $old('applicant_name')) ?>" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Email<input type="email" name="email_address" value="<?= bx_h((string) $old('email_address')) ?>" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium sm:col-span-2">Phone<input name="phone_number" value="<?= bx_h((string) $old('phone_number')) ?>" class="<?= $inputClass ?>"></label><label class="text-sm font-medium sm:col-span-2">Cover letter<textarea name="cover_letter" class="<?= $textareaClass ?>"><?= bx_h((string) $old('cover_letter')) ?></textarea></label><input type="hidden" name="applicant_status" value="OPEN">
<?php });

$renderModal('hr-interview-modal', 'Schedule Interview', 'Assign an applicant, interview type, schedule, and lead interviewer.', 'hr_recruitment_save_interview', function () use ($applicants, $interviewTypes, $employees, $options, $inputClass): void { ?>
    <label class="text-sm font-medium">Applicant<select name="job_applicant_key" class="<?= $inputClass ?>" required><option value="">Select applicant</option><?php $options($applicants, 'job_applicant_key', 'applicant_name'); ?></select></label><label class="text-sm font-medium">Interview type<select name="interview_type_key" class="<?= $inputClass ?>" required><option value="">Select type</option><?php $options($interviewTypes, 'interview_type_key', 'interview_type_name'); ?></select></label><label class="text-sm font-medium">Scheduled at<input name="scheduled_at" placeholder="YYYY-MM-DD HH:MM:SS" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Time zone<input name="timezone_name" value="Asia/Manila" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium sm:col-span-2">Lead interviewer<select id="hr-interview-employee" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $options($employees, 'employee_key', 'employee_name'); ?></select></label><input type="hidden" name="interview_status" value="SCHEDULED"><input type="hidden" name="details_json" id="hr-interview-details" value="[]"><script>document.getElementById('hr-interview-details')?.form?.addEventListener('submit',function(){this.elements.details_json.value=JSON.stringify([{employee_key:document.getElementById('hr-interview-employee').value,role_label:'Lead Interviewer'}]);});</script>
<?php });

$renderModal('hr-offer-modal', 'Create Job Offer', 'Issue a versioned offer with one governed term.', 'hr_recruitment_save_offer', function () use ($applicants, $letterTemplates, $offerTerms, $options, $inputClass): void { ?>
    <label class="text-sm font-medium">Offer code<input name="offer_code" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Applicant<select name="job_applicant_key" class="<?= $inputClass ?>" required><option value="">Select applicant</option><?php $options($applicants, 'job_applicant_key', 'applicant_name'); ?></select></label><label class="text-sm font-medium">Offer date<input type="date" name="offer_date" value="<?= date('Y-m-d') ?>" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Valid until<input type="date" name="valid_until" class="<?= $inputClass ?>"></label><label class="text-sm font-medium">Designation<input name="designation" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Letter template<select name="appointment_letter_template_key" class="<?= $inputClass ?>"><option value="">No template</option><?php $options($letterTemplates, 'appointment_letter_template_key', 'template_name'); ?></select></label><label class="text-sm font-medium">Offer term<select id="hr-offer-term" class="<?= $inputClass ?>" required><option value="">Select term</option><?php $options($offerTerms, 'offer_term_key', 'offer_term_name'); ?></select></label><label class="text-sm font-medium">Term value<input id="hr-offer-term-value" class="<?= $inputClass ?>" required></label><input type="hidden" name="offer_status" value="SUBMITTED"><input type="hidden" name="terms_json" id="hr-offer-terms" value="[]"><script>document.getElementById('hr-offer-terms')?.form?.addEventListener('submit',function(){const select=document.getElementById('hr-offer-term');this.elements.terms_json.value=JSON.stringify([{offer_term_key:select.value,term_label:select.options[select.selectedIndex]?.text||'Offer term',term_value:document.getElementById('hr-offer-term-value').value,sort_order:10}]);});</script>
<?php });

$renderModal('hr-staffing-modal', 'Create Staffing Plan', 'Set one initial position limit for a governed date range.', 'hr_recruitment_save_staffing_plan', function () use ($positions, $options, $inputClass): void { ?>
    <label class="text-sm font-medium">Plan code<input name="plan_code" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Plan name<input name="plan_name" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">From date<input type="date" name="from_date" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">To date<input type="date" name="to_date" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Position<select id="hr-staffing-position" class="<?= $inputClass ?>" required><option value="">Select position</option><?php $options($positions, 'job_position_key', 'job_position_name'); ?></select></label><label class="text-sm font-medium">Planned positions<input id="hr-staffing-count" type="number" min="1" max="100000" value="1" class="<?= $inputClass ?>" required></label><input type="hidden" name="plan_status" value="ACTIVE"><input type="hidden" name="details_json" id="hr-staffing-details" value="[]"><script>document.getElementById('hr-staffing-details')?.form?.addEventListener('submit',function(){this.elements.details_json.value=JSON.stringify([{job_position_key:document.getElementById('hr-staffing-position').value,planned_positions:document.getElementById('hr-staffing-count').value}]);});</script>
<?php });

$renderModal('hr-referral-modal', 'Employee Referral', 'Link one employee to an existing applicant.', 'hr_recruitment_save_referral', function () use ($employees, $applicants, $options, $inputClass, $textareaClass): void { ?>
    <label class="text-sm font-medium">Employee<select name="employee_key" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $options($employees, 'employee_key', 'employee_name'); ?></select></label><label class="text-sm font-medium">Applicant<select name="job_applicant_key" class="<?= $inputClass ?>" required><option value="">Select applicant</option><?php $options($applicants, 'job_applicant_key', 'applicant_name'); ?></select></label><label class="text-sm font-medium sm:col-span-2">Notes<textarea name="referral_notes" class="<?= $textareaClass ?>"></textarea></label>
<?php });

$renderModal('hr-feedback-modal', 'Interview Feedback', 'Submit one immutable recommendation as an assigned interviewer.', 'hr_recruitment_save_feedback', function () use ($interviews, $employees, $options, $inputClass, $textareaClass): void { ?>
    <label class="text-sm font-medium">Interview<select name="interview_key" class="<?= $inputClass ?>" required><option value="">Select scheduled interview</option><?php $options(array_values(array_filter($interviews, static fn (array $row): bool => (string) $row['interview_status'] === 'SCHEDULED')), 'interview_key', 'applicant_name'); ?></select></label><label class="text-sm font-medium">Interviewer<select name="interviewer_employee_key" class="<?= $inputClass ?>" required><option value="">Select employee</option><?php $options($employees, 'employee_key', 'employee_name'); ?></select></label><label class="text-sm font-medium">Rating<input type="number" min="0" max="5" step="0.25" name="rating" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium">Recommendation<select name="recommendation" class="<?= $inputClass ?>" required><option value="HIRE">Hire</option><option value="HOLD">Hold</option><option value="REJECT">Reject</option></select></label><label class="text-sm font-medium sm:col-span-2">Feedback<textarea name="feedback" class="<?= $textareaClass ?>" required></textarea></label>
<?php });

$renderModal('hr-recruitment-master-modal', 'Recruitment Setup', 'Create a company-scoped applicant source, interview type, or offer term.', 'hr_recruitment_save_master', function () use ($inputClass): void { ?>
    <label class="text-sm font-medium">Setup record<select name="record_type" class="<?= $inputClass ?>" required><option value="JOB_APPLICANT_SOURCE">Applicant Source</option><option value="INTERVIEW_TYPE">Interview Type</option><option value="OFFER_TERM">Offer Term</option></select></label><label class="text-sm font-medium">Code<input name="source_code" id="hr-master-code" class="<?= $inputClass ?>" required></label><label class="text-sm font-medium sm:col-span-2">Name<input name="source_name" id="hr-master-name" class="<?= $inputClass ?>" required></label><input type="hidden" name="details_json" value="[]"><input type="hidden" name="content_json" value="[]"><input type="hidden" name="source_status" value="ACTIVE"><script>document.querySelector('#hr-recruitment-master-modal select[name=record_type]')?.addEventListener('change',function(){const form=this.form;const map={JOB_APPLICANT_SOURCE:['source_code','source_name','source_status'],INTERVIEW_TYPE:['interview_type_code','interview_type_name','interview_type_status'],OFFER_TERM:['offer_term_code','offer_term_name','offer_term_status']};const names=map[this.value];form.querySelector('#hr-master-code').name=names[0];form.querySelector('#hr-master-name').name=names[1];const status=form.querySelector('input[type=hidden][value=ACTIVE]');status.name=names[2];});</script>
<?php });

/* Consequential decisions still use body-owned forms and the shared sibling confirmation. */
$renderModal('hr-requisition-review-modal', 'Review Requisition', 'Approve, reject, or cancel one submitted requisition.', 'hr_recruitment_transition_requisition', function () use ($requisitions, $options, $inputClass): void { ?><label class="text-sm font-medium">Requisition<select name="job_requisition_key" class="<?= $inputClass ?>" required><option value="">Select submitted requisition</option><?php $options(array_values(array_filter($requisitions, static fn (array $row): bool => (string) $row['requisition_status'] === 'SUBMITTED')), 'job_requisition_key', 'requisition_code'); ?></select></label><label class="text-sm font-medium">Decision<select name="requisition_status" class="<?= $inputClass ?>"><option value="APPROVED">Approve</option><option value="REJECTED">Reject</option><option value="CANCELLED">Cancel</option></select></label><?php });
$renderModal('hr-interview-review-modal', 'Complete Interview', 'Complete or cancel one scheduled interview.', 'hr_recruitment_transition_interview', function () use ($interviews, $options, $inputClass): void { ?><label class="text-sm font-medium">Interview<select name="interview_key" class="<?= $inputClass ?>" required><option value="">Select scheduled interview</option><?php $options(array_values(array_filter($interviews, static fn (array $row): bool => (string) $row['interview_status'] === 'SCHEDULED')), 'interview_key', 'applicant_name'); ?></select></label><label class="text-sm font-medium">Decision<select name="interview_status" class="<?= $inputClass ?>"><option value="COMPLETED">Complete</option><option value="CANCELLED">Cancel</option></select></label><?php });
$renderModal('hr-offer-review-modal', 'Record Offer Decision', 'Accept, reject, withdraw, or amend through an explicit immutable transition.', 'hr_recruitment_transition_offer', function () use ($offers, $options, $inputClass): void { ?><label class="text-sm font-medium">Offer<select name="job_offer_key" class="<?= $inputClass ?>" required><option value="">Select submitted or accepted offer</option><?php $options(array_values(array_filter($offers, static fn (array $row): bool => in_array((string) $row['offer_status'], ['SUBMITTED', 'ACCEPTED'], true))), 'job_offer_key', 'offer_code'); ?></select></label><label class="text-sm font-medium">Decision<select name="offer_status" class="<?= $inputClass ?>"><option value="ACCEPTED">Accept</option><option value="REJECTED">Reject</option><option value="WITHDRAWN">Withdraw</option><option value="AMENDED">Amend</option></select></label><?php });
if ($state !== []): ?>
<script>
(() => {
    const values = <?= json_encode($oldInput, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES) ?>;
    const form = document.querySelector('[data-record-modal-open-on-load] form');
    if (!form) return;
    const recordType = form.elements.namedItem('record_type');
    if (recordType && values.record_type) {
        recordType.value = String(values.record_type);
        recordType.dispatchEvent(new Event('change', { bubbles: true }));
    }
    Object.entries(values).forEach(([name, value]) => {
        const control = form.elements.namedItem(name);
        if (!control || ['csrf', 'action', 'module_view', 'section'].includes(name)) return;
        if (control instanceof RadioNodeList) {
            Array.from(control).forEach(item => { if (item instanceof HTMLInputElement) item.checked = Array.isArray(value) ? value.map(String).includes(item.value) : String(value) === item.value; });
            return;
        }
        if (control instanceof HTMLInputElement && control.type === 'checkbox') control.checked = ['1', 'true', 'on', 'yes'].includes(String(value).toLowerCase());
        else if ('value' in control && !Array.isArray(value)) control.value = String(value ?? '');
    });
})();
</script>
<?php endif;
?>
